### ISSUE TITLE
solr_tests test_multiprocessing sometimes fail

### ISSUE THREAD

**Issue by jorgecarleitao** [django-haystack/django-haystack#1001]
This test is making some pull requests to fail the travis, which is making it more difficult to properly evaluate them.

Examples:
* #951, [this build](https://travis-ci.org/toastdriven/django-haystack/jobs/21842097#L1359)
* #978, [this build](https://travis-ci.org/toastdriven/django-haystack/jobs/21307417#L643)

For now, this is just documenting the occurrence.

**Comment by acdha** [comment]
How tedious: 1ab44b56c533c4cc262d543b9794aa7ddd2d63c6 shows every sign of fixing this issue (tested with a few thousand repeats of that test) but it appears to hang on Python 2.6's multiprocessing:

https://travis-ci.org/acdha/django-haystack/builds/48965711

Time for more testing and maybe just disabling parallel workers on 2.6…
