### ISSUE TITLE
KeyError: u'_source' in Elastic Search backend

### ISSUE THREAD

**Issue by askaliuk** [django-haystack/django-haystack#1019]
Call:
```
SearchQuerySet().auto_query('query')[:20]
```

Full stacktrace:
```
  File "/python2.7/site-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
  File "/django-haystack/haystack/query.py", line 268, in __getitem__
    self._fill_cache(start, bound)
  File "/django-haystack/haystack/query.py", line 630, in _fill_cache
    return super(ValuesListSearchQuerySet, self)._fill_cache(start, end, **kwargs)
  File "/django-haystack/haystack/query.py", line 166, in _fill_cache
    results = self.query.get_results(**kwargs)
  File "/django-haystack/haystack/backends/__init__.py", line 644, in get_results
    self.run(**kwargs)
  File "/django-haystack/haystack/backends/elasticsearch_backend.py", line 912, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "/django-haystack/haystack/backends/__init__.py", line 34, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "/django-haystack/haystack/backends/elasticsearch_backend.py", line 498, in search
    distance_point=kwargs.get('distance_point'), geo_sort=geo_sort)
  File "/django-haystack/haystack/backends/elasticsearch_backend.py", line 574, in _process_results
    source = raw_result['_source']
KeyError: u'_source'
```

Environment:
1. Haystack dev version (https://github.com/toastdriven/django-haystack/commit/0043fac849dbb6cda7a4597821b27cbb7e87f9d9)
2. elasticsearch==1.0.0
3. Elastic Search 1.2.1

I've checked raw result. It does not contain "_source".
Here it is:
```
{u'_score': 0.076713204, u'_type': u'modelresult', u'_id': u'blogs.post.3', u'_index': u'haystack'}
```

**Comment by cgreene** [comment]
This also affects .values_list() in django-haystack 2.3.1.

**Comment by cpury** [comment]
Can confirm for `.values()` and `.values_list()`

**Comment by acdha** [comment]
It looks like both @metalpriest's https://github.com/moneypark/django-haystack/commit/9db4de3362c20224d9b068eb8427df5ceaa53dea and @xsamurai's https://github.com/xsamurai/django-haystack/commit/b7aa6493db6cc4a687a861113934cc0df232b5ac fix this. 

Has anyone else had time to test this? A pull request with a test which fails before the patch would be a fast way to get this merged; otherwise I'll try to get to it later this week.

**Comment by acdha** [comment]
Never mind, that commit was merged awhile back: 

https://github.com/django-haystack/django-haystack/commit/3571bdead31728923e2739c0ed7212696f501994#diff-86da7062c02bc3ba1fe14dd640207b78

The better question: has anyone who's experienced this problem had time to test against the current master branch to confirm that it fixes the problem?

**Comment by cpury** [comment]
@acdha Can confirm `.values_list()` works for me on current master!
Do you see any risk in me using master in a production environment?
