### ISSUE TITLE
Please ship a new version

### ISSUE THREAD

**Issue by frewsxcv** [django-haystack/django-haystack#1029]
Django 1.7 is almost out and the latest stable version of this library is still not compatible with 1.6 as per https://github.com/toastdriven/django-haystack/issues/908

Please push a new version to PyPi so we can stop pointing to master. If there is something that needs to be done to make this happen, please let the community know, we'd love to help! If you just don't have the time, add me as a non-owner role on PyPi and I'd be happy to push a new version for you

**Comment by galuszkak** [comment]
This should be closed as relase was done. //cc @acdha
