### ISSUE TITLE
connection_router is not actually a singleton when custom routers are used

### ISSUE THREAD

**Issue by phill-tornroth** [django-haystack/django-haystack#1034]
In haystack/__init__.py a pattern is employed where connection_router is assigned to a ConnectionRouter instance with no custom routers, and then if settings says so we'll create a ConnectionRouter with the custom classes.

Problem is, ConnectionRouter constructs those custom Router classes.. and there's a pretty good chance they live in modules that (directly or indirectly) import some haystack stuff (lots of my haystack customization was in the same module of mine).

When that happens it's likely that things like haystack/indexes are gonna do a `from haystack import connections, connection_router` and permanently end up with the empty connection_router instance, which the stack is currently attempting to replace.

In my eyes, the only really solid solution is to make it impossible for there to be two instances assigned to haystack.connection_router at different times. The most reasonable way I came up with for doing that is to lazily load the router classes at first-use.

Here's the commit on my fork, which is branched off of v2.0.0 at the moment. I'm happy to open up a pull request also but the routing functionality seems potentially experimental and without tests (unless I've overlooked them). So figured I'd open the issue first instead and see what folks think.

https://github.com/phill-tornroth/django-haystack/commit/12536f4ee50c13786f70343dde72391a017212f7

**Comment by skirsdeda** [comment]
I hit this as well. Using **aldryn_search.router.LanguageRouter**. I hit the wrong (generic) router everytime I use SearchQuerySet.

So I made a simple test in **SearchQuerySet._determine_backend**:
```python
print(connection_router)
```

And then I run this script:
```python
from haystack import connection_router
from haystack.query import SearchQuerySet
SearchQuerySet()
print(connection_router)
```

Which outputs:
```
<haystack.utils.loading.ConnectionRouter object at 0x7fd3c648b990>
<haystack.utils.loading.ConnectionRouter object at 0x7fd3c648b490>
```
So obviously connection_router is at two different addresses.

However there is a simple fix. Move ```from haystack import connection_router``` to  ```SearchQuerySet._determine_backend``` (make the import local) and the problem goes away.

**Comment by sampeka** [comment]
The PR I've referenced above will provide a short term quick fix, but Phil's proposed changes would be a lot better. I'll merge in the PR above when he resolves a minor issue but leave this issue to revisit later, is that alright with everyone?

**Comment by acdha** [comment]
@sampeka If that passes our tests, :+1: and let's document it in the release notes here. I doubt this is an especially common thing to rely on.

**Comment by skirsdeda** [comment]
Merging #1292 is the first step. But I think Phil's proposed changes are a bit overcomplicated. I would suggest  removing ```routers_list=None``` arg from **ConnectionRouter** and instantiating only one **ConnectionRouter** in **\__init\__.py** without accessing settings. Then in **ConnectionRouter** actual router settings would be accessed and routers constructed upon first ```for_action``` call only. This would definitely happen after all imports are done.

**Comment by skirsdeda** [comment]
My attempt at fixing this is now in #1296
