### ISSUE TITLE
__exact using elasticsearch doesn't work

### ISSUE THREAD

**Issue by timghague** [django-haystack/django-haystack#1045]
My search index looks like:

```
class MemberRolesIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    role_name = indexes.CharField(model_attr='role_name')

    def get_model(self):
        return MemberRoles
```

If I then do:

```
SearchQuerySet().models(MemberRoles).filter(role_name__exact='Director')
```

The search matches on role_name values:
- Director
- Assistant Director
- 1st Assistant Director

Should it not return results that match exactly 'Director'?

**Comment by JonnatasCabral** [comment]
Thanks so much , @phill-tornroth , I resolved it following your tips

**Comment by JonnatasCabral** [comment]
Thanks @joestump  and @phill-tornroth, I got resolve with your help.
