### ISSUE TITLE
readthedoc documentation is not up-to-date

### ISSUE THREAD

**Issue by fizyk** [django-haystack/django-haystack#1105]
latest version shows 2.1.1-dev ( http://django-haystack.readthedocs.org/en/latest/ ) while link pointing to 2.3.x docs ( http://django-haystack.readthedocs.org/en/v2.3.0/ ) shows maze found (404 error)

**Comment by foobacca** [comment]
It is still the case that the `<title>` tag of the docs on read the docs *still* says 2.1.1-dev even though other parts of the page clearly show that I'm looking at the 2.4.0 docs.  This appears to be set in docs/conf.py on line 53 (and line 51 also references 2.1.1) 

https://github.com/django-haystack/django-haystack/blob/master/docs/conf.py#L51

**Comment by foobacca** [comment]
Did a bit of searching around and here is a method for auto-setting the version in the docs from the version in setup.py

```
path = os.path.split(os.path.dirname(__file__))[0]
path = os.path.split(path)[0]
sys.path.insert(0, path)
import haystack

version = haystack.__version__
# The full version, including alpha/beta/rc tags.
release = haystack.__version__
```

from https://github.com/divio/django-cms/blob/develop/docs/conf.py#L57

**Comment by acdha** [comment]
Unfortunately, that approach is prone to hard-to-debug errors if anything triggers an import error and they tend to be missed by e.g. developers or CI systems which always do a full install before importing anything, which cannot be assumed will be consistently true for a widely used project.

This was a simple commit to bump the current version up but long-term I want to switch to something like one of the recommended schemes here:

https://packaging.python.org/en/latest/single_source_version/#single-sourcing-the-version

The approach I'm leaning towards is a bit of a hybrid, using the increasingly-popular approach of having an `__about__.py` file which contains all of the project metadata and, most important, has no import dependencies to avoid the hazards of loading `__init__.py`. See e.g. https://github.com/pyca/cryptography/blob/master/src/cryptography/__about__.py

**Comment by SalahAdDin** [comment]
Did you update it?

**Comment by SalahAdDin** [comment]
Updated final y?
