### ISSUE TITLE
Documentation about Woosh Python 3 support

### ISSUE THREAD

**Issue by gitaarik** [django-haystack/django-haystack#1108]
The current documentation says Woosh has partial Python 3 support because of an open issue, however, the link to the issue is dead:
http://django-haystack.readthedocs.org/en/latest/python3.html

Also the Woosh 2.0 release notes it says Python 3 is supported:
http://whoosh.readthedocs.org/en/latest/releases/2_0.html#improvements

Can we consider Woosh has Python 3 support and modify the documentation?

**Comment by acdha** [comment]
Good catch – if you have time to contribute a doc update, it'd be appreciated. Otherwise I'll try to fit it into 2.4.

**Comment by gitaarik** [comment]
So this issue the docs are referring to is no longer an issue?

**Comment by acdha** [comment]
@gitaarik I'm assuming so because the tests are passing on Python 3.3 & 3.4, but it might be worth a quick review to confirm that the whoosh highlighting test is indeed using the Whoosh highlighter:

https://travis-ci.org/django-haystack/django-haystack/jobs/53709852#L1350

**Comment by gitaarik** [comment]
https://github.com/django-haystack/django-haystack/blob/master/test_haystack/whoosh_tests/test_whoosh_backend.py#L262

I assume we can conclude it works. Also over here I see that highlighting is supported:
http://django-haystack.readthedocs.org/en/latest/backend_support.html#backend-support-matrix

I'll file a pull request

**Comment by acdha** [comment]
Great, thanks!

**Comment by gitaarik** [comment]
Here it is: https://github.com/django-haystack/django-haystack/pull/1154

**Comment by vqw** [comment]
"The following backends are fully supported under Python 3. However, you may need to update these dependencies if you have a pre-existing setup.

    Solr (pysolr>=3.1.0)
    Elasticsearch
"
Basically Whoosh is not supported or not "fully" supported?
