### ISSUE TITLE
Haystack is broken with Django 1.7 AppConfig

### ISSUE THREAD

**Issue by jsma** [django-haystack/django-haystack#1125]
The app autodiscover code is broken when using Django 1.7's AppConfig. The code attempts to ``importlib.import_module(app)`` [here](https://github.com/django-haystack/django-haystack/blob/be67c37e3d23eed96d675e0c56e85eb6de0d484b/haystack/utils/loading.py#L172-L182) but this fails if the user has 'myapp.apps.MyAppConfig' in INSTALLED_APPS. 

Django 1.7 converts all apps to AppConfig instances so the code should probably branch for 1.7 vs Django<1.7 and make use of the app registry for 1.7+. For now, I'll change my INSTALLED_APPS to use old-school 'project.app' notation so I can get on with my life but noticed [Django's admin](https://github.com/django/django/blob/master/django/utils/module_loading.py#L53) has a way of discovering admin.py files, perhaps this or something like this could be repurposed to do things the 'right' way with Django 1.7+.

**Comment by dcramer** [comment]
I just got notified about this, and it looks like the changes related to this will greatly break various apps.

https://github.com/django-haystack/django-haystack/blob/master/haystack/utils/app_loading.py#L14

Specifically, raven-python's app name is "raven.contrib.django.raven_compat", so the length checks here are super invalid.

**Comment by acdha** [comment]
#1153 is starting the process of refactoring to remove the older code which is now redundant in recent Django releases.

**Comment by acdha** [comment]
There's a release candidate on PyPI now:

pip install django-haystack==2.4.0rc1
