### ISSUE TITLE
Specifying a list fields for searching result

### ISSUE THREAD

**Issue by atugushev** [django-haystack/django-haystack#1127]
I just wondering is there a way to specify returned fields for search request to the backend elasticsearch. See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-fields.html for how to specify list in JSON API.

Let me explain why i need this. I have lots of articles with a large text data. Searching(more precisely, transferring a data) in this case is very slow, cause elasticsearch returns a whole large texts for each search results, but i want to render only titles except a whole text.

May be is there another way to do it? Thank you in advance.

**Comment by Madalosso** [comment]
Wouldn't be enough to split the string `search_kwargs['fields']` back to a list of field names?
