### ISSUE TITLE
Add Documentation for the New Generic Class Based View Added in PR #1130

### ISSUE THREAD

**Issue by troygrosfield** [django-haystack/django-haystack#1133]
The PR merged in #1130 added new django style class based views.  These need to be added to the doc so users know they exist.

**Comment by acdha** [comment]
I think this is one of the blockers for v2.4.0 since we have the actual code and tests ready to ship

**Comment by troygrosfield** [comment]
PR is out for the doc:

- https://github.com/toastdriven/django-haystack/pull/1139
