### ISSUE TITLE
`update_index` throws `ImproperlyConfigured ` if `raven` (`Sentry`) used

### ISSUE THREAD

**Issue by fedosov** [django-haystack/django-haystack#1150]
`raven` (https://github.com/getsentry/raven-python) requires including `raven.contrib.django.raven_compat` in `INSTALLED_APPS` which throws `ImproperlyConfigured` exception when someone tries to run `update_index` (https://github.com/django-haystack/django-haystack/blob/master/haystack/utils/app_loading.py#L26) because of comma count (>2) in the name of the app.

**Comment by acdha** [comment]
See #1153 for a proposed fix

**Comment by fedosov** [comment]
Thanks @acdha!
