### ISSUE TITLE
to index Postgresql specific field types

### ISSUE THREAD

**Issue by pajooh** [django-haystack/django-haystack#1157]
like ```ArrayField```, ```HStoreField```, as implemented in [django.contrib.postgres](https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/)
any experience on this?
e.g. how should indexing work for ArrayField

**Comment by acdha** [comment]
This would be a good question for the mailing list. You can specify multiple on a field and have a custom prepare method which unpacks the data as appropriate.
