### ISSUE TITLE
Link to the article.id

### ISSUE THREAD

**Issue by Huriddin** [django-haystack/django-haystack#1160]
hi, I have a little problem, when I use the haystack search and find my search result (it works), I can't click on the link and go to the article itself. 
heres some pictures:
![1](https://cloud.githubusercontent.com/assets/7415299/6917644/b5319326-d7a6-11e4-9338-8d73a0fe4637.jpg)
![2](https://cloud.githubusercontent.com/assets/7415299/6917649/b8ad2452-d7a6-11e4-98aa-fd07c0710324.jpg)
How can I resolve this?

**Comment by acdha** [comment]
This isn't a bug and would be better in the mailing list: https://groups.google.com/d/forum/django-haystack

The search result documentation shows that the field you want is `pk`, following Django's standard practice:

https://django-haystack.readthedocs.org/en/latest/searchresult_api.html#attribute-reference

https://docs.djangoproject.com/en/1.7/ref/models/instances/#the-pk-property
