### ISSUE TITLE
Django 1.8 - Removed in Django 1.9 warning

### ISSUE THREAD

**Issue by Koed00** [django-haystack/django-haystack#1162]
django.utils.importlib will be removed in Django 1.9
haystack/utils/__init__.py:12: ` from django.utils import importlib`

**Comment by acdha** [comment]
Once we officially drop support for Python 2.6 we can make this change

**Comment by acdha** [comment]
If you wanted to start a pull request, simply trying to import importlib directly and falling back to django.utils should work fine since we know all Django 1.9 users have to be using Python 2.7 or later.

**Comment by SalahAdDin** [comment]
I have the next warnings:
/home/tulipan/Proyectos/IspanyolHaber/lib/python3.4/site-packages/haystack/utils/loading.py:150: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  self.fields = SortedDict()

/home/tulipan/Proyectos/IspanyolHaber/lib/python3.4/site-packages/haystack/utils/loading.py:191: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  self.fields = SortedDict()

**Comment by acdha** [comment]
haystack.utils.importlib uses the stdlib importlib instead of django.utils.importlib
