### ISSUE TITLE
Facet_counts not working with whoosh backend

### ISSUE THREAD

**Issue by chriswedgwood** [django-haystack/django-haystack#1172]
I am not getting whoosh facet_counts to work with Haystack in my Django project Python==2.7.8 Whoosh==2.7 Haystack==2.3.1 I receive the error

"Warning: Whoosh does not handle faceting" when I run the following:

In [1]: from haystack.query import SearchQuerySet
In [2]: sqs = SearchQuerySet().facet('title')
In [3]: sqs.facet_counts() 

/Users/chriswedgwood/virtualenvs/omexchange/lib/python2.7/site-
packages/haystack/backends/init.py:35: Warning: Whoosh does not handle 
faceting. 

Out[3]: {}
in my search_indexes.py I have declared

title = indexes.CharField(model_attr='title',faceted=True)
I thought I would change my backend to elastic search and see what happens and i got results back In [1]: from haystack.query import SearchQuerySet In [2]: sqs = SearchQuerySet().facet('title') In [3]: sqs.facet_counts()

Out[3]: {u'dates': {}, u'fields': {'title': [(u'Event vlugkppylj', 2),
(u'Event jlomvcpidn', 2), (u'Event ryusgjejgg', 1), (u'Event pjetthkihw', 1),
(u'Event jdeestsxpb', 1), (u'Event hkmuyhnzjv', 1), (u'Event ewnxnvisdj', 1), 
(u'Chris event', 1)]}, u'queries': {}}
Im a bit confused with the combination of the Haystack documents and the whoosh documents Do I need to define a schema in order to get the faceting to function? Where should I do that? In search_indexes.py? Thanks Chris

**Comment by acdha** [comment]
Faceting currently isn't supported on Whoosh (see #815). I believe #914 is the furthest along & would be worth following or contributing to if this feature is important to you.
