### ISSUE TITLE
Highlighting Phrasal Searches

### ISSUE THREAD

**Issue by jimjkelly** [django-haystack/django-haystack#1181]
I was wondering if there was desire for extending the highlighting class to highlight phrasal searches - I note there's PR #466 with a simple stab at it (though that doesn't actually make any effort to ensure the search query is together).

I have a sub-classed version of the highlighter class in use in production, and would be happy to roll it into the Highlighter class itself and do a PR if there was interest in it.

**Comment by SteveByerly** [comment]
i'll be trying to incorporate the exact query highlighting soon in #1402
