### ISSUE TITLE
DATETIME_REGEX does not match DateField fields

### ISSUE THREAD

**Issue by mgaby25** [django-haystack/django-haystack#1188]
To reproduce this just use a ModelSearchIndex where the model has a field of type DateField.
You should get a similar error when you try to filter using SearchQuerySet:

SearchFieldError: Datetime provided to 'disappear_date' field doesn't appear to be a valid datetime string: '2013-01-03'

**Comment by ravigadila** [comment]
@acdha 
Same here,
`SearchFieldError: Date provided to 'date' field doesn't appear to be a valid date string: '2016-02-2`7'

Environment:
```
Python 2.7
Django 1.8
django-haystack 2.4.1
```

**Comment by mgaby25** [comment]
@ravigadila I created a patch for this see this snippet https://gist.github.com/mgaby25/d603cf828ec90899a160

**Comment by yeago** [comment]
in master i get errorDate provided to 'top_position_date' field doesn't appear to be a valid date string: '2016-04-09T00:30:13Z'

**Comment by saulshanabrook** [comment]
Yeah I am getting this as well:

```
SearchFieldError: Date provided to 'date_posted_search' field doesn't appear to be a valid date string: '2017-06-26T13:03:22.452Z'
```

**Comment by mgaby25** [comment]
@saulshanabrook Your string represents a datetime field, you should use a DateTimeField instead of DateField

**Comment by saulshanabrook** [comment]
@mgaby25 You are right, it works when I changed it. Thank you!
