### ISSUE TITLE
Schedule deprecation for Django 1.6 support

### ISSUE THREAD

**Issue by acdha** [django-haystack/django-haystack#1190]
A fair number of people in the community still use Django 1.6 but it's now two releases behind and officially unsupported by the Django project.

**Comment by Koed00** [comment]
I'll sign up for this one after the 2.4 releasee

**Comment by simonsmiley** [comment]
Since django 1.6 is not used by travis, I guess support was dropped

**Comment by acdha** [comment]
Closing this since we're now following the upstream Django support lifecycle

**Comment by nitely** [comment]
@acdha you forgot to close this one.

**Comment by acdha** [comment]
@nitely thanks!
