### ISSUE TITLE
ElasticSearch: Optimize by only returning IDs

### ISSUE THREAD

**Issue by cpury** [django-haystack/django-haystack#1203]
Before working with Haystack, I dealt with ElasticSearch directly. I used to set the returned fields to only the `_id`s since I would then get the complete objects from the DB anyway. Is there a way to do this in Haystack? Documents can be quite large, and so the response can be quite big for absolutely no reason. I'm sure other backends have similar options.

**Comment by acdha** [comment]
Yes - there are [`values()`](http://django-haystack.readthedocs.org/en/latest/searchqueryset_api.html#values) and [`values_list()`](http://django-haystack.readthedocs.org/en/latest/searchqueryset_api.html#values-list) SearchQuerySet methods which work just like their Django QuerySet counterparts. 

We use them for exactly this reason in e.g. the update_index management command:

https://github.com/django-haystack/django-haystack/blob/3c88d41f9a02299d031eef8114dfd4fdc5ed358f/haystack/management/commands/update_index.py#L242

**Comment by cpury** [comment]
Perfect, that's exactly what I need! Thanks!

**Comment by cpury** [comment]
@acdha can this be combined with slicing / pagination? As far as I understood, it gets the whole result set and puts it into a list.

**Comment by cpury** [comment]
Never mind, I'm getting a `KeyError: u'_source'` due to this issue: https://github.com/django-haystack/django-haystack/issues/1019

Will wait until it is fixed.

**Comment by acdha** [comment]
@cpury I just checked the commit logs – looks like we just need to ship a release with https://github.com/django-haystack/django-haystack/commit/3571bdead31728923e2739c0ed7212696f501994#diff-86da7062c02bc3ba1fe14dd640207b78. Have you tested against master?

**Comment by cpury** [comment]
@acdha yup, and it seems to work fine

**Comment by acdha** [comment]
@cpury Thanks for testing – I'm thinking about bumping #1093/#1141 to the next release so we can release 2.4.0 soon.
