### ISSUE TITLE
TemplateDoesNotExist at  /search/

### ISSUE THREAD

**Issue by alzearafat** [django-haystack/django-haystack#1205]
Hi,

I'm running Haystack backed by SimpleEngine.

I'm following your getting started tutorial and everything is doing fine, but when I attempt to search, I get a *TemplateDoesNotExist* exception for a template included in templates/search/search.html. 

```
TemplateDoesNotExist at /search/

search/search.html
```

```

Template-loader postmortem

Django tried loading these templates, in this order:

    Using loader django.template.loaders.filesystem.Loader:
    Using loader django.template.loaders.app_directories.Loader:
        /home/zea/Riset/Django-Project/HN-EZINE/lib/python2.7/site-packages/django/contrib/admin/templates/search/search.html (File does not exist)
        /home/zea/Riset/Django-Project/HN-EZINE/lib/python2.7/site-packages/django/contrib/auth/templates/search/search.html (File does not exist)
        /home/zea/Riset/Django-Project/HN-EZINE/hn/wsgi/myproject/ezine/templates/search/search.html (File exists)
        /home/zea/Riset/Django-Project/HN-EZINE/lib/python2.7/site-packages/haystack/templates/search/search.html (File exists)

```
I'm sure I already put the templates on the right place.

Any ideas?

Please excuse my English. Thanks in advance.

**Comment by acdha** [comment]
What version of Django are you using? I've heard of some people having problems migrating to the new syntax in 1.8. As an aside, Django 1.8 is not yet supported but I'm hoping to ship 2.4 fairly soon – if you are using 1.8 you might want to test with the current development version.

This line in the debug message seems quite odd – Haystack doesn't ship anything in templates/search/search.html so it's not immediately obvious why it says “File exists”:

```
        /home/zea/Riset/Django-Project/HN-EZINE/lib/python2.7/site-packages/haystack/templates/search/search.html (File exists)
```

n.b. which is not yet supported although I'm hoping to ship 2.4 very soon.
That's curious given that

**Comment by alzearafat** [comment]
Hi acdha,

Thank you for fast response. I'm using Django 1.8.2. 

Sorry... Actually, that's me who put the template there. I thought if I put it there, then haystack will find it. But it did not.

Thanks in advance  :)

**Comment by chhantyal** [comment]
@alzearafat put your template in `PROJET/templates/search/search.html`

**Comment by alzearafat** [comment]
@chhantyal Yes, I've done it. But still *TemplateDoesNotExist*. This is my projeject tree : 

```
(HN-EZINE)[zea@localhost myproject]$ tree
.
├── ezine
│   ├── admin.py
│   ├── __init__.py
│   ├── migrations
│   │   ├── 0001_initial.py
│   │   └── __init__.py
│   ├── models.py
│   ├── search_indexes.py
│   ├── static
│   │   ├── css
│   │   │   ├── hacker.css
│   │   │   └── rara.css
│   │   └── img
│   │       └── python-powered.png
│   ├── tests.py
│   ├── urls.py
│   ├── validators.py
│   └── views.py
├── manage.py
├── myproject
│   ├── e-zine
│   │   └── txt
│   │       └── 2015
│   │           └── 06
│   │               └── 04
│   │                   ├── tes_tHZ2JVS.txt
│   │                   └── tes.txt
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
└── templates
    ├── ezine
    │   ├── base.html
    │   ├── ezine_detail.html
    │   └── ezine_list.html
    └── search
        └── search.html
```

**Comment by SalahAdDin** [comment]
And your template_dirs settings?

**Comment by alzearafat** [comment]
@SalahAdDin I thought it's deprecated since version 1.8... (https://docs.djangoproject.com/en/1.8/ref/settings/#template-dirs)

But I tried something like this : 

```
TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,  'templates'),
)
```

But still not working... 

Thanks

**Comment by SalahAdDin** [comment]
And template finders?
 Man, have you an example to the new template configuration? I don't understand what is Django Template Backend.

**Comment by ChrisBraddock24** [comment]
FYI - I am having the same problem with Haystack not finding the template. Django should be going through and finding the template at search/search.html but is not for some reason.  Anyone find an answer since June?

**Comment by ChrisBraddock24** [comment]
@alzearafat not sure if you figured it out. You probably have since it has been awhile, but for future viewers. For me at least, the error was in the search.html file.  I had nested it appropriately under templates directory in the main project directory, but from the haystack set up docs it has {% extends 'base.html' %} in the search.html. However, for those going by the Django tutorial (and I think best practice), the base is generally nested under the app's name, so {% extends 'myapp/base.html' %}.  Once I added the myapp it loaded the page.

**Comment by DESHRAJ** [comment]
If the problem still persists, then you would be extending the non existing base file in your current template i.e search/search.html. Try correcting the path of base template or just remove the line for extending the base template and it will work for you very fine. Actually I was also facing the same problem and fixed it this way. 

Cheers

**Comment by acdha** [comment]
It sounds like nobody has encountered this as an issue in Haystack itself, so I'm going to close this issue. If someone wanted to send a pull request updating the docs to follow the modern Django tutorial recommendation, please feel free to do so.
