### ISSUE TITLE
add changelog so users know what has been changed for each version

### ISSUE THREAD

**Issue by gfairchild** [django-haystack/django-haystack#1213]
I don't see a changelog anywhere in the haystack project. I looked in the git repo as well as on the official website and readthedocs, but I don't see a changelog anywhere. It would be great to know what exactly changes between versions.

**Comment by acdha** [comment]
See https://github.com/django-haystack/django-haystack/releases

If you'd like to start maintaining more detailed release notes, contributions are always appreciated.

**Comment by gfairchild** [comment]
Oh, fantastic! It looks like I looked in the exact places this didn't exist. That's totally sufficient for me. Thanks!
