### ISSUE TITLE
Source code/documentation discrepency for default of "update_index --using" 

### ISSUE THREAD

**Issue by cbeland** [django-haystack/django-haystack#1215]
A co-worker of mine points out that:

http://django-haystack.readthedocs.org/en/v2.4.0/management_commands.html#update-index

says:

`--using`:
    If provided, determines which connection should be used. Default is
    `default`.

but the source code:

https://github.com/django-haystack/django-haystack/blob/609852661e5090d05ea04db9292ba109ce169027/haystack/management/commands/update_index.py#L153

appears to use all the connections from the settings.

**Comment by marcypetro** [comment]
It would seem:

Source code help text is correct: https://github.com/django-haystack/django-haystack/blob/609852661e5090d05ea04db9292ba109ce169027/haystack/management/commands/update_index.py#L126-L127

Need to update the documentation source code: https://github.com/django-haystack/django-haystack/blob/master/docs/management_commands.rst

**Comment by cbeland** [comment]
Thanks for the fix!
