### ISSUE TITLE
Repository description mentions outdated version

### ISSUE THREAD

**Issue by martey** [django-haystack/django-haystack#1217]
The description of the repository says that the current version is 2.3.1, but the most recent version seems to be [2.4.0](https://github.com/django-haystack/django-haystack/commit/ebf1a5c94a7e8af1329084cf0056de0014821723):

![screenshot from 2015-06-26 00-34-40](https://cloud.githubusercontent.com/assets/49076/8370793/24f10dbc-1b9b-11e5-9162-454476d14eef.png)

I think it would make the most sense to remove the version information from the repository description (so that core contributors do not have to worry about updating it when releasing new versions).

**Comment by acdha** [comment]
Good point, particularly since prior to the move to the django-haystack organization nobody else had access to change it. I've removed it.
