### ISSUE TITLE
FacetedSearchMixin errors on self.results property

### ISSUE THREAD

**Issue by dcloud** [django-haystack/django-haystack#1218]
Haystack 2.4.0

In https://github.com/django-haystack/django-haystack/blob/master/haystack/generic_views.py#L101:

```
context.update({'facets': self.results.facet_counts()})
```

There is no `results` property on FacetedSearchMixin. This looks like a copy/paste issue.

**Comment by acdha** [comment]
Yes – it was an oversight in the original pull request. See #1159.
