### ISSUE TITLE
Urllib3 1.11 breaks Elasticsearch

### ISSUE THREAD

**Issue by Koed00** [django-haystack/django-haystack#1231]
This is probably specific to Elasticsearch, but  upgrading to Urllib3 1.11 causes the following error:

```
elasticsearch.exceptions.ConnectionError:
ConnectionError(('Connection aborted.', ResponseNotReady())) caused by:
 ProtocolError(('Connection aborted.', ResponseNotReady()))
```

and occasionally:

```
ConnectionError('module' object has no attribute 'HTTPMessage') caused by:
 AttributeError('module' object has no attribute 'HTTPMessage')
```
raised by

``/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 124, in streaming_bulk``

Downgrading to urllib3 1.10 solves this.
I will have a look upstream as well.

**Comment by acdha** [comment]
Looks like this is already being tracked upstream: https://github.com/elastic/elasticsearch-py/issues/253

**Comment by Koed00** [comment]
Turns out having either `pies` or `future<=0.14.3` installed will break `urllib3==1.11`.
Upgrading to the latest `future==0.15.0` fixes this and they're working on a fix for `pies`.
