### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by basilelegal** [django-haystack/django-haystack#1238]
I'm having issues with circular import using haystack and [categories](http://django-categories.readthedocs.org/en/latest/index.html) and having a custom signal processor.

But I realised that if remove the statement  `from haystack import signals` from haystack `__init__.py` I don't have the circular import anymore. Signals isn't use in this file, is there a reason to keep it or can I patch it ?

**Comment by basilelegal** [comment]
Found another way to fix it.

**Comment by SalahAdDin** [comment]
Wich?

**Comment by basilelegal** [comment]
It's pretty long but it was Categories fault.  django Settings ->  haystack \_\_init__ -> MyCustomSignalProcessor -> my_models \_\_init__  -> Categories models in which there was `ugettext` instead of `ugettext_lazy`. `ugettext` needs Settings and you get your circular import, I have no idea why removing `from haystack import signals` was fixing the issue.

**Comment by SalahAdDin** [comment]
@acdha Doctor, some idea here?
