### ISSUE TITLE
Replace use of django.db.models.get_model with django.apps.apps.get_model

### ISSUE THREAD

**Issue by reidpr** [django-haystack/django-haystack#1246]
I am getting RemovedInDjango19Warning deprecation warnings, e.g.:

    /usr/local/lib/python3.4/site-packages/haystack/models.py:104: RemovedInDjango19Warning: django.db.models.get_model is deprecated.
      self._model = models.get_model(self.app_label, self.model_name)

which is caused by `models.py:SearchResult._get_model()`, line 104 (`get_model()` is deprecated):

````
    def _get_model(self):
        if self._model is None:
            try:
                self._model = models.get_model(self.app_label, self.model_name)
            except LookupError:
                # this changed in change 1.7 to throw an error instead of
                # returning None when the model isn't found. So catch the
                # lookup error and keep self._model == None.
                pass

        return self._model
````

Also:

    /usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
      return f(*args, **kwds)

caused by `utils/app_loading.py` importing `django.db.models.loading`; that entire module is deprecated.

There is a pull request #1137 on this topic. However, that will not solve the problem in this case because it relies on the functions in question being entirely absent instead of deprecated. That is, the deprecated stuff will still be used and the warnings still generated.

Versions:

* django-haystack 2.4.0
* OS X 10.10.5
* Python 3.4.3 via Homebrew
* Django 1.8.4
* elasticsearch 1.6.0

**Comment by SalahAdDin** [comment]
:+1:

**Comment by mathewbyrnejbi** [comment]
Now on Django 1.9 this causes a fairly obscure error for me.  Switching to using `django.apps.apps.get_model` has solved the issue for me.

**Comment by gvankeerberghen** [comment]
@mathewbyrnejbi I've got same obscure error it seems. Getting 

AttributeError at /search/
'module' object has no attribute 'get_model'

Could you detail what you changed where, did you change from using `django.db.models.get_model` to `django.apps.apps.get_model` both in 
- `models.py:SearchResult._get_model()`
- `forms.py:ModelsSearchForm.get_models()`? 

Anywhere else?

Versions 
- Django 1.9
- Haystack 2.4.1

**Comment by mathewbyrnejbi** [comment]
@gvankeerberghen For me, updating `haystack.models.SearchResults._get_model` was enough to solve my issue.  I ended up extending the base model and inserting the new class into searches using `haystack.query.SearchQuerySet.result_class()` rather than change this package, but hopefully this can be removed with an upcoming release.

**Comment by jheld** [comment]
+1. Took me a little while (started working on a project today) to realize this was not a configuration or code issue I had made. I'm glad I checked. I may have to keep at django 1.8 until this is fixed; I was on 1.9.

**Comment by acdha** [comment]
Sorry about the delays but as of 10bcc7668ccaab499f8db516fd59de182aadbcb4 the tests are passing on Django 1.9.

**Comment by reidpr** [comment]
That's great news, thank you!

**Comment by acdha** [comment]
@reidpr Thank @claudep for stepping up and wrangling all of the partial patches into a nice clean set of commits. I mostly updated the changelog :grinning:
