### ISSUE TITLE
haystack + solr 5.3 rebuild_index gives wrong url

### ISSUE THREAD

**Issue by xuezhaokun** [django-haystack/django-haystack#1249]
I create a core in solr 5.3 using haystack for my django application and try to do `python manage.py rebuild_index`, it just gives this error message. The part `/update/?commit=true` looks strange for me. I try to manually change it to `/update?commit=true`, but still does not work. In browser, it just says 404. Anyone has any idea on it? Thanks!

> Failed to clear Solr index: Failed to connect to server at
> 'http://localhost:8983/solr/#/my_core/update/?commit=true', are you
> sure that URL is correct? Checking it in a browser might help:
> HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded
> with url: /solr/ (Caused by <class 'socket.error'>: [Errno 111]
> Connection refused)

**Comment by acdha** [comment]
If you're getting connection refused errors, Solr is either not running or is running on a different port than Haystack is using. Additionally, `http://localhost:8983/solr/#/my_core/update/` suggests that your Solr URL has a stray `#` on the end
