### ISSUE TITLE
Fix imports for elasticsearch 1.8+

### ISSUE THREAD

**Issue by mrmachine** [django-haystack/django-haystack#1253]
`elasticsearch.helpers.bulk_index` was removed In this commit:

https://github.com/elastic/elasticsearch-py/commit/5d4640d4c2cfd52aa92121fe41bbb383945cf6d3

**Comment by chocobn69** [comment]
indeed, need to change import

**Comment by stephenpaulger** [comment]
This manifests as

    MissingDependency: The 'elasticsearch' backend requires the installation of 'elasticsearch'. Please refer to the documentation.

If you have elasticsearch 1.8.0 or 2.0.0 installed. You can downgrade to elasticsearch==1.7.0 as a workaround.

**Comment by chocobn69** [comment]
I just did a small patch as a workaround too

**Comment by mmautner** [comment]
Like-wise, had to pin to 1.7.0

**Comment by acdha** [comment]
Sounds like we need to have a point release for haystack soon

**Comment by jleclanche** [comment]
Any chance for a release?

**Comment by acdha** [comment]
@jleclanche The code in this issue was released in v2.4.1 on October 29th. If you're looking for something else, we are due for another release and could use help testing if you have time.

**Comment by jleclanche** [comment]
@acdha how come 2.4.1 isnt tagged?

**Comment by acdha** [comment]
See https://github.com/django-haystack/django-haystack/releases/tag/v2.4.1 and https://pypi.python.org/pypi/django-haystack/2.4.1

**Comment by jleclanche** [comment]
Ah I see. I didn't find it because it wasn't in the releases. It needs a description to appear there.

**Comment by acdha** [comment]
@jleclanche PyPI is the system of record for releases. GitHub may improve their UI at some point but I'd always look at PyPI since that's where most installs will actually originate from.
