### ISSUE TITLE
Import failure for elasticsearch backend

### ISSUE THREAD

**Issue by abhikalakuntla** [django-haystack/django-haystack#1262]
Hello,

I'm trying to use elasticsearch as my backend service for django-haystack and an import error comes from https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L33.

However, when I go into `python manage.py shell_plus`, I'm able to `import elasticsearch` and `from elasticsearch.helpers import bulk`. I have included 'elasticsearch' and 'haystack' in my settings.py file. 

I am using django-haystack version 2.4.0 and elasticsearch version 2.1.0. 

Has this been happening to anyone else?

![from shell_plus console interaction](https://cloud.githubusercontent.com/assets/3415226/10719857/dabe56d8-7b4d-11e5-883f-0d4c7a1b2b7c.png)

![rebuilding index](https://cloud.githubusercontent.com/assets/3415226/10719831/4d8ffcc6-7b4d-11e5-81a7-df9e142754a5.png)

**Comment by AdrianRibao** [comment]
It happens to me too

**Comment by acdha** [comment]
Are you using 2.4.0 or the latest master branch? The elasticsearch client API changed with 2.x and we do not yet have a release which supports it, although I think @bigjust was getting ready for a haystack point release to address that.

**Comment by theiviaxx** [comment]
same, fails trying to import

    from elasticsearch.helpers import bulk_index

**Comment by acdha** [comment]
@theiviaxx Are you sure you've completely uninstalled the old version of haystack? With ElasticSearch 1.7, 1.9 and 2.1 the current master branch works.

If you've been using the same install for awhile it's possible that you have to uninstall multiple versions (this is a fairly common source bug reports):

```bash
while pip uninstall -y elasticsearch; do true; done
```

**Comment by theiviaxx** [comment]
using django-haystack master resolved it

**Comment by jsma** [comment]
Can confirm this happened with a clean virtualenv using Django 1.7.10, django-haystack 2.4.0 and elasticsearch 1.8.0, all installed via pip from pypi.

**Comment by jsma** [comment]
The issue appears to have been fixed in https://github.com/django-haystack/django-haystack/commit/a86d1e3b9117a8794635304f093d25ed064100d8

**Comment by acdha** [comment]
@jsma How extensive was your testing? I'm getting ready to ship 2.4.1 but would welcome feedback from anyone who's tested it with a serious app

**Comment by acdha** [comment]
v2.4.1 is out now: https://pypi.python.org/pypi/django-haystack/2.4.1
