### ISSUE TITLE
maganing attachments for elasticsearch

### ISSUE THREAD

**Issue by frague59** [django-haystack/django-haystack#1264]
Hi, 

I'm trying to use haystack + elasticsearch to populate an index with documents, aka files, using the mapper-attachments elasticsearch plugin.

My files are uploaded to the index as base64 streams, I've built a SearchField that provides this functionnality. My files are visible as a string in the elasticsearch index, it has been uploaded.

My question is : How can I bind the field type 'attachment' into the mappings ? 
As I saw in the haystack code, it uses a hard coded set of rules, and does not provide this kind of mappings. In elasticstack, `show_mapping --detail` uses the same mapping stuff, so I'm stuck.

Have you any idea on how to provide this functionality ? Thanks !

**Comment by acdha** [comment]
This sounds like a good question for the group:

https://groups.google.com/forum/#!forum/django-haystack
