### ISSUE TITLE
Elasticsearch Shield (Security for Elasticsearch)

### ISSUE THREAD

**Issue by Alir3z4** [django-haystack/django-haystack#1266]
Does haystack configuration supports such auth method ?

* https://www.elastic.co/products/shield

**Comment by cstrap** [comment]
It should work with a base authentication.
In your django settings put something like:
```
HAYSTACK_CONNECTIONS['default']['KWARGS'] = {
    'port': 9200,
    'http_auth': ('es_admin', 'password'),
    'use_ssl': False
}
```

**Comment by sampeka** [comment]
@Alir3z4 I'm going to assume that the solution above worked out, but if you still have a problem please feel free to raise another issue
