### ISSUE TITLE
Elasticsearch engine not working on Django 1.9b1 

### ISSUE THREAD

**Issue by tarvitz** [django-haystack/django-haystack#1267]
Standard (tutorial) work-around with elasticsearch engine selected does not work on django-1.9b1 though 1.8.6 works well.

Still have some `removed in django-1.9b1` parts such as models.get_model (haystack.forms:111)

**Comment by acdha** [comment]
Django 1.9 is not supported yet. Please open a pull request with any code
changes you've made which are not already in the existing pull requests.

**Comment by mariocesar** [comment]
@tarvitz I made a fix in this PR #1276

**Comment by tarvitz** [comment]
@mariocesar, thanks I'll try to test my workaround with this pr a litte bit later.
