### ISSUE TITLE
Retrieve list of spelling suggestions from the search backend

### ISSUE THREAD

**Issue by johnthedebs** [django-haystack/django-haystack#127]
It would be nice if Haystack could get a list of suggestions from the search backend for things like Search Suggestions or those who are curious. You mentioned in the Haystack group on Google that it's possible with Solr, but that you'd have to look into this for the other backends.

http://groups.google.com/group/django-haystack/browse_thread/thread/6886b209335ae9fa

**Comment by sampeka** [comment]
It's been a long time since this issue was last progressed and there is no clear path to moving it forward. I'm going to close this for now but please feel free to raise a new one.
