### ISSUE TITLE
django haystack error ImportError: The Python module 'xapian_backend' has no 'XapianEngine' class

### ISSUE THREAD

**Issue by TheDrifter254** [django-haystack/django-haystack#1271]
I have haystack version 2.0.0 installed and it throws this error in the logs. This happened when I upgraded all the apps for django.

**Comment by sampeka** [comment]
Are you still experiencing this problem? If so - could you try upgrading haystack to 2.4?

**Comment by skirsdeda** [comment]
Xapian backend lives in external project as noted in docs. So this issue is irrelevant.
