### ISSUE TITLE
field "pk_xapian" not indexed

### ISSUE THREAD

**Issue by Six-wars** [django-haystack/django-haystack#1275]
I can't use update_index without specifying the app name because it throws TypeError: index_queryset() got an unexpected keyword argument 'using' even after I included using in all the search_indexes so I've updated the index for all the app but for a rest api view that has this line 

sqs = SearchQuerySet().filter(django_ct='directory.venue', pk_xapian__in=venue_ids).order_by('name')

not sure if it's deprecated and causing the issue or the index hasn't been built properly.

**Comment by sampeka** [comment]
Hi @Six-wars , are you still experiencing this problem? If so, what version of haystack are you using? Could you also paste the contents of the search index that is throwing the error?

**Comment by Six-wars** [comment]
Hi @sampeka I had to remove all instances of using to remove the bug, thanks though for the reply.
