### ISSUE TITLE
testsuite absent

### ISSUE THREAD

**Issue by idella** [django-haystack/django-haystack#1280]
This is the content of the tarball of django-haystack-2.4.0 from pypi.

```bash
AUTHORS  LICENSE  MANIFEST.in  PKG-INFO  README.rst  django_haystack.egg-info  docs  haystack  setup.cfg  setup.py
```

The testsuite resides in the folder test_haystack and is not included in the MANIFEST.in

**Comment by sampeka** [comment]
Is there be any benefit to including test_haystack with the pypi distribution? The only real use case for running tests would be if people are contributing toward the project, in which case you'll get them from cloning the repo. Or do you have some other requirement?

I'm adding a wontfix to this, but please feel free to disagree and I'll remove it :)
