### ISSUE TITLE
ImproperlyConfigured: The default alias 'default' must be included in the HAYSTACK_CONNECTIONS setting

### ISSUE THREAD

**Issue by Lamicc** [django-haystack/django-haystack#1283]
Hey guys, i got this issue when running haystack 

File "/edx/app/edx_notes_api/venvs/edx_notes_api/local/lib/python2.7/site-packages/haystack/__init__.py", line 41, in <module>
    raise ImproperlyConfigured("The default alias '%s' must be included in the HAYSTACK_CONNECTIONS setting." % DEFAULT_ALIAS)
ImproperlyConfigured: The default alias 'default' must be included in the HAYSTACK_CONNECTIONS setting.

The configuration is like this

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'notesserver.highlight.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'notes_index',
    },
}

Did I miss anything?

**Comment by bigjust** [comment]
Are you sure that configuration is being loaded?

**Comment by Lamicc** [comment]
Is there any way to check if the configuration is loaded?
sorry if this is a silly question.

**Comment by skirsdeda** [comment]
@Lamicc Good way to check this would be to run ```python manage.py shell``` in your project's root directory. Then just write this:
```python
from django.conf import settings
settings.HAYSTACK_CONNECTIONS
```

It should output the same HAYSTACK_CONNECTIONS as you have configured.

**Comment by skirsdeda** [comment]
Assuming this was a misconfiguration related thing and closing off.
