### ISSUE TITLE
Autocomplete Example Returns No Results

### ISSUE THREAD

**Issue by mrigdon** [django-haystack/django-haystack#1284]
Hi, I integrated the exact example provided by the autocomplete docs, and it's not working for me. As far as I know, the given example is supposed to return any Indexed SearchIndex based on text you type correct?

**Comment by sampeka** [comment]
Which backend are you using?

**Comment by sampeka** [comment]
Going to close this issue since it's been over a month, but raise a new one with some example code if you're still experiencing a problem
