### ISSUE TITLE
Typo in docs, in section about upgrading to GCBV's

### ISSUE THREAD

**Issue by discopatrick** [django-haystack/django-haystack#1290]
https://github.com/django-haystack/django-haystack/blob/v2.4.1/docs/views_and_forms.rst#upgrading

Step 3 currently reads:

> Review your templates and replace the ``page`` variable with ``page_object``

However, the variable name is: ``page_obj``

**Comment by sampeka** [comment]
Good catch, feel free to submit a PR - I'll merge it in :+1:

**Comment by sampeka** [comment]
Looks like this has already been fixed for next release
