### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by mskrzypek** [django-haystack/django-haystack#1293]
There is a warning in Django 1.9:

    [...]/haystack/fields.py:137: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
    return t.render(Context({'object': obj}))

Just remove "Context()" and it should be ok.

**Comment by acdha** [comment]
That fix would break compatibility with older versions of Django. If you want to work on a pull request, please update the documentation to drop support for versions of Django older than 1.8, which is reasonable since the Django project dropped support for 1.7 last month.

**Comment by acdha** [comment]
This should be resolved as of 69bb1db279546137b8b03abefecd13fa214d48fe
