### ISSUE TITLE
 foo_field__in lockup bugs. 

### ISSUE THREAD

**Issue by ubombi** [django-haystack/django-haystack#1294]
s = ['keyword', 'search phrase', 'synonym']  # simple array

**This code return nothing**  Returns empty array

     SearchQuerySet().models(Expert).filter(foo__in=s)

**This works, why?** Returns normal result, as for searching 1st element

    SearchQuerySet().models(Expert).filter(foo__in=s[0])
    #EQUALS
    SearchQuerySet().models(Expert).filter(foo=s[0])

**Comment by ubombi** [comment]
Its MultiValueField (same with FacetMultiValueField).

**Comment by sampeka** [comment]
What backend are you using?

**Comment by ubombi** [comment]
Sorry, I use elasticsearch 2.X which is not supported.
(fails on index shcema create, because of deprecated __boost )
