### ISSUE TITLE
Python2.7 ssl error with urllib3 installed

### ISSUE THREAD

**Issue by the-kid89** [django-haystack/django-haystack#1299]
I was on the django irc today and assisted a user with getting his script working again after he installed django-haystack. The issue was with the requirement of urllib3 not bringing SSL with it when installing. I propose the change from urllib3 to urllib3[secure] as this fixes the issue.

**Comment by sampeka** [comment]
Could you provide some more details of what the exact problem was, and what you're proposing to fix it?

**Comment by acdha** [comment]
@the-kid89: haystack doesn't directly depend on urllib3. Was that perhaps due to `elasticsearch` or `pysolr` depending on `urllib3`? If so, that could be solved with e.g. a requirements file specifying `requests[secure]` which also pulls in `urllib3[secure]`

**Comment by the-kid89** [comment]
@acdha Yes it was elasticsearch that he was using and the proposed solution would fix the problem. Though note that the issue was not directly with django-haystack it was that installing django-haystack changed the functionality of a different library the user was using. This caused the other library to throw errors and stop functioning. The fix being install urllib3[secure]. I have also reported the issue to the other library in question.

**Comment by the-kid89** [comment]
I also did preform a test from a fresh Ubuntu server and was able to replicate the issue with haystack installing urllib3 from pip. It then did provide a warning that I could run into the issue from this report.

**Comment by acdha** [comment]
@the-kid89 What's the exact command you're using to install haystack? It doesn't pull in either urllib3 or elasticsearch (the only core dependency is Django) so I think the problem is one of the other dependencies.

**Comment by SteveByerly** [comment]
@the-kid89 if you are able to provide details on how to produce, please reopen this issue.
