### ISSUE TITLE
Change log for 2.4.1 not available

### ISSUE THREAD

**Issue by tysonclugg** [django-haystack/django-haystack#1310]
The list of releases at https://github.com/django-haystack/django-haystack/releases does not include version 2.4.1 which is the latest version available from PyPi.  There is however a tag for v2.4.1 at https://github.com/django-haystack/django-haystack/releases/tag/v2.4.1 but it doesn't have any changes listed.

I know it's nice that GitHub provides a place for you to put changes in the release details, but if you're not being consistent in using that feature I'd prefer you go back to maintaining a CHANGELOG.rst (or CHANGELOG.md) instead.  As an added bonus of using a change log file, any *missing* or *incorrect* change entries can be resolved in future releases.

**Comment by acdha** [comment]
If you're interested in the changes, you can use the links on the release page to view the commits:

https://github.com/django-haystack/django-haystack/compare/v2.4.0...v2.4.1

This project has never had a changelog before but we're always looking for volunteers if you'd like to help create one, particularly if we started using a tool to generate the updates from the commit logs so it doesn't drift out of sync.
