### ISSUE TITLE
"Searchqueryset" fails to filter using the reserved field "django_ct"

### ISSUE THREAD

**Issue by alexsilva** [django-haystack/django-haystack#1316]
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
I need to be able to filter by content type(django_ct).
```
>>> s = SearchQuerySet()
>>> print s
# result: [<SearchResult: model.indexA (pk=1)>, <SearchResult: model.indexB (pk=1)>]
>>> resultA = s.filter(django_ct=u"model.indexA")
>>> print resultA.count() # 1
>>> print resultA
# result (only indexA): [<SearchResult: model.indexA (pk=1)>]
>>> resultB = s.filter(django_ct=u"model.indexB")
>>> print resultB.count() # 1
>>> print resultB
# result (only indexB): [<SearchResult: model.indexB (pk=1)>]
```
## Actual behaviour
However haystack failure to apply the filter and returns an empty list
```
>>> s = SearchQuerySet()
>>> print s.filter(django_ct=u"model.indexA")
# empty result: []
```

## Steps to reproduce the behaviour

1. Filter `searchqueryset` using the reserved field `django_ct`

[Case like this has been reported here](http://stackoverflow.com/questions/33954463/django-ct-filter-for-django-haystack-not-returning-results)

## Configuration

* Operating system version: Windows 10 x64
* Search engine version: xapian v1.2.22
* Python version: 2.7 32 bits
* Django version: 1.7.11
* Haystack version: 2.4.1

**Comment by skirsdeda** [comment]
Use ```SearchQuerySet.models``` instead which does exactly that.

**Comment by alexsilva** [comment]
I need to count the number of results by `content_type`, so I tried to apply this filter.

**Comment by acdha** [comment]
I'm assuming `narrow('django_ct:foo.bar')` also does not work? In a quick test using my Solr-backed app, `.filter(django_ct='core.itemtranslation').count()` and `.narrow('django_ct:core.file').count()` behave identically and are definitely applying the filters.

I'm having trouble reproducing this and noticed that you're using Xapian, which isn't part of the core haystack project – do you know if `xapian-haystack` either uses a different field name than the literal `django_ct` (this is infrequently done but possible to change) or perhaps is overriding your `django_ct` with a default?

**Comment by alexsilva** [comment]
It works! Just do not yet know why, but I solve my problem

```
s = SearchQueryset()
s.narrow('django_ct:model.index1')
s.narrow('django_ct:model.index2')
```

**Comment by alexsilva** [comment]
It is the administrator's discretion to accept this as a bug or not. `narrow` solved the problem.
