### ISSUE TITLE
Haystack not returning the object properly

### ISSUE THREAD

**Issue by idesignedme** [django-haystack/django-haystack#1333]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Steps to reproduce the behaviour

1.

## Configuration

* Operating system version:
* Search engine version:
* Python version:
* Django version:
* Haystack version:

**Comment by idesignedme** [comment]
class PostIndex(indexes.SearchIndex, indexes.Indexable):
  text = indexes.CharField(document=True, use_template=True)
  publish = indexes.DateTimeField(model_attr='publish')

  def get_model(self):
      return Post

  def index_queryset(self, using=None):
      """Used when the entire index for model is updated."""
      return self.get_model().objects.all()
in templates I create

search/indexes/blog/post_text.txt
and add this to it

{{ object.title }}
{{ object.tags.all|join:", " }}
{{ object.body }}
in my views.py i add

from haystack.query import SearchQuerySet
then in a view function

def post_search(request):

  form = request.GET.get('q')
  results = SearchQuerySet().models(Post).filter(content=form)
  # count total results
  total_results = results.count()
  template = 'blog/post/search.html',
  context = {
      'form': form,
      'results': results,
      'total_results': total_results

  }
  return render(request, template, context)
and in a search template

{% for result in results %}
  <p>{{result.publish}}</p>

  <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
but the only thing that gets returned is the publish. If I inspect the a element the href is blank. if I do this

{{results}}
I get something like this

[blog.post.pk(2)] or something like that
these will not work

 {{result.object.publish}}<br>
but this will {{result.publish}}

and to access these

 {{result.object.body}}<br>
 {{result.object.title}}<br>
 {{result.object.slug}}<br>
I go back and add this

 class PostIndex(indexes.SearchIndex, indexes.Indexable):
  text = indexes.CharField(document=True, use_template=True)
  publish = indexes.DateTimeField(model_attr='publish')

  # added this
  title = indexes.CharField(model_attr='title')
  body = indexes.CharField(model_attr='body')
  slug = indexes.CharField(model_attr='slug')

  def get_model(self):
      return Post

  def index_queryset(self, using=None):
      """Used when the entire index for model is updated."""
      return self.get_model().objects.all()
which is nothing like the the tutorials say What am I doing wrong?

I get my results buy doing this

result.title
not

result.object.title
and from the tutorials I watch and read all they do is this

 class PostIndex(indexes.SearchIndex, indexes.Indexable):
  text = indexes.CharField(document=True, use_template=True)
  publish = indexes.DateTimeField(model_attr='publish')

  def get_model(self):
      return Post

  def index_queryset(self, using=None):
      """Used when the entire index for model is updated."""
      return self.get_model().objects.all()
but can access everything like this

result.object.title
result.object.publish
result.object.get_absolute_url
they are obviously accessing the whole object but for some reason I am not. any guidance or a suggestion to something that I could possibly see like a video would be appreciated. I really don't get why I'm not accessing the whole object.

Edit :

my models.py

class Post(models.Model):

STATUS_CHOICES = (
   ('draft', 'Draft'),
   ('published', 'Published'),
)
title = models.CharField(max_length=250)
slug = models.SlugField(max_length=250,
                        unique_for_date='publish')
image = models.ImageField(null=True, blank=True)
author = models.ForeignKey(User,
                           related_name='blog_posts')
body = models.TextField()
publish = models.DateTimeField(default=timezone.now)
created = models.DateTimeField(auto_now_add=True)
updated = models.DateTimeField(auto_now=True)
status = models.CharField(max_length=10,
                          choices=STATUS_CHOICES,
                          default='draft')
video = models.BooleanField(default=False)
video_path = models.CharField(max_length=320,
                              null=True,
                              blank=True,)

class Meta:
    ordering = ('-publish',)

def __str__(self):
    return self.title

def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

objects = models.Manager() # The default manager.
published = PublishedManager() # Our custom manager.
tags = TaggableManager()
I'm using

Django==1.9.4
django-crispy-forms==1.6.0
django-haystack==2.4.1
django-taggit==0.18.0
Pillow==3.1.1
pysolr==3.4.0
pytz==2016.1
requests==2.9.1
python 3.5
Ive updated and rebuilt my schema and I followed Mike Hibbert and read a book called django by example follwed them verbatim and still cant figure it out. Is this some kinf=d of bug?

**Comment by ahoho** [comment]
Haystack does not support Django 1.9. Before trying anything else, you should downgrade to 1.8.

I think your intuition behind how things should work is correct -- you should be able to run `result.object` to retrieve your `Post` objects.

The key insight regarding Haystack vis-a-vis Django is that, in many use cases, the `SearchIndex` (your `PostIndex`) is effectively a mirror for your model (`Post`). Your fields in the index generally correspond to fields (or a subset of fields) in the model. You seem to have grasped this, but I just thought I'd make it explicit.

Several other concepts follow this index-model analogy: a `SearchQuerySet` (Haystack) corresponds to a `QuerySet` (Django), the former contains `SearchResult` objects and the latter your `Post` model objects. `SearchResult` objects have the `object` attribute, which is a pointer to the related `Post` object. 

So yes, you should just be able to index what you want to in `PostIndex`, and run `{{result.object.model_field_name}}` in your template. I can't see anything wrong with your code (although I've only glanced through it), so I do suspect it's due to a 1.9 incompatibility.
