### ISSUE TITLE
Necessity for explicitly setting the search_index file path

### ISSUE THREAD

**Issue by fleischie** [django-haystack/django-haystack#1342]
The documentation states, that it isn't required to put the `search_index.py` file into the app it belongs to (though this is the default behaviour). For example a global `search_index.py`, that contains all indexes for all currently managed apps could go into a separate directory in the project root.

Going through the code this seems not to be as simple as it is stated: `utils/loading.py`
```python
try:
    search_index_module = importlib.import_module("%s.search_indexes" % app_mod.__name__)
except ImportError:
    ...
```

with `app_mod` being a list of apps for this specific django project.

I would propose to implement a more modular search_index setting feature:

* Add a specific setting attribute `HAYSTACK_SEARCH_INDEX_PATH` or something more/less verbose.
* See, whether this attribute is set and try to import from there.
* If not set or set path/paths do not exist, fall back to default behaviour. (Which would make this feature backwards-compatible.

The reason for posting this issue is I would like to have some feedback, before implementing this kind of feature. I don't want to implement something that's unnecessary or wrongly thought through or don't comply the contribution codex. If this behaviour/feature is requested/required/necessary/wanted, I would gladly begin working on it. :)

**Comment by SteveByerly** [comment]
I agree with this. I prefer to have one file for my indexes, but have just been putting it in the main app of my project.

Do you want to submit a PR? If you do, please make sure you add tests and documentation.

**Comment by fleischie** [comment]
I'll try to work on a PR this week. I'll keep you updated on this. :smile:

**Comment by acdha** [comment]
@fleischie Thanks! Since this is a new feature, I think we can roll it into a release once the code is ready.

**Comment by fleischie** [comment]
Haha, I skipped work today to work on it. :grinning: 

See PR #1407.

**Comment by SteveByerly** [comment]
Thanks @fleischie i'll try to take a look at it tonight or tomorrow. I'll close this issue in favor of the PR.
