### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_model'

### ISSUE THREAD

**Issue by savalou** [django-haystack/django-haystack#1350]
* [ x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behavior
No error.
## Actual behavior
I get an error.
## Steps to reproduce the behaviour

1.
I created a very simple project using the example from Haystack. However, when I try to do a search, I get an exception. 

Environment:

Request Method: GET
Request URL: http://localhost:8000/search/?q=lassie&models=dog.dog

Django Version: 1.9.4
Python Version: 2.7.10
Installed Applications:
```
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'haystack',
 'dog']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
```

```
Traceback:

File "/Users/lebouuski/projects/django/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/Users/lebouuski/projects/django/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/lebouuski/projects/django/lib/python2.7/site-packages/haystack/views.py" in __call__
  51.         self.results = self.get_results()

File "/Users/lebouuski/projects/django/lib/python2.7/site-packages/haystack/views.py" in get_results
  91.         return self.form.search()

File "/Users/lebouuski/projects/django/lib/python2.7/site-packages/haystack/forms.py" in search
  116.         return sqs.models(*self.get_models())

File "/Users/lebouuski/projects/django/lib/python2.7/site-packages/haystack/forms.py" in get_models
  110.                 search_models.append(models.get_model(*model.split('.')))

Exception Type: AttributeError at /search/
Exception Value: 'module' object has no attribute 'get_model'
```

**Comment by savalou** [comment]
@acdha Seems to be an issue in haystack/forms.py

**Comment by claudep** [comment]
This should be fixed in master (f1ed1831377).

**Comment by savalou** [comment]
Thanks for the reply! So how do I get this fix? I used pip, should I download the Zip file from the git page and install it manually?

Sushil

**Comment by claudep** [comment]
Hopefully a new django-haystack release should be available soon.

**Comment by acdha** [comment]
@savalou pip install django-haystack and install the zip/tar file from the GitHub page. If that works for you, please feel update this with results. I haven't shipped a release yet because I haven't had time to give it enough testing.

**Comment by savalou** [comment]
@acdha Getting the code from the master zip file resolved that issue. I had to do a few other things to get the example cat and dog apps working. Do you want the full project code?

**Comment by SteveByerly** [comment]
Seems like the updated code fixed the problem.
