### ISSUE TITLE
Django admin search - implementation issues

### ISSUE THREAD

**Issue by geekashu** [django-haystack/django-haystack#1373]
Hi,

I am trying to implement haystack admin search but not able to do so. I have following code to register LocationAdmin in AdminSite.

```
from django.utils.translation import ugettext_lazy as _
from haystack.admin import SearchModelAdmin
from users.models import Location

class LocationAdmin(SearchModelAdmin):
    list_display = ('city', 'state', 'country',)
    ordering = ('state',)

admin.site.register(Location, LocationAdmin)
```

Now i have a default haystack connection which points to my elastic search install and it works nicely. 
My search_indexes.py file is as follows.
```
from haystack import indexes
from users.models import Location
class LocationIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    state = indexes.CharField(model_attr='state')

    autocomplete_city = indexes.EdgeNgramField(model_attr='city')

    def get_model(self):
        return Location

    def index_queryset(self, using=None):
        return self.get_model().objects.all()
```

Now what else i need to do so that search box should start displaying in AdminSite when Location page is opened. 

If i define `search_fields = ('city',)` search box is displayed but no matter what i search for, results are always none.

I am using latest master dev version of django-haystack in django 1.9

Edit: Also the search results i am getting doesn't have check-boxes with the help of which we perform action on bulk items.

**Comment by geekashu** [comment]
Anyone? Please point me in correct direction.

**Comment by acdha** [comment]
I would suggest trying the discussion group and reviewing the source code. This likely needs a substantial update since the admin has become much easier to extend, so feel free to submit a pull request.
