### ISSUE TITLE
Error when removing stale records - AttributeError: Nonetype object has no attribute '_meta'

### ISSUE THREAD

**Issue by anuragjain** [django-haystack/django-haystack#1380]
* [x] Tested with the latest Haystack release

## Expected behavior
Objects should get removed from index

## Actual behavior
Getting AttributeError: Nonetype object has no attribute '_meta'
```
  removing 1 stale records.
ERROR Error updating analytics using default 
Traceback (most recent call last):
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 289, in update_backend
    backend.remove(rec_id, commit=self.commit)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 199, in remove
    doc_id = get_identifier(obj_or_string)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/__init__.py", line 37, in default_get_identifier
    return u"%s.%s" % (get_model_ct(obj_or_string),
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/__init__.py", line 81, in get_model_ct
    return "%s.%s" % get_model_ct_tuple(model)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/__init__.py", line 75, in get_model_ct_tuple
    return (model._meta.app_label, model._meta.model_name)
AttributeError: 'NoneType' object has no attribute '_meta'
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 183, in handle
    return super(Command, self).handle(*items, **options)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/django/core/management/base.py", line 623, in handle
    label_output = self.handle_label(label, **options)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 289, in update_backend
    backend.remove(rec_id, commit=self.commit)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 199, in remove
    doc_id = get_identifier(obj_or_string)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/__init__.py", line 37, in default_get_identifier
    return u"%s.%s" % (get_model_ct(obj_or_string),
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/__init__.py", line 81, in get_model_ct
    return "%s.%s" % get_model_ct_tuple(model)
  File "/Users/anurag/VirtualEnvs/myenv/lib/python2.7/site-packages/haystack/utils/__init__.py", line 75, in get_model_ct_tuple
    return (model._meta.app_label, model._meta.model_name)
AttributeError: 'NoneType' object has no attribute '_meta'
```

## Steps to reproduce the behaviour

1. Build Full index
2. Manually remove from database
3. Update index with remove parameter

This is my index definition for reference

    class ProductViewIndex(indexes.SearchIndex, indexes.Indexable):
	   text = indexes.CharField(document=True, use_template=True)
	   ProductViewId = indexes.IntegerField(model_attr='id', indexed=True, stored=True)
	   productName = indexes.CharField(model_attr='getProductName', indexed=True, stored=True)
	   userId = indexes.IntegerField(model_attr='getUserId', indexed=True, stored=True, null=True)
	   sessionKey = indexes.CharField(model_attr='getSessionKey', indexed=True, stored=True, null=True)
	   count = indexes.IntegerField(model_attr='count', indexed=True, stored=True)

	def get_model(self):
		return ProductView

## Configuration

* Operating system version: OS X El Capitan - 10.11.5
* Search engine version: elasticsearch==2.0.0
* Python version: 2.7.10
* Django version: 1.8.11
* Haystack version: 2.4.1

**Comment by acdha** [comment]
ElasticSearch 2 is not supported in  2.4.1.  It should be in the next release.

**Comment by acdha** [comment]
See https://github.com/django-haystack/django-haystack/pull/1336 if you would like to help test or contribute to that work

**Comment by anuragjain** [comment]
Hello,
I downgraded elasticsearch version to 1.9.0 and still got the same error.

**Comment by acdha** [comment]
Since you're still having this problem, do you have a reproducible test-case for this? It'd be really useful to know what e.g. `obj_or_string` is at the point where this is failing. If you run it under `pdb` you

**Comment by anuragjain** [comment]
After using pdb, I came to know that stale_records is coming as a set with **None** value which is causing the issue
I used pdb on line 287 in this file 
lib/python2.7/site-packages/haystack/management/commands/update_index.py_

    if stale_records:
                    if self.verbosity >= 1:
                        print("  removing %d stale records." % len(stale_records))
                    import pdb; pdb.set_trace()
                    for rec_id in stale_records:

    -> for rec_id in stale_records:
    (Pdb) stale_records
    set([None])
    (Pdb) 

I then tried finding out where is stale_records set being generated. Essentially the rec_id is coming as None from this method

    (Pdb) index_pks = SearchQuerySet(using=backend.connection_alias).models(model)
    (Pdb) index_pks = index_pks.values_list('pk', 'id')
    (Pdb) index_pks
    INFO GET http://127.0.0.1:9200/haystack/modelresult/_search?_source=true [status:200    request:0.008s]
    [[u'3', None], [u'4', None], [u'5', None]]
    (Pdb)

**Comment by acdha** [comment]
It sounds like we might want to put some better error logging in for this case but that should never happen in normal operations. If you query ElasticSearch directly, what do those records look like?

**Comment by anuragjain** [comment]
If I query directly, I get all the records including the stale ones with all the data.

**Comment by acdha** [comment]
@anuragjain Are the values in the `id`, `django_ct`, and `django_id` fields correct? If they're null that'd explain the `None` values above but not how they got there; if they're set, do they point to e.g. a model which has been removed from your index?

**Comment by anuragjain** [comment]
In settings, I have defined HAYSTACK_ID_FIELD = 'haystack_id'
When I query elastic search directly, and print the data, following are the output
```
SearchQuerySet()[0].haystack_id
INFO GET http://127.0.0.1:9200/haystack/modelresult/_search?_source=true [status:200 request:0.013s]
u'analytics.productview.3'
```
However id, django_ct and django_id are none
```
 SearchQuerySet()[0].django_id
INFO GET http://127.0.0.1:9200/haystack/modelresult/_search?_source=true [status:200 request:0.012s]
>>> 
```

**Comment by acdha** [comment]
So if you use something like curl to query ElasticSearch directly, are the `django_ct` and `django_id` fields missing, present with a value of `null`, etc?

**Comment by anuragjain** [comment]
I am not sure about the curl syntax, but when I am querying from django shell, I am not getting any of these fields
    ./manage.py shell
    >>> from haystack.query import SearchQuerySet
    >>> SearchQuerySet()
    INFO GET http://127.0.0.1:9200/haystack/modelresult/_search?_source=true [status:200 request:0.015s]
     [<SearchResult: analytics.productview (pk=u'3')>, <SearchResult: analytics.productview (pk=u'4')>, <SearchResult: analytics.productview (pk=u'5')>]
    >>> SearchQuerySet()[0].django_id
    INFO GET http://127.0.0.1:9200/haystack/modelresult/_search?_source=true [status:200 request:0.012s]
    >>>

**Comment by anuragjain** [comment]
As per the SearchResult API, the available attributes are **app_label**, **model_name**, **pk**, **score**, **object**, **model**, **verbose_name**, **verbose_name_plural**, **searchindex**, **distance** . So from the searchResult, I cannot get django_id or django_ct. TO verify, I tried printing the object of each searchResult. The data which was removed from the database got the following error which is correct
  ```
  Object could not be found in database for SearchResult '<SearchResult: analytics.productview   (pk=u'4')>'.
    ERROR Object could not be found in database for SearchResult '<SearchResult: analytics.productview (pk=u'4')>'.
```
I am not sure why its not able to remove the stale records

**Comment by acdha** [comment]
Since this does not normally happen and there's no code I can run to reproduce the failure, I have only the information you provide. The point to querying ElasticSearch directly – without using Haystack in any way – was to see whether the data in the index is corrupt or whether there's some issue with how it's being retrieved or processed by Haystack.

The failure for the object which was removed is normal, and not getting that error for the other three records is also expected.

**Comment by anuragjain** [comment]
This is how to reproduce this error.
Install haystack 2.4.1, ElasticSearch 1.7.5 and elasticsearch python binding 1.7.0. Run the elastic search server. Configure django settings file to include haystack_connections. 
Now define a model with following attributes and method

`class ProductView(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True)
	session = models.ForeignKey(Session, null=True, blank=True)
	productLevelDetail = models.ForeignKey(ProductLevelDetail, on_delete=models.PROTECT)
	count = models.PositiveIntegerField(default=0)

	def getProductName(self):
		return self.productLevelDetail.name

	def getUserId(self):
		if self.user:
			return self.user.id
		else:
			return None

	def getSessionKey(self):
		if self.session:
			return self.session.session_key
		else:
			return None
			`

Here instead of foreign keys, you can just use charfields. Do database migration so that tables are created in database.
Now define search_index as outlined below
`from haystack import indexes
from analytics.models import *


class ProductViewIndex(indexes.SearchIndex, indexes.Indexable):
	text = indexes.CharField(document=True, use_template=True)
	id = indexes.IntegerField(model_attr='id', indexed=True, stored=True)
	productName = indexes.CharField(model_attr='getProductName', indexed=True, stored=True)
	userId = indexes.IntegerField(model_attr='getUserId', indexed=True, stored=True, null=True)
	sessionKey = indexes.CharField(model_attr='getSessionKey', indexed=True, stored=True, null=True)
	count = indexes.IntegerField(model_attr='count', indexed=True, stored=True)

	def get_model(self):
		return ProductView
`
Now insert two rows into your productView table with pk as 3 and 4 respectively. 
Run the following command to build index
`./manage.py rebuild_index`
Once this command runs successfully, delete row from database with pk as 4 and create a new row with pk as 5. Now run the following command
`./manage.py update_index --remove`

At this point, you should see the error.
I am not doing any unusual operation. Just deleting row from database and updating index.

**Comment by anuragjain** [comment]
@acdha  I found out the reason for this issue but not clear on solution. So here is the case,

I wanted to use different settings for analyzer and tokenizers, so I extended the **ElasticsearchSearchBackend** class and updated settings according to my use case. I also defined the same in haystack_connections
```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'home.my_elasticbackend.ConfigurableSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
        'INCLUDE_SPELLING':True,
    },
}
```
Following are the content of my custom backend file
```
from django.conf import settings

from haystack.backends.elasticsearch_backend import ElasticsearchSearchBackend, ElasticsearchSearchQuery
from haystack.backends import BaseEngine


class ConfigurableSearchBackend(ElasticsearchSearchBackend):
	DEFAULT_SETTINGS = settings.ELASTICSEARCH_INDEX_SETTINGS

	def __init__(self, connection_alias, **connection_options):
		super(ConfigurableSearchBackend, self).__init__(connection_alias, **connection_options)


class ConfigurableSearchEngine(BaseEngine):
    backend = ConfigurableSearchBackend
    query = ElasticsearchSearchQuery
```
Here I have just modified the DEFAULT_SETTINGS variable and nothing else.
If instead of **ConfigurableSearchEngine**, I use the default **ElasticsearchSearchEngine** everything works fine. 

I tried to dig deep in the source code to look for the potential reason for error, but couldn't find anything.  

I can also see issue [1371](https://github.com/django-haystack/django-haystack/issues/1371) also having issue while updating index, although error is different, it looks related.
Hope this helps in finding out the root case, let me know if you have any comments on how to solve this.

**Comment by anuragjain** [comment]
I am able to solve this issue. The problem was HAYSTACK_ID_FIELD defined in settings file as my field name (id) was colliding with the default haystack field. http://django-haystack.readthedocs.io/en/v2.4.1/settings.html#haystack-id-field

I changed my field name to something else and removed this setting and everything seems to be working fine. Note that even if I change my field name but don't remove this entry from settings file, it still gives me error. 
I hope this will help someone.
