### ISSUE TITLE
DNS broken: haystacksearch.org returning unknown

### ISSUE THREAD

**Issue by rwillmer** [django-haystack/django-haystack#1385]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Steps to reproduce the behaviour

1. nslookup haystacksearch.org

## Configuration

* Operating system version:
* Search engine version:
* Python version:
* Django version:
* Haystack version:

**Comment by acdha** [comment]
I don't know whether @toastdriven fixed this but it's working now. In the future, it's always a good idea to include the output of `nslookup`, `dig`, etc. or a durable trace using a tool like wheresitup.com in case the problem is specific to your network location.
