### ISSUE TITLE
Worst documentation ever?

### ISSUE THREAD

**Issue by eronaeon** [django-haystack/django-haystack#1388]
Really thanks for the software from the author and contributers. **BUT**, haystack's documentation is one of the worst and most irritating documentations I'eve ever read. The `getting started` chapter needs to be completely eliminated and something else takes it's place. Frankly it makes haystack very unfriendly to the newcomers. 

Thanks!

**Comment by Alkalit** [comment]
@eronaeon What exactly is wrong? Since you mention `getting started`, I guess, the problem came from you start learning haystack. I can only suggest mention in docs that haystack is just are python/django wrapper for search engines API. So you need to learn specific backend before.

**Comment by acdha** [comment]
@eronaeon Remember that Haystack is a volunteer project – nobody is paid to work on it and what you get is heavily supported by people choosing to donate their spare time making something which you can use for free. There are plenty of things I'd like to change about it too but that's not my day job and, to be frank, content-free complaints are a great way to kill someone's motivation to work on an open-source project. It's also worth remembering that Haystack has been around for a long time and it, Django, and all of the search engines have changed considerably over time.

If you have some specific, actionable points which could be improved, please open a separate issue or pull request for any proposed changes.

**Comment by eronaeon** [comment]
@acdha, I am so sorry. I didn't mean to be rude at all. Haystack is my first django app, and I am a newcomer to them both. The problem is haystack supposes that you are already experienced with django and worked with some apps. And that's why the tutorial chapter is utterly confusing to beginners. I couldn't understand anything until I read the source code myself.

**Comment by acdha** [comment]
@eronaeon Yeah, the tutorial definitely could definitely use some improvements since it was written by someone with a great deal of existing Django experience. If you send some pull requests I'd be happy to discuss / merge.
