### ISSUE TITLE
Parentheses on spelling_suggestion for run query

### ISSUE THREAD

**Issue by SteveByerly** [django-haystack/django-haystack#1394]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour
Retrieving the spelling suggestion from a search provides the string representation: `'django'`

## Actual behaviour
The spelling suggestion is wrapped in parens, as part of the string: `'(django)'`

## Steps to reproduce the behaviour

1. Tested using Solr 4.10
2. Setup spellchecker on '/select' requestHandler
3. call `SearchQuerySet().auto_query('djngo').spelling_suggestion()`
4. the returned result will be `'(django)'`
5. call `SearchQuerySet().spelling_suggestion('djngo')`
6. the returned result will be `'django'`

The reason this happens is that the `q` field is being used for the spellcheck based on my solrconfig.xml. When doing the spelling_suggestion without the filter, it's using the `spellcheck.q` field.

Code adding the parens:
https://github.com/django-haystack/django-haystack/blob/ef0010a7d6a9b6acd6e8f21258a1f86764c53c75/haystack/backends/solr_backend.py#L617

I'm using the forms and generic views. I could use `filter(content=Raw())` instead of `auto_query` - this would give me the desired result, but I'm not sure if it's a best-practice.

Should the code linked above only add the parens if `index_fieldname ` is truthy? 

## Configuration

* Operating system version: OSx El Cap
* Search engine version: 2.5.dev2
* Python version: 2.7
* Django version: 1.9
* Haystack version: 4.10

**Comment by acdha** [comment]
I added something recently which allows you to call `set_spelling_query()` for exactly this reason – I needed to use Solr's edismax query parser and that had the same problem with leaking query syntax into the spelling suggestion:

https://github.com/django-haystack/django-haystack/blob/master/docs/searchqueryset_api.rst#set_spelling_query

**Comment by SteveByerly** [comment]
Awesome, thank you very much for your time!

**Comment by acdha** [comment]
Thanks - I'd love to know it works for you in case there should be a charge before releasing 2.5

**Comment by SteveByerly** [comment]
Seems to be working perfectly. Sorry I didn't see that method earlier, must have been viewing the 2.4.1 docs.

Thank you again for the time looking at this.
