### ISSUE TITLE
Add support for customized date facet.

### ISSUE THREAD

**Issue by askfor** [django-haystack/django-haystack#140]
For example i want a date facet like this:
Past 24 hours
Past week
Past year

The date gap is not fixed between each pair of date. Current api does not support this way of facet.
Maybe haystack can add a method or a parameter so i can pass the date i needed.
Like this:
[('Past 24 hours', datetime.date(2009,11,28), datetime.date(2009,11,29) ),    
 ('Past week', datetime.date(2009,11,23), datetime.date(2009,11,29) ,     
 ('Past year', datetime.date(2009,1,1), datetime.date(2009,11,29) ]

**Comment by sampeka** [comment]
It's been a long time since this issue was last progressed and there is no clear path to moving it forward. I'm going to close this for now but please feel free to raise a new one.
