### ISSUE TITLE
Unable to override pagination / Pagination buggy

### ISSUE THREAD

**Issue by Brobin** [django-haystack/django-haystack#1414]
## Expected behaviour

Visiting `mysite.com/catalog/` should have the same `page_obj.paginator.count` as `mysite.com/?page=1`.

## Actual behaviour

Without the `page` parameter, the paginator says it has 291 results, and with, it has 84 results. which leads to having too many pagination buttons at the bottom on my page.

## What I've tried

I tried adding the `build_page` method to my cusotm search class, but I put logging statements in it and it was never hit.

#### Views.py
```python
class ProductSearchView(SearchView):
    form_class = ProductSearchForm
    queryset = SearchQuerySet().order_by('-recent_clicks')
    template_name = 'product/catalog/search.html'

    def build_page(self):
        log.debug("building page")  # This line is never hit!
        try:
            page_no = int(self.request.GET.get('page', 1))
        except (TypeError, ValueError):
            raise Http404("Not a valid number for page.")
        if page_no < 1:
            raise Http404("Pages should be 1 or greater.")
        start_offset = (page_no - 1) * self.results_per_page
        self.results[start_offset:start_offset + self.results_per_page]
        paginator = Paginator(self.results, self.results_per_page)
        try:
            page = paginator.page(page_no)
        except InvalidPage:
            raise Http404("No such page!")
        return (paginator, page)

    def get_context_data(self, **kwargs):
        context = super(ProductSearchView, self).get_context_data(**kwargs)
        context['result_size'] = context['page_obj'].paginator.count
        context['search_param'] = self.request.GET.get('q', None)
        return context
```

#### Urls.py
```python
 url(r'^catalog/$',
    ProductSearchView.as_view(),
    name='product-catalog-search'),
```

## Configuration

* Operating system version: Ubuntu 16.04
* Search engine version: Elasticsearch 2.3.4
* Python version: 3.4.3
* Django version: 1.9.7
* Haystack version: 2.5.0

**Comment by acdha** [comment]
Based on the `as_view` call, it looks like you're using the newer generic views. The `build_page` method is used by Haystack's original (and now deprecated) search view class, which predates Django including the generic CBVs. 

The MultipleObjectMixin documentation describes the paginate_queryset method:

https://docs.djangoproject.com/en/1.9/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.paginate_queryset

**Comment by Brobin** [comment]
I still get different numbers of results for the following urls. At first I thought it was the pagination, but now I'm logging `queryset.count()` in the paginate method and it's different if the page is set. Any ideas?

`mysite.com/catalog/`
`mysite.com/catalog/?page=1`

**Comment by Brobin** [comment]
Ah, it was something in my form. I got it resolved. Thanks!
