### ISSUE TITLE
Redirect after getting result in django haystack

### ISSUE THREAD

**Issue by skizzy** [django-haystack/django-haystack#1419]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
I want to get the model the user perform a search on in order to redirect the user to a standalone page of the particular model. I tried to do that in views but it's not reflecting even after I modify my urls.  After doing all this, it failed to redirect me to a standalone page. It will display the result in the default 'search.html' template.
## Actual behaviour
 have two models indexed in Django Haystack 'Hotel' and 'Restaurant'. I was able to extend the ModelSearchForm for it to ensure a user select one model before it can perform the search, and it worked.

What am I missing?

## Steps to reproduce the behaviour

1. views

          class MySearchView(SearchView):
                   def get_results(self):
                         results=super(MySearchView, self).get_results()
                         if results.models=='hotel':
                            return render(request, 'search/hotels_only.html', {'results':results})

                        elif results.models=='restaurant':
                              return render(reuqest, 'search/restaurants_only.html',{'results':results})
                       else:
                          return results

URL:

         url(r'^search/', search_view_factory(view_class=MySearchView, form_class=ExtendModelSearchForm), name='haystack_search'),

Hotels only template

              {% if query %}
                     <h3>Results</h3>

                       {% for result in results %}
                            <p>
                              <a href="{{ result.object.get_absolute_url }}">{{ result.object.name }}</a>
                           </p>
                       {% empty %}
                             <p>No results found.</p>
                       {% endfor %}

## Configuration

* Operating system version:
Windows 10
* Search engine version:
Whoosh 2.7
* Python version:
2.7
* Django version:
1.9.6
* Haystack version:
2.5.0

**Comment by SteveByerly** [comment]
Hi @skizzy ,
It looks like you're using the traditional views `haystack.views.SearchView`?

If so, you'll need to override the `create_response` method as this is what returns the response. When you override the `get_results` method you are only changing the context for the template response.
