### ISSUE TITLE
<class 'haystack.query.SearchQuerySet'> doesn't support list()

### ISSUE THREAD

**Issue by martinsam** [django-haystack/django-haystack#1421]
list(sqs) --> Exception Value: 	

__len__() should return >= 0

- sqs[45] give the same result of sqs[0]
- sqs[45:46] gibe the same result of sqs[0:1]

Everything it's ok , except pagination.

Steps to reproduce the behaviour
 without form, seems it's ok : 
```


from haystack.query import SearchQuerySet
sqs = SearchQuerySet()
search = sqs.models(YourModel)
list(search)

```

Configuration

    Operating system version: Macos X 10.11.6
    Search engine version: xapian-haystack==2.0.0
    Python version: Python 2.7.10
    Django version: 1.4.22
    Haystack version: 2.1.1 dev

**Comment by acdha** [comment]
I don't think anyone will be able to help you without more information or, preferably, a reproducible test case. The issue template at https://github.com/django-haystack/django-haystack/blob/master/.github/issue_template.md requests all of the information needed to investigate a reported problem.

**Comment by martinsam** [comment]
Search method of SearchForm, seems like the problem.

**Comment by acdha** [comment]
This doesn't happen in a standard Haystack install so it's probably specific to your model (based on the above, this could be as simple as whether `__repr__` works?) or `SearchIndex` configuration. I noticed that the version of haystack listed is fairly old – [the current release is 2.5.0](https://pypi.python.org/pypi/django-haystack/2.5.0) – and I would check the xapian-haystack issues to make sure there isn't a known or recently fixed problem there, too: https://github.com/notanumber/xapian-haystack/issues

**Comment by martinsam** [comment]
After rewrite search(self) seems it's ok 

Quick and dirty test : 

```python 
    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        sqs = self.searchqueryset.auto_query(self.cleaned_data['q'])

        # if self.load_all:
        #     sqs = sqs.load_all()

        return sqs
```

**Comment by acdha** [comment]
If pulling out `load_all` fixed it, it sounds like the problem is specific to some code in your project. Our test suite covers `load_all` in normal usage so I'd start by looking at the exception stack trace and seeing where custom code is involved in either the model or the `SearchIndex`.

**Comment by SteveByerly** [comment]
@martinsam if you're still able to reproduce this error and have more code/steps to reproduce that you can supply, we'll be happy to take a look at it. As it stands, there's not much we can do to help.
