### ISSUE TITLE
Woosh supports boost since 2.0

### ISSUE THREAD

**Issue by DylannCordel** [django-haystack/django-haystack#1424]
Hi,

In code [whoosh backend, around line 194](https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/whoosh_backend.py#L194): 

```python
# Document boosts aren't supported in Whoosh 2.5.0+.
if 'boost' in doc:
    del doc['boost']
```

But Whoosh supports document boost (from 2.0 to current version). Check [here (2.0 version)](https://bitbucket.org/mchaput/whoosh/src/c159748f54665733d903ffc071db967392a65d6d/src/whoosh/writing.py?at=default&fileviewer=file-view-default#writing.py-185) or [here for the master version](https://bitbucket.org/mchaput/whoosh/src/e344fb64067e45d47ec62dc65a75a50be51264a7/src/whoosh/writing.py?at=default&fileviewer=file-view-default#writing.py-389)

In whoosh backend, we should have:

```python
if 'boost' in doc:
    doc['_boost'] = doc['boost']
    del doc['boost']
```

**Comment by acdha** [comment]
I'll close this to keep the discussion in #1425
