### ISSUE TITLE
How to use SearchResult.get_additional_fields()

### ISSUE THREAD

**Issue by RamizSami** [django-haystack/django-haystack#1427]
I am new to django haystack. I am using Haystack with Xapian backend. My search results from search queryset API dont give all the fields. I read in the documentation that I need to use How to use SearchResult.get_additional_fields() method from Search Result API but the documentation doesn't provide any examples. Can someone please let me know how to use the method with my queryset?

**Comment by SteveByerly** [comment]
Hi @RamizSami , what exactly are you trying to achieve? The `get_additional_fields` method will simply return fields that were saved to the search engine, but not by the defined haystack indexes. I believe it's only useful if you passed in extra data to your backend explicitly.

If you have more information, please re-open this issue and i'll be happy to help.
