### ISSUE TITLE
Any plans to update to use more like this with whoosh?

### ISSUE THREAD

**Issue by RamizSami** [django-haystack/django-haystack#1429]
When is the new version of Haystack coming which incorporates "more like this" with whoosh?

**Comment by acdha** [comment]
More like this support in Whoosh was added in 2013 as part of the Haystack 2 release:

https://github.com/django-haystack/django-haystack/commit/6b3407a4e1ddf6d82e76e477d0fd4258fd36dbf5

See http://django-haystack.readthedocs.io/en/v2.5.0/backend_support.html

Haystack is a volunteer project, so it's worth remembering that features are generally added when someone who uses a particular backend contributes the extra work. If you encounter something you need which isn't already present or in a pull request which you could help with, please open a new pull request.
