### ISSUE TITLE
Invalid block tag: 'highlight'

### ISSUE THREAD

**Issue by nikola** [django-haystack/django-haystack#143]
I have implemented usage of the HighlightedSearchForm in my URLConf according to the example in the documentation:

<pre>
 url(r'^search/?$', SearchView(
       template='search/search.html',
       searchqueryset=sqs,
       form_class=HighlightedSearchForm,
    ), name='haystack_search'), 
</pre>

However, any usage of the {% highlight ... %} tag in the template throws an error:

Invalid block tag: 'highlight'

Am I missing something here? Do I have to modify the settings.py to be able to use the tag?

It seems like Django is complaining it doesn't know anything about the tag. (Omitting it works fine, i.e Haystack with Xapian as my backend works correctly and yields results, and I can iterate over results in my template and do all kinds of processing on result items.)

EDIT:

Ok, I discovered that I need to call this first:

<pre>
{% load highlight %}
</pre>

Another issue:

I can't chain filters to the highlighted text, i.e. I can't do the following:

<pre>
{% highlight result.fulltext|safe with query %}
</pre>

Will this be implemented at a later point in time?

**Comment by sampeka** [comment]
It's been a long time and a ton of changes since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
