### ISSUE TITLE
update_index by index age?

### ISSUE THREAD

**Issue by richardasaurus** [django-haystack/django-haystack#1435]
Is there a way to `update_index` but just update index records added say more than 2 days ago?

I know `get_updated_field` exists and the `age` command line arg, but this age is to represent the age of the thing being indexed rather than the index itself?

Thanks in advance

**Comment by SteveByerly** [comment]
There might be a better ways, but here are a few options:

1. Subclass `SearchIndex` and add some new methods to handle objects of a certain age. You'd basically want to have a second `update` and `index_queryset` method (or maybe combine into one). You'd then call this new update method programmatically through a new management command or some other function in your project.

https://github.com/django-haystack/django-haystack/blob/master/haystack/indexes.py#L142
https://github.com/django-haystack/django-haystack/blob/master/haystack/indexes.py#L251

2. Get the objects from the DB that are x days old, then iterate over them and call update_object on the SearchIndex responsible for those objects.

https://github.com/django-haystack/django-haystack/blob/master/haystack/signals.py#L42
https://django-haystack.readthedocs.io/en/v2.5.0/best_practices.html?highlight=update#use-of-a-queue-for-a-better-user-experience

**Comment by richardasaurus** [comment]
Thanks
