### ISSUE TITLE
Django 1.10 release

### ISSUE THREAD

**Issue by ellmetha** [django-haystack/django-haystack#1437]
Hi!

I wonder: is it planned to release a version of *django-haystack* that is compatible with Django 1.10? I noticed that Travis builds pass for ``Django==1.10a1``. However the setup module of *django-haystack* prevents the use of Django 1.10 (https://github.com/django-haystack/django-haystack/blob/master/setup.py#L16).

Thanks!

**Comment by acdha** [comment]
It's planned but that's in setup.py because we need some help to get it finished. #1434 had much of it working but that didn't reach the point of the test suite completely passing. If you have time to work on this, I would start there.

**Comment by pa-jama** [comment]
+1, in fact I'm currently still using django 1.8 because haystack 2.5 hasn't been released yet which supports 1.9

**Comment by acdha** [comment]
2.5 was released:

https://pypi.python.org/pypi/django-haystack/2.5.0

We definitely need to get a 1.10 support release out soon, however.

**Comment by derekolsson** [comment]
Any news on this?

**Comment by acdha** [comment]
@derekolsson Nothing yet but if you have time to work on this, I'm sure your contributions would be appreciated by the community

**Comment by patrys** [comment]
Is there an issue tracking what remains to be done for 1.10 compatibility? We can consider donating the necessary man power but need to know the scope of work first.

**Comment by acdha** [comment]
@patrys I think #1434 was the furthest along - it was down to a few failing tests but I haven't looked to see how involved the changes appear to be.

**Comment by SalahAdDin** [comment]
:+1: For this!!!

**Comment by acdha** [comment]
For anyone interested in this, if you have time to test the code in #1445 with your apps please update the ticket with the results

**Comment by artursmet** [comment]
I tested this branch with my project, also with a search queryset that contained `.only()` queries. It works, tested with elasticsearch backend.

**Comment by derekolsson** [comment]
Tested it as well in my project with all sorts of queries on elasticsearch backend, haven't seen any issues so far either. Thanks so much for this!

**Comment by acdha** [comment]
I just tagged v2.5.1
