### ISSUE TITLE
Error running travis tests: Invalid environment marker

### ISSUE THREAD

**Issue by henriquechehad** [django-haystack/django-haystack#1442]
I sent a PR and tests stopped here:

`error: Setup script exited with error in urllib3 setup command: Invalid environment marker: python_version <= "2.7"`

https://travis-ci.org/django-haystack/django-haystack/jobs/163455396#L665

I guess need to update setuptools

**Comment by ahoho** [comment]
@acdha, I've noticed this in a few PRs. Should we set a `urllib3` dependency in `setup.py` so that the elasticsearch doesn't trigger this failing setup script?

**Comment by ahoho** [comment]
This is happening on several different PRs. We're not specifying a setuptools version in `travis.yml`, so I would assume it's using the most recent version already. Should we create a `urllib3==1.17` dependency, which appeared to work for past builds, to avoid this problem?

**Comment by acdha** [comment]
@ahoho I have no problem with a dependency but I wouldn't pin a specific version – can we simply depend on `requests`, which is used by both the ES and Solr backends, or at least `urllib3>=1.17` to avoid preventing future upgrades?

**Comment by ahoho** [comment]
Based on [the docs](http://django-haystack.readthedocs.io/en/v2.4.1/installing_search_engines.html#elasticsearch) and the [elasticsearch source](https://github.com/elastic/elasticsearch-py/blob/6e94bf76adbbbb2fe5b927a3933ed535cd738387/setup.py#L16), it looks like it's an elasticsearch-genereated install. [This upstream issue](https://github.com/shazow/urllib3/issues/986) and resulting [PR](https://github.com/shazow/urllib3/pull/987) is identical to ours, and suggests updating setuptools, as @henriquechehad mentioned. I guess the question is: whose setuptools is out of date, and how do we update it?

**Comment by acdha** [comment]
I just merged @jeremycline's setuptools update in #1444
