### ISSUE TITLE
Problem with sites.get_current()

### ISSUE THREAD

**Issue by tBaxter** [django-haystack/django-haystack#146]
using 
current_site = Site.objects.get_current() in the model breaks ``handle_registrations`` when used from a request but not from a management command.

Snippet:
from django.contrib.sites.models import Site
...
        
class Entry(models.Model):
    blog             = models.ForeignKey(Blog, limit_choices_to={'site':Site.objects.get_current()}, blank=True, null=True)
....

using settings.SITE_ID instead works, though.

**Comment by sampeka** [comment]
It's been a long time and a ton of changes since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
