### ISSUE TITLE
SearchQueryset / Filter: Feature or bug ?

### ISSUE THREAD

**Issue by alexsilva** [django-haystack/django-haystack#1463]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
I have two index classes (media and info).
In the index info I have the field `text`, and `pub_date`.
In the index `media`, I have only the field `text`.
What I expected was the following:
```
>> qs = SearchQuerySet().auto_query('pdf').filter(pub_date__gte=datetime(year=2016, month=1, day=1))
>>> [<SearchResult: model.info (pk=2865)>, <SearchResult: model.media (pk=2839)>, ...]
```
Because I'm sure that media has in its text the term pdf and info also contains.

## Actual behaviour
```
>> qs = SearchQuerySet().auto_query('pdf').filter(pub_date__gte=datetime(year=2016, month=1, day=1))
>>> [<SearchResult: model.info (pk=2865)>, <SearchResult: model.info (pk=2839)>, ...]
```
Somehow results for media are excluded because of the pub_date field. 
This does not make sense considering I have two index classes.

## Steps to reproduce the behaviour
Filter SearchQueryset with a field that is not common to both indexes, such as in the `pub_date`  case.

## Configuration

* Operating system version: Win10; Win Server 2008
* Search engine version: 1.2.22 (xapian-haystack 2.0.0)
* Python version: 2.7 32bits
* Django version: 1.9.9
* Haystack version: 2.5.0

So the question: Feature or bug ?

**Comment by acdha** [comment]
The code is working correctly but the behaviour could probably use better documentation: Haystack builds a single index using *all* of the fields defined on every model. For most users, this is what you want since it allows someone to type text into a field and get ranked results for everything in the index no matter the source model, and you can filter to a specific type when you need to using something like [`models()`](http://django-haystack.readthedocs.io/en/v2.5.1/searchqueryset_api.html#models).

Unfortunately, it can be confusing in cases like yours since querying on a field value implicitly filters out any records which don't have that field.

**Comment by alexsilva** [comment]
@acdha  My intention was to get a list of combined results (containing media and info). And the filters would be a way to exclude certain results, but not a specific type (info or media).
```
?text=pdf&publication_date_lte=20070910&contenttype=media
```
In my api I even considered the possibility of exclude a type, but never through the use of `filter`, only through `models`.

Lua source:
```
  ...
  if (options.contenttype == "info") then
    self.searchqueryset = self.searchqueryset.models(models.Info)
  elseif (options.contenttype == "media") then
     self.searchqueryset = self.searchqueryset.models(models.Media)
   end
```
This will force me to have `pub_date` in the index media too, every field I put in info I will have to have in 
media.
If you think about it, not every field of a type makes sense in another.

**Comment by acdha** [comment]
The problem is that your `pub_date` filter is inclusive so it requires that field to have a value. It sounds like all you need is an `SQ` filter: 

https://django-haystack.readthedocs.io/en/v2.5.1/searchquery_api.html#sq-objects

Something like `filter(SQ(pub_date=None) | SQ(pub_date__gte=…))` or, if you have more complicated model-specific logic, something like `SQ(django_ct=…, pub_date__gte=…, other_query=…) | SQ(…)`

**Comment by alexsilva** [comment]
```
SQ(django_ct=…, pub_date__gte=…, other_query=…)
```
I expected that the example above would work.

This
```
filter(SQ(django_ct='model.info', pub_date__lte=datetime.datetime(2007, 9, 10, 0, 0)))
```
Returns an empty list, when it should return at least two results.

In this case:
```
filter(SQ(pub_date__lte=datetime.datetime(2007, 9, 10, 0, 0)))
```
I get the expected result (two results).

**Comment by alexsilva** [comment]
Probably `xapian-haystack` does not work with filter for the field `django_ct`.

**Comment by acdha** [comment]
I would check your code & data to confirm the values are working as expected, and check the value of `sqs.query.build_query()` to confirm it works as expected. 

As an example, here's what it looks like when I filter on the model type for values which are present:

```python
>>> sqs.filter(SQ(django_ct='core.itemtranslation', institution='test')).count()
7914
>>> sqs.filter(SQ(django_ct='core.itemtranslation', institution='library-of-congress')).query.build_query()
u'(django_ct:(core.itemtranslation) AND institution:(test))'
```

Looking at your example above, is your app really named `model`? Django content type values are usually `app_name.model_name` unless you've customized it.

**Comment by alexsilva** [comment]
I tested in the python shell and the examples below show how I do not get the results you expect.

```
>>> x = SearchQuerySet().auto_query('pdf').filter(publicationDate__gte=datetime(year=2016, month=1, day=1))
>>> x.count()
>>> 2
>>> x[0].django_ct
>>> u'publique.info'
>>> [i for i in x]
>>> [<SearchResult: publique.info (pk=2865)>, <SearchResult: publique.info (pk=2839)>]
>>> print x.query.build_query()
>>> Xapian::Query((Zpdf:(pos=1) AND VALUE_RANGE 13 20160101000000 99990101000000))
>>>
>>> # Using django_ct
>>> x = SearchQuerySet().auto_query('pdf').filter(django_ct=u'publique.info', publicationDate__gte=datetime(year=2016, month=1, day=1))
>>> x.count()
>>> 0
>>> print x.query.build_query()
>>> Xapian::Query((Zpdf:(pos=1) AND (CONTENTTYPE^ PHRASE 3 CONTENTTYPEpublique.info PHRASE 3 CONTENTTYPE$) AND VALUE_RANGE 13 20160101000000 99990101000000))

```

**Comment by acdha** [comment]
It might be necessary to use `django_ct__exact=` to avoid stemming. Obviously that doesn't matter in my Solr example but it might with Xapian – I was expecting to see "publique.info" quoted above.

**Comment by alexsilva** [comment]
I compiled `xapian 1.4.1` to see if anything changed, but it does not seem to have changed anything.

```
print 'pub date only'
x = SearchQuerySet().auto_query('pdf').filter(publicationDate__gte=datetime(year=2016, month=1, day=1))
print x.query.build_query()
print x.count()
##
print "django_ct__exact"
x = SearchQuerySet().auto_query('pdf').filter(django_ct__exact='publique.info',
                                              publicationDate__gte=datetime(year=2016, month=1, day=1))
print x.query.build_query()
print x.count()

print "django_ct only"
x = SearchQuerySet().auto_query('pdf').filter(django_ct='publique.info',
                                              publicationDate__gte=datetime(year=2016, month=1, day=1))
print x.query.build_query()
print x.count()

# ---------- results!

pub date only
Query((Zpdf@1 AND VALUE_RANGE 13 20160101000000 99990101000000))
2
django_ct__exact
Query((Zpdf@1 AND (CONTENTTYPE^ PHRASE 3 CONTENTTYPEpublique.info PHRASE 3 CONTENTTYPE$) AND VALUE_RANGE 13 20160101000000 99990101000000))
0
django_ct only
Query((Zpdf@1 AND (CONTENTTYPE^ PHRASE 3 CONTENTTYPEpublique.info PHRASE 3 CONTENTTYPE$) AND VALUE_RANGE 13 20160101000000 99990101000000))
0
```

**Comment by alexsilva** [comment]
```

**Comment by alexsilva** [comment]
Even explicitly inserting quotation marks, continues to return no results.

```
x = SearchQuerySet().auto_query('pdf').filter(django_ct='\"publique.info\"',
			  publicationDate__gte=datetime(year=2016, month=1, day=1))
print x.query.build_query()
print x.count()

Query((Zpdf@1 AND (CONTENTTYPE^ PHRASE 3 CONTENTTYPE"publique.info" PHRASE 3 CONTENTTYPE$) AND VALUE_RANGE 13 20160101000000 99990101000000))
0
```

**Comment by alexsilva** [comment]
It looks like the problem is actually in the xapian backend.
Below the same idea, only using the whoosh indexer. It works perfectly.

Xapian is an excellent indexer, written in C and extremely fast, however due to this problem it becomes very limited.

I think I'm going to have to use a combination two two.
```
sqs = SearchQuerySet(using='whoosh')

sqs = sqs.auto_query('pdf').filter(
    SQ(publicationDate__gte=datetime(year=2016, month=1, day=1),
       django_ct='publique.info') |
    #
    SQ(django_ct='publique.media'))

print sqs.query.build_query()

for i in sqs:
    print i, i.publicationDate
```

```
((pdf) AND ((django_ct:('publique.info') AND publicationDate:([20160101000000 to])) OR django_ct:('publique.media')))
<SearchResult: publique.media (pk=u'6120')> None
<SearchResult: publique.info (pk=u'2865')> 2016-04-06 00:00:00
<SearchResult: publique.media (pk=u'6130')> None
<SearchResult: publique.info (pk=u'2839')> 2016-02-15 00:00:00
<SearchResult: publique.media (pk=u'6123')> None
<SearchResult: publique.media (pk=u'6121')> None
<SearchResult: publique.media (pk=u'6124')> None
```

**Comment by alessandrohc** [comment]
Hi, 

What is the result using only django_ct?

```
print 'only django_ct, removed pub date'
x = SearchQuerySet().auto_query('pdf').filter(django_ct__exact='publique.info')
print x.query.build_query()
print x.count()
```

I still do not understand if the bug is in the filter 'OR' or in the field 'django_ct'

**Comment by acdha** [comment]
Also, does `.models()` work? After very briefly looking at the code in

https://github.com/notanumber/xapian-haystack/blob/de76bad3f05eb7937aefac3f5b0d3ef1d126b526/tests/xapian_tests/tests/test_query.py#L214-L230

and

https://github.com/notanumber/xapian-haystack/blob/de76bad3f05eb7937aefac3f5b0d3ef1d126b526/xapian_backend.py#L48-L52

I was wondering whether this is as simple as needing to use `CONTENTTYPE=`:

https://github.com/notanumber/xapian-haystack/blob/de76bad3f05eb7937aefac3f5b0d3ef1d126b526/xapian_backend.py#L435-L444

**Comment by alexsilva** [comment]
`.models` works yes, but query is quite different from an applied filter.

```
        sqs = SearchQuerySet()
        q = sqs.auto_query('pdf').filter(django_ct='publique.info')
        print q.query.build_query()
        print q.count()

Xapian::Query((Zpdf:(pos=1) AND (CONTENTTYPE^ PHRASE 3 CONTENTTYPEpublique.info PHRASE 3 CONTENTTYPE$)))
0

        sqs = SearchQuerySet()
        q = sqs.auto_query('pdf').models(Info)
        print q.query.build_query()
        print q.count()

Xapian::Query((Zpdf:(pos=1) AND 0 * CONTENTTYPEpublique.info))
28

```

**Comment by alexsilva** [comment]
I was able to solve https://github.com/notanumber/xapian-haystack/pull/166
