### ISSUE TITLE
Documentation with elastic search

### ISSUE THREAD

**Issue by iMerica** [django-haystack/django-haystack#1473]
I'm doing a fresh set up and the following error is displaying:

> .MissingDependency: The 'elasticsearch' backend requires the installation of 'elasticsearch'. Please refer to the documentation.

The documentation does not mention installing the `elasticsearch` for for the elasticsearch backend anywhere. The only installation using pyp is `pip install django-haystack`

Django version: 1.9.7
Python 3.5.2
PIP 9.0.1

**Comment by lucasdavila86** [comment]
The documentation mention the elasticsearch dependency.
https://django-haystack.readthedocs.io/en/v2.6.0/installing_search_engines.html#elasticsearch

You’ll also need an Elasticsearch binding: elasticsearch (NOT pyes). Place elasticsearch somewhere on your PYTHONPATH (usually python setup.py install or pip install elasticsearch).

elasticsearch has its own dependencies that aren’t covered by Haystack. You’ll also need urllib3.

**Comment by iMerica** [comment]
Okay cool. Really liking this tool so far!

**Comment by lwairore** [comment]
Just do 
`pip install pyelasticsearch`
