### ISSUE TITLE
django_ct error with Solr 5.5.4/6.4.1 and Haystack 2.6.0

### ISSUE THREAD

**Issue by elitzer2** [django-haystack/django-haystack#1488]
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behavior

Haystack responds as expected (with an appropriate JSON response) and is able to be queried using a Solr backend

## Actual behavior

500 Internal Server Error: KeyError: 'django_ct'

## Steps to reproduce the behavior

1. Create Django project and add a model
2. You can try using the `build_solr_schema` command, but that produces an output incompatible (deprecated field types) with both Solr 6.4.1 and Solr 5.5.4 (so I basically have been trying to use [this](https://github.com/nazariyg/Solr-5-for-django-haystack) for the schema. I have tried using the schema output from both cases mentioned in both Solr 6.4.1 and Solr 5.5.4 but have not had any luck.
3. I have ensured the `django_id` and `django_ct` are defined as fields but that does not seem to be the issue here. 

I suppose my main question to the community is whether or not anyone has gotten Haystack working with Solr 5.5.4 or Solr 6.4.1? I don't feel we should have to downgrade Solr any further due to lack of new features and for security reasons. Currently in our Django application we are using PySolr directly to query Solr and return JSON. Thanks for your time!

## Configuration

* Operating system version: Ubuntu 16.04.2 LTS
* Search engine version: Solr 6.4.1 and Solr 5.5.4
* Python version: 3.5.2
* Django version: 1.10.5
* Haystack version: 2.6.0

**Comment by acdha** [comment]
I use Haystack with Solr 6.4.1 in production now but I updated my schema independently since it's fairly customized from what `build_solr_schema` produces. That key error really sounds like Solr doesn't have the expected schema, which makes sense given your point 2 so perhaps the real story here is updating `build_solr_schema` to work with Solr 6.

**Comment by elitzer2** [comment]
If I post my schema file would you mind glancing at it and see if you can find anything obvious? It's only about 90 lines or so and most fieldTypes don't ever get utilized but are just in there from the default schema. Not sure if I should post it directly in here or if I should put it in a Gist or something?

**Comment by acdha** [comment]
A gist would probably be good – the main thing is usually looking at the startup log messages since Solr usually logs the configuration fault but not always in the most obvious form

**Comment by elitzer2** [comment]
Ok I can condense it and get rid of the unused fieldTypes just so it's easier to pinpoint.

**Comment by elitzer2** [comment]
Alright here's the schema.xml file (I tried getting rid of fieldTypes I don't specifically use with the `<field>` tags but Solr would complain): https://gist.github.com/elitzer2/7b5694082166006c250392ba04040142 

I don't see anything out of the ordinary in the log messages when I start Solr in the foreground.

**Comment by acdha** [comment]
Can you add the solrconfig.xml as well? I'll try to take a look at this later today – I got a couple of errors loading it which might be artifacts of my local setup.

**Comment by acdha** [comment]
Anyway, one other note: the error message makes me think something has gone wrong in the schema config. If you look at the admin panel (e.g. localhost:8983) for your core I would confirm that the expected django_ct and django_id fields are present and that there aren't any obvious errors. I would also try to run the query directly (starting with just copy and and pasting it from the query log) to see what data is returned and especially whether there's an error message which should be handled.

**Comment by elitzer2** [comment]
Here's the solrconfig: https://gist.github.com/elitzer2/848ee001218068ef96926ca5db72a299

FYI I am using the DataImportHandler to import from a MySQL database.

**Comment by elitzer2** [comment]
I confirmed the django_ct and django_id fields are both present in the Schema Browser in the admin panel. If I use the query panel in the admin panel that queries the data just fine. But it doesn't return django_ct or django_id, I don't believe it's supposed to though? I am not entirely sure what those two things are for and how they are used?

**Comment by acdha** [comment]
Those two fields are what Haystack uses to retrieve the corresponding model – that's the Django content type and primary key – which is why you're getting that weird error since those are always present normally. Haystack should be sending in queries with those in the field list unless that's been customized in the settings (http://django-haystack.readthedocs.io/en/v2.6.0/settings.html#haystack-django-ct-field).

**Comment by elitzer2** [comment]
I haven't changed anything in the settings. Any suggestions for other things I can look at?

**Comment by elitzer2** [comment]
Should Solr be sending haystack back JSON that includes the django_ct and django_id fields? Where do those two fields get populated in Solr? Should they be copy fields?

**Comment by acdha** [comment]
Yes - those fields are populated by haystack during the indexing process

**Comment by elitzer2** [comment]
So Solr is doing the indexing, is it not? I am indexing Solr from its admin interface using the DataImportHandler. Is this not the way to do it when connecting with haystack?

**Comment by acdha** [comment]
Ah, okay, that's probably the source of the problem: when you run `update_index` or `rebuild_index`, Haystack generates the document which is inserted into Solr (see http://django-haystack.readthedocs.io/en/v2.6.0/tutorial.html#reindex, http://django-haystack.readthedocs.io/en/v2.6.0/searchindex_api.html, etc.). 

That includes generating the document field using a Django template (which can combine tons of different fields) and it generates the two fields it needs to be able to retrieve a database model from the search result when you access the `.object` accessor (by default, that's `django_ct` (which is just the  Django content-type value as a string – e.g. “myapp.mymodel” by default) and `django_id`, which is the primary key) and to be able to detect stale records in the index which are no longer in the database or vice versa.

If you're using a direct import from a SQL database, at the very least you'll need to either populate a field named `django_id` or set `HAYSTACK_DJANGO_ID_FIELD` in your settings to the name of the primary key field. `django_ct` is similar, although you could do something like simply have a query like `SELECT 'myapp.mymodel' as django_ct`, …`.

**Comment by elitzer2** [comment]
Ok I thought those were just convenience commands. Creating a search_indexes.py and using the `rebuild_index` command seemed to populate Solr with the `django_ct` and `django_id` fields. Does it seem to run slower than it would using just the Solr admin interface?

**Comment by acdha** [comment]
Yes - it's doing more processing so it will definitely be slower. If you really need the performance, there's nothing wrong with loading data yourself but you'll need to make sure it matches what Haystack assumes. I believe that'll be just the `django_ct` / `django_id` fields but this isn't a common configuration.

**Comment by elitzer2** [comment]
Ok sounds good. We will have 50+ million rows and when testing I was indexing 1 million and it already felt super slow. Now I need to figure out Pagination with Tastypie.

**Comment by acdha** [comment]
That's definitely enough records to consider optimization. The default Haystack indexing process allows customization per-field and renders a Django template for the document which is definitely going to be a lot of extra work if you don't need anything other than the values directly from the database

**Comment by elitzer2** [comment]
This is more a sidenote and not sure where to ask this question but does Haystack not support regex matching like the Django ORM does?

**Comment by acdha** [comment]
No - that was previously not supported by the backends but apparently could be now at least on the Lucene 4+ engines.

**Comment by elitzer2** [comment]
I'm a little confused, you say no then you say it is in Lucene 4+? Maybe I worded my question incorrectly? So Haystack does support regex if using the latest Solr?

**Comment by elitzer2** [comment]
I can't find anything in the Haystack docs about support for regex sub-string matching.

**Comment by acdha** [comment]
Haystack cannot support something which the backends don't implement. Solr
and ElasticSearch use Lucene so they apparently couldn't have supported it
prior to upgrading to Lucene 4, which is why Haystack doesn't have support.
If they now have it we could implement that now.

**Comment by elitzer2** [comment]
Ah ok, I understand. Yeah regex support is one reason why we are currently using PySolr directly.

**Comment by acdha** [comment]
My preference long-term is that we start exposing the clients directly for any feature which can't be supported by most of the backends since most of the point to the ORM-like interface is portability.

**Comment by RabidCicada** [comment]
I've handled this with https://github.com/RabidCicada/haystack_solr6.
Specifically Check the schema file is appropriate (It's been updated in my repo there)
And Make sure you name the files corretcly for django-haystack and handle all the django configuration details correctly.  The "Failures in build_solr_schema or the curl command (Error 500 etc) or uses of solr itself" section of my readme should be helpful.

On this note...Would haystack be up for an upgrade of the default supported solr and build_solr_schema stuff?  We could integrate the new template from my repo as the default for haystack and change the name that build_solr_schema looks for to the more expected schema.xml vs the solr.xml?

I would be happy to edit and provide the PR to fix this as I have already done so to get solr6 working

**Comment by acdha** [comment]
I think it would make sense to change the default to the current version of Solr and assume that anyone with a an Solr has already deployed and almost certainly customized that configuration.

**Comment by RabidCicada** [comment]
Should I open a new issue, or just provide a PR updating to modern solr , or are other people shepherding this?

**Comment by SalahAdDin** [comment]
@RabidCicada, you are awesome.

**Comment by acdha** [comment]
@RabidCicada If you have time to work on it, a pull request would be great. My availability is somewhat limited these days.

**Comment by RabidCicada** [comment]
I will do that....I already have a proper schema.xml written up.  I'm working on the part for orchestrating solr server control so we can slot in the solrconfig.xml, the test_haystack stuff up to 6 and all the other gory stuff I can think of.

Is there anyone else reviewing PR's and issues?...it seems like a bit of a zombieland currently.  Anyone I can ping directly?...I'd like to be more actively involved but fear work will sit idly in the queue.

**Comment by SalahAdDin** [comment]
@RabidCicada, many people are wating fot this, but i think no one have a good capabilities with python, so, at least me, i can not help with this great package.

**Comment by RabidCicada** [comment]
Good progress made today.  I've updated a lot of the test_haystack/solr_tests stuff to work with solr 6.4.0.  I've got start_solr_test_server.sh completely ported I think, with a compatible schema.xml and solrconfig.xml .  All solr tests run and I get 6 failures, at least some of which are management command related (makes sense because I haven't even attempted to port that yet.

I will dig into individual tests and rework the management commands sometime soon.  They will need to be updated for solr6's _style_ :)

My WIP branch is here https://github.com/RabidCicada/django-haystack/tree/solr6_template_upgrade

**Comment by elitzer2** [comment]
This is great @RabidCicada look forward to trying it once it's merged in!

**Comment by RabidCicada** [comment]
Work is progressing.  I'm having problems with Travis.  All tests pass locally with python 2.7-3.5 completely.  But on Travis I'm getting errors in my new code for spelling_suggestions.  I don't understand how/why travis is screwing up.  I'm running on 16.04 but all the relevant bits are python, java, django, and solr.  So...still troubleshooting the Travis problem.

I have all tests passing now on my branch https://github.com/RabidCicada/django-haystack/tree/solr6_template_upgrade.

I still have to upgrade the management command build_solr_schema to plop in the solr 6 schema and switch to classic schema style.  But other than that...all tests run and complete 100%.

Still working to figure out the descrepancy with Travis and my local env.  If anyone wants to take a look please do.

**Comment by RabidCicada** [comment]
Ok...on my machine all the results in raw_results.spellcheck.get('collations', []) are a dict...but on travis they are all lists.  I'm wondering if that's due to pysolr?...as the same code is running on my machine for haystack itself

**Comment by RabidCicada** [comment]
Ok...the raw_response from pysolr IS different on travis than on my machine...gotta figure out why now.

Local Machine: Raw Response: {u'spellcheck': {u'correctlySpelled': False, u'collations': {u'collation': {u'hits': 3, u'collationQuery': u'(index)', u'misspellingsAndCorrections': [u'indexi', u'index']}}, u'suggestions': {u'indexi': {u'origFreq': 0, u'numFound': 1, u'suggestion': [{u'freq': 3, u'word': u'index'}], u'startOffset': 1, u'endOffset': 7}}}, u'responseHeader': {u'status': 0, u'QTime': 1, u'params': {u'fq': u'django_ct:(core.mockmodel)', u'spellcheck': u'true', u'spellcheck.count': u'1', u'q': u'(Indexy)', u'start': u'0', u'wt': u'json', u'spellcheck.collate': u'true', u'fl': u'* score'}}, u'response': {u'start': 0, u'maxScore': 0.0, u'numFound': 0, u'docs': []}}

Travis: Raw Response: {u'spellcheck': {u'correctlySpelled': False, u'collations': [u'collation', {u'hits': 3, u'collationQuery': u'(index)', u'misspellingsAndCorrections': [u'indexi', u'index']}], u'suggestions': [u'indexi', {u'origFreq': 0, u'numFound': 1, u'suggestion': [{u'freq': 3, u'word': u'index'}], u'startOffset': 1, u'endOffset': 7}]}, u'responseHeader': {u'status': 0, u'QTime': 6, u'params': {u'fq': u'django_ct:(core.mockmodel)', u'spellcheck': u'true', u'spellcheck.count': u'1', u'q': u'(Indexy)', u'start': u'0', u'wt': u'json', u'spellcheck.collate': u'true', u'fl': u'* score'}}, u'response': {u'start': 0, u'maxScore': 0.0, u'numFound': 0, u'docs': []}}

**Comment by RabidCicada** [comment]
Might be onto something....local solr version is 6.5.0 instead of 6.4.0....I think the get-solr-download.py might be wrong.  And we will need to handle both spelling suggestoin formats:
https://issues.apache.org/jira/browse/SOLR-3029
https://issues.apache.org/jira/browse/SOLR-9972
https://github.com/solariumphp/solarium/issues/320

**Comment by RabidCicada** [comment]
The download from http://apache.mesi.com.ar/lucene/solr/6.4.0/solr-6.4.0.tgz is actually solr 6.5.0....sigh
The one that travis got was actually 6.4.0...
Ok...so I'll handle the differences between 6.4.0 and 6.5.0

**Comment by acdha** [comment]
!!! That's a nice little point of confusion – I'd probably report it on the `#solr` channel on IRC

**Comment by webyneter** [comment]
LOL, weird...

**Comment by RabidCicada** [comment]
I'm going to stop hijacking this thread and continue work in another issue #1502

**Comment by RabidCicada** [comment]
For those watching this ticket: PR #1504 has been created.  We're almost there.

**Comment by RabidCicada** [comment]
Solr 6 support has been merged into the mainline.  The build_solr_schema now support two more flags and can configure and reload a core for Solr6.4/6.5 etc.  Please give it a try @elitzer2 .  If this corrects your problems please close out the ticket.  Thanks!

**Comment by SalahAdDin** [comment]
Are there new documentation here?

**Comment by acdha** [comment]
@SalahAdDin Yes - see the commit for the changes and http://django-haystack.readthedocs.io

**Comment by RabidCicada** [comment]
Hey @acdha, that link looks to have out of date docs with the Mainline.....do the know how readthedocs is supposed to work

**Comment by RabidCicada** [comment]
Ahhh...just add latest to the URL...http://django-haystack.readthedocs.io/en/latest/

**Comment by SalahAdDin** [comment]
@RabidCicada But there aren't section for `2.6.7` version.

**Comment by acdha** [comment]
That build tracks the contents of the `master` branch. We do need to prune the list of links to older versions before release, which is part of why there hasn't been a release yet, but the master build on readthedocs.io should be current to within a few minutes.
