### ISSUE TITLE
django-haystack filters on several models

### ISSUE THREAD

**Issue by hubert10** [django-haystack/django-haystack#1494]
I have been trying to implement haystack filters on multiple models with elasticsearch as a search backend but it does not work. 
I want to be able to filter users according to their skills, positions etc
Here are my indexes:
I have two models search_indexes.py

    class PersonSkillIndex(indexes.SearchIndex, indexes.Indexable)
         text = indexes.CharField(document=True, use_template=True)
         person_name = indexes.CharField(model_attr='person_id')
         skill_name = indexes.EdgeNgramField(model_attr='skill_id')
         autocomplete = indexes.EdgeNgramField()

         @staticmethod
         def prepare_autocomplete(obj):
         return " ".join((obj.skill_id.name))

         def get_model(self):
         return PersonSkill

         def index_queryset(self, using=None):
         return self.get_model().objects.all()

         def prepare_person_id(self, obj):
         return obj.person_id.name

         def prepare_skill_id(self, obj):
         return obj.skill_id.name`

    class PersonPositionIndex(indexes.SearchIndex, indexes.Indexable):
        text =   indexes.CharField(document=True, use_template=True)
        person_name = indexes.CharField(model_attr='person_id')
        position_name = indexes.EdgeNgramField(model_attr='position_id')
        autocomplete = indexes.EdgeNgramField()

       @staticmethod
       def prepare_autocomplete(obj):
       return " ".join(( obj.position_id.title))

       def get_model(self):
       return PersonPosition

       def index_queryset(self, using=None):
       return self.get_model().objects.all()

       def prepare_person_id(self, obj):
       return obj.person_id.name

       def prepare_position_id(self, obj):
       return obj.position_id.name`

 I want to search in both PersonSkill and PersonPosition models with the following searchQuerySet:
`http://localhost:8000/en/api/profiles/search/?skill_name=python&position_name=programmer`
Does Haystack filters support this functionality? if yes, Any suggestion will be welcomed!

**Comment by wh836627932** [comment]
Please find a solution without I filtering has been also want to do

**Comment by acdha** [comment]
That query is saying `skill_name=python` AND `position_name=programmer` and no single record will have both. You need to use `SQ` objects, which are similar to `django.db.models.Q`:

http://django-haystack.readthedocs.io/en/v2.6.0/searchquery_api.html#sq-objects
