### ISSUE TITLE
[question] Count documents originating from a model

### ISSUE THREAD

**Issue by webyneter** [django-haystack/django-haystack#1501]
First, I'd like to thank `django-haystack` developers for the awesome product!

I wonder, if it's possible to count documents originated from a particular model? I use `haystack` `2.6.0` and `Solr` `6.5` as a searching backend.

Any suggestions/clues are much appreciated.

**Comment by acdha** [comment]
The simple case would be something like `sqs.models(…).count()`. Unfortunately, due to the differences in backends Haystack doesn't have the equivalent of Django's annotation or aggregation so there isn't a portable way to get a count broken down by _each_ known model using a single query.

**Comment by webyneter** [comment]
@acdha, thanks!
