### ISSUE TITLE
Upgrade to 6.X Solr

### ISSUE THREAD

**Issue by RabidCicada** [django-haystack/django-haystack#1502]
This is a continuation of #1488.

This is for all questions that arise during port.

Or particular interest at the moment:
I'm interested in feedback on upgrading the behavior of spelling suggestions.  Currently it looks like we only return a single result.  I feel this is next to useless other than the collation query.

For the initial port I'm looking to maintain backwards compatibility which looks like returning a SINGLE suggetion with collation results overriding suggestion results (whole query suggestion vs single word suggestion)...but I'm plumbing for future returning all results in a reasonable format.  Does anyone have any input on what data to pass forward?

**Comment by RabidCicada** [comment]
Good news Everyone https://i.ytimg.com/vi/YRCzEqkCoiM/maxresdefault.jpg

All tests passing.

Note of interest: with our default behavior...we never test just the suggestion portion...it always returns a collation.  This is because we pass spellcheck.collate=True with every spellcheck.  This is how it was done previously...but means that we don't EVER test the suggestion spellcheck...only the collate spellcheck.

I plan to change this in the future.  I also would like to return a sensible multiresult in the future ( I preserved what I though was current behavior where we only return one result and only collate if both collate and suggestions are provided)

We now support 6.4.0 and 6.5.0 api wise.

I still need to implement the build_solr_schema...I think later today and the initial port effort is done.
https://github.com/RabidCicada/django-haystack/tree/solr6_template_upgrade

**Comment by RabidCicada** [comment]
I'm currently wrangling with details involving level or responsibility for the command (philosophical crap).  I'm designing the command to take an output 'configure_dir'.  The command will have the same search_configuration/ template directory.  It will also construct the solrconfig.xml from that directory currently feeding the template engine the same context that it feeds the schema.xml.  I'm considering just taking all *.xmls under the search configuration directory and running them through the template engine and dumping them into the configure_dir output directory.

The reason we need solrconfig.xml now is to enable ClassicSchema Factory stuff and disable DynamicFieldHandlers.  In addition there's a defaults field that we should template to play nicely.

This would allow anyone to template in ANY of the config files now using the existing context info (admittedly not very useful outside of schema.xml and solrconfig.xml at the moment -- but future proofing?). 

As it stands I will either:

- Render all xml files through the template engine and into configure_dir then use connections[using].get_backend().reload() to reload the core.

- Only render solrconfig.xml and schema.xml through template engine and into configure_dir then use connections[using].get_backend().reload() to reload the core.

Any advice or design decision...or third option @acdha ?

**Comment by RabidCicada** [comment]
Also...I will force our tests to actually use spelling suggestion without collation in addition to current (with collation) behavior to exercise more pieces.

**Comment by RabidCicada** [comment]
Alright...well that was much more than I expected in terms of effort.
I have full template management and solr configuration working on a quick local test.  Running through Travis now.

Couple observations and questions:

- So, pysolr is outdated..it passes get params for SolrCoreAdmin in the data= argument which solr doesn't like.
- I still need to make the changes to support testing just spelling suggestions without collations (not done yet)
- I saw your comment about adding spaces and using full words...and now it's dissappeared..I can't find that comment...it doesn't seem attached to my own repo or the parent one or any issues....I have the email alert from it...but can't find the actual comments on github (help?)
- I tried to leave the current filename argument functionality alone to not break old stuff.  I implemented a new command configure_dir and another reload which can be used in conjunction to have one-shot reconfig and run :).
- Please go through and be ruthless with your review of things.  I'll try to fix as much as possible.  It think Solr fans will be very happy when this lands.

**Comment by acdha** [comment]
pysolr can definitely use some updates – the upstream formats have been changing a lot over the years so we're probably just going to need to accept a broader test matrix. One of the things which would probably make sense is pivoting both pysolr and haystack over to using the official Docker images so we could at least minimize the amount of work needed to deal with the basic configuration, startup, etc.

Did you rebase your repo? That'd break any comments on old commits. If you think this is ready, let's move the discussion to a pull-request and I can start a code review.

**Comment by RabidCicada** [comment]
I didn't rebase anything to my knowledge.  I'm not an expert but I'm also not brand new so no rebasing occured.

I'll take another day or two before going there.  Looks like I have a little more to do.  I'll put in your suggestions from before (thanks to email) and do the spelling suggestions footwork.

**Comment by RabidCicada** [comment]
Also agreed in particular about the docker statement.  I'm just too new here to want to try to step on more than I already have:)  I started using docker on my home project for the same reason.

**Comment by acdha** [comment]
I just hit the spellcheck issue while updating my own project to Solr 6.5 and am now wondering whether I should “steal” https://github.com/RabidCicada/django-haystack/commit/b356097a55d463f62ba00c0f9dc3a5650cc969d8 into a separate commit since it's relatively isolated.

**Comment by RabidCicada** [comment]
I just checked in the part that checks spelling suggestions without collation.  I've added a collate parameter to solr_backend.py's build_search_kwargs.  Which is passed to by many different entry points.

I have all tests passing on travis for everything now.

At this point I'm throwing pep8 at the whole thing and then I'll be ready for a pull request.

https://github.com/RabidCicada/django-haystack/tree/solr6_template_upgrade
https://travis-ci.org/RabidCicada/django-haystack/builds/223314570

**Comment by RabidCicada** [comment]
Alright....it's pretty much ready to go I believe...I need to update documentation though to reflect the new command options

**Comment by acdha** [comment]
Awesome, thanks!

**Comment by RabidCicada** [comment]
Hella sick this weekend.  I will be nibbling at this as I feel better through the week.

**Comment by RabidCicada** [comment]
Looks like this is done...Cosing out:).
