### ISSUE TITLE
update_index's batched slice re-queries are very slow with large OFFSETs

### ISSUE THREAD

**Issue by ggaughan** [django-haystack/django-haystack#1514]
As mentioned in issue #1077, running `update_index` against millions of rows (with multiprocessing and lots of database memory) I also saw it get progressively slower with mysql (innodb), only handling a few million after several days.

The `update_index` batching method (whether using multiprocessing or not) gets slower and slower because naive offsets (LIMITs) are used (this is the same issue that cripples almost all paginations of large datasets - see http://use-the-index-luke.com/no-offset).

The loop to split the queryset into batches uses `start:end` slices on a lazy queryset which issues a full re-query and sort of ALL rows (at full-row width) for *every* batch (default = 1000 rows) and then the db-server has to page through the results to find the next offset. For datasets that don't fit into the database cache this will effectively:

 * flush out all other users' data
 * waste i/o sorting the whole queryset
 * waste i/o paging in and out through the leading portion of the results every time, getting progressively slower as the offset increases

I've implemented an alternative approach which:

 * avoids the sort by using the covering index to partition the table
 * avoids the initial count (which I think also makes the partitioning more robust, especially for mysql)
 * partitions the batches into ranges of primary keys that can be located instantly via the index without re-sorting and re-reading any of the batch records

I haven't got round to looking at adding a unit test to show the benefits, but my code is here:

  https://github.com/ggaughan/django-haystack/tree/scalable_update_index

**Comment by acdha** [comment]
This seems like a nice win – if you have time to wrap it into a pull-request, it'd be good to confirm test coverage.

**Comment by ggaughan** [comment]
Well #1517 should do it, but Travis seems stuck...

**Comment by wetneb** [comment]
I think this is stale, offsets no longer seem to be used. However, there is still a `COUNT` query that is used to report the number of objects to update, and even that is impractical in my case. Using the largest pk is much more efficient.

**Comment by acdha** [comment]
@wetneb If you want to send a PR that might be helpful — it's not just the logging line but also the code which chunks the update batches so you might need to rewrite that loop to keep reading blocks until it gets one which is smaller than the block size. I'm thinking that could be a separate issue.
