### ISSUE TITLE
./manage.py build_solr_schema get 'TypeError'

### ISSUE THREAD

**Issue by Landver** [django-haystack/django-haystack#1519]
* [yes] Tested with the latest Haystack release
* [no] Tested with the current Haystack master branch

## Expected behaviour
![1](https://user-images.githubusercontent.com/15925657/27179178-1bbfe8da-51d6-11e7-8aca-121e351f3dcc.PNG)

## Actual behaviour
![2](https://user-images.githubusercontent.com/15925657/27179198-36f23996-51d6-11e7-8348-6a609a2a0cbd.PNG)

## Steps to reproduce the behaviour

python 3.5
I think that's enough, because there is problem with syntax in file build_solr_schema.py

## Solution to the problem

change the code in site-packages\haystack\management\commands\build_solr_schema.py
If you can't find that file, then search for 'build_solr_schema.py' where located all your python libraries.

How it was :
```
    def build_context(self, using):
        backend = connections[using].get_backend()

        if not isinstance(backend, SolrSearchBackend):
            raise ImproperlyConfigured("'%s' isn't configured as a SolrEngine)." % backend.connection_alias)

        content_field_name, fields = backend.build_schema(
            connections[using].get_unified_index().all_searchfields()
        )
        return Context({
            'content_field_name': content_field_name,
            'fields': fields,
            'default_operator': constants.DEFAULT_OPERATOR,
            'ID': constants.ID,
            'DJANGO_CT': constants.DJANGO_CT,
            'DJANGO_ID': constants.DJANGO_ID,
        })
```
How it must be:

```
    def build_context(self, using):
        backend = connections[using].get_backend()

        if not isinstance(backend, SolrSearchBackend):
            raise ImproperlyConfigured("'%s' isn't configured as a SolrEngine)." % backend.connection_alias)

        content_field_name, fields = backend.build_schema(
            connections[using].get_unified_index().all_searchfields()
        )
        Context = {
            'content_field_name': content_field_name,
            'fields': fields,
            'default_operator': constants.DEFAULT_OPERATOR,
            'ID': constants.ID,
            'DJANGO_CT': constants.DJANGO_CT,
            'DJANGO_ID': constants.DJANGO_ID,
        }
        return Context
```
## Configuration

* Operating system version: Ubuntu 16.04.2 LTS (GNU/Linux 4.8.0-54-generic x86_64)
* Search engine version: solr 4.10.2
* Python version: 3.5
* Django version: 1.11.1
* Haystack version: 2.6.1

**Comment by acdha** [comment]
Django 1.11 isn't supported yet. Feel free to open a pull request with your changes to confirm that they don't break supported versions.

**Comment by acdha** [comment]
Did you test this with the current master branch of haystack? `build_solr_schema` runs as expected on Django 1.11.2 on Python 3.6.1.

**Comment by Landver** [comment]
"Did you test this with the current master branch of haystack?"
Sorry, I did mistake to post issue here, I'm not using master. In master there is another code in script.
django-haystack I installed **via pip** haystack 2.6.1
So via pip I got another data. What we will do next?

**Comment by acdha** [comment]
You can either install the current master branch or use a version of Django which is compatible with 2.6.1 until the next release.
