### ISSUE TITLE
Missing django 1.11 support

### ISSUE THREAD

**Issue by kvdveer** [django-haystack/django-haystack#1529]
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour

Be able to install most recent django(1.11.3) with django-haystack

## Steps to reproduce the behaviour

I have not been able to reproduce this with `pip`, but I have an application that uses setuptools to depend on versions of django 1.11.3 and django-haystack 2.6.1. `python setup.py develop` triggers:

`error: Django 1.11.3 is installed but Django<1.11 is required by {'django-haystack'}`

This is caused by a too restrictive dependency in setup.py. In the master branch this was (probably accidentally) fixed, but no release has been done to include this..

## Configuration

* Operating system version: Ubuntu 16.04
* Search engine version: None in play yet
* Python version: 2.7, 3.5, 3.6
* Django version: 1.11.3
* Haystack version: 2.6.1

**Comment by acdha** [comment]
This is fixed in the current master branch but has not yet been released. If you have time to test that would be appreciated.

**Comment by dgabrielson** [comment]
+1.  This was problematic for me because the documentation clearly states "a supported version of Django" and points to https://www.djangoproject.com/download/#supported-versions which clearly indicates that 1.11 is currently supported (released April 4, 2017).

**Comment by kvdveer** [comment]
I have run my product's unittests and acceptance tests with Django 1.11.3 and haystack 2.6.1, and found no problems. My software only has trivial Haystack usage, though, so that's not a high bar.

[travis](https://travis-ci.org/django-haystack/django-haystack/jobs/251205560) also signed off on that combination. 

Django's change log doesn't really mention many changes relevant to Haystack (to my eyes, anyway). Given that and both my CI and Travis both signed off, I'd say that doing a release right now (current master) would be a safe thing to do.

**Comment by RabidCicada** [comment]
@dgabrielson You are right...we're a little behind in keeping on top of new releases.  Sorry about that.  Perhaps we should mention explicitly all the version we are testing against by name in the docs...instead of pointing to a resource not under our control?  Either way...if you scope out the travis link...you can see what is actively working on the master branch:https://travis-ci.org/django-haystack/django-haystack#.  Not a solution...just a workaround

**Comment by kvdveer** [comment]
The Travis link tells us Django 1.11 is supported, but the version on Pypi doesn't actually support it. Hence my request to do a release of current master. As far as I can see, there's no indication that that would be a bad idea.

**Comment by RabidCicada** [comment]
My statement about moving "supported versions" to a resource we control was directed at @acdha.  That way people wouldn't fall into the trap you did.

I am not in charge of releases (or indeed a direct dev on django-haystack).  I agree django-haystack seeing an official release soon would be nice.  In the meantime...you could install directly from github with a pip requirements syntax of : `git+https://github.com/django-haystack/django-haystack@<TagName>#egg=django-haystack` to pull it in.  Again not a solution you are looking for...but a workaround to make it less painful.

I did notice that pypy tests started ALL failing relatively recently..but it looks to be a travis configuration problem not related to something changing in django-haystack.

**Comment by acdha** [comment]
I just tagged a 2.7.dev0 release to be easier to test with:

https://pypi.python.org/pypi/django-haystack/2.7.dev0

Haystack could definitely use a release manager or other help getting new versions out - my time is fairly limited these days and most of the other core developers have had similar problems.

**Comment by whyscream** [comment]
Please be aware that the 2.7.dev0 release is not tagged on github right now.

**Comment by bigjust** [comment]
the less restrictive setup.py (to include django 1.11) was released to pypi with 2.5.1, so i'm going to close this issue

**Comment by whyscream** [comment]
```
$ pip download django-haystack==2.5.1 --no-binary :all:
Collecting django-haystack==2.5.1
  Using cached django-haystack-2.5.1.tar.gz
  Saved ./django-haystack-2.5.1.tar.gz
{...]
$ tar -xzvf django-haystack-2.5.1.tar.gz 
django-haystack-2.5.1/
django-haystack-2.5.1/AUTHORS
[...]
django-haystack-2.5.1/setup.cfg
django-haystack-2.5.1/setup.py
$ grep -C2 Django django-haystack-2.5.1/setup.py
install_requires = [
    'Django>=1.8',
    'Django<1.11',
]
--
[...]
$
```

This dependency specification is not always handled correctly by pip (and fixed in #1555), but there is only 1 release that allows django 1.11 (i.e. `Django<1.12`), and that is 2.7.0.dev0. Could you please do a non-dev release before closing this bug?

**Comment by whyscream** [comment]
@bigjust or @acdha  Could you please answer my questions? If there needs work to be done before creating a stable release that supports django 1.11, we'd be happy to put in some work, but it seems travis seems to think everything is working as expected?

**Comment by acdha** [comment]
There hasn't been much testing with 1.11. The best way to get a non-dev release would be to help with that and confirm that it's safe to release 2.7.0.

**Comment by RabidCicada** [comment]
IF it helps...I've been running with django dev/git head for a while.  Everything looks good so far.  But I'm not using it "intensively".  Just using it and it's search feature for low traffic stuff
