### ISSUE TITLE
Order of INSTALLED_APPS is in documentation is wrong

### ISSUE THREAD

**Issue by allcaps** [django-haystack/django-haystack#1533]
At http://django-haystack.readthedocs.io/en/latest/tutorial.html#add-haystack-to-installed-apps it reads:

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',

    # Added.
    'haystack',

    # Then your usual apps...
    'blog',
]
```
But the order of the installed apps is wrong. The order should be: local apps, third party apps, Django apps. Like this:

```
INSTALLED_APPS = [
    # Local apps
    'blog',

    # Third party apps
    'haystack',

   # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
]
```

This is important when overriding templates, static files, management commands and translations. Your local app should take precedence.

From https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-INSTALLED_APPS last paragraph:

> When several applications provide different versions of the same resource (template, static file, management command, translation), the application listed first in INSTALLED_APPS has precedence.

**Comment by Aniket-Singla** [comment]
+1

**Comment by acdha** [comment]
The Django tutorial changed the ordering at some point after the documentation was written but it doesn't matter for Haystack since we're not trying to override the built-ins. Feel free to send a pull request updating the documentation.
