### ISSUE TITLE
Search (ala SearchView) doesn't work with UUID pk's(Non Int pk's in general)

### ISSUE THREAD

**Issue by RabidCicada** [django-haystack/django-haystack#1543]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour
You could use UUID pk's for models in django.  Setup a SearchView and it all works.

## Actual behaviour
You can see the number of results with sqs.all().count() in for example your SearchForm Class.  But the moment you try to instantiate and get all the results...it evaporates.  No results available when you try to iterate over the list.

## Steps to reproduce the behaviour

1.Use UUID's as primary keys on django models that are indexed
2.Create a SearchView and SearchForm that use the Model.
3.Try to use the sqs in the html template through object_list OR a paginated result set (page_obj.object_list)

## Configuration

* Operating system version:Ubuntu 16.04
* Search engine version:6.5
* Python version:3.5.2
* Django version:1.11.4
* Haystack version:master branch and earlier

## Root Cause Analysis
Still in process but it looks like post_process_results of query.py:SearchQuerySet tries to force an int() conversion on the pk causing a problem...or it's involved somehow.  resulting in every result being discarded as an ignored result silently

Still working out the exact nature.

This took me forever to figure out.  I thought I had it working before...I don't know what changed to make it stop.

**Comment by RabidCicada** [comment]
Going to work on a PR to fix as soon as I finish detailed root cause

**Comment by RabidCicada** [comment]
I am correct.  The problem lies in assuming all the keys can be coerced to ints (in otherwords assuming that all primary keys are ints if they are not strings).

I am looking into the proper way to handle this.

Initial thought was to initialize the class type from the first key we can pull out of the database (2.x and 3.x python compatible):
```
for result in results:
            if self._load_all:
                result_klass = None
                # We have to deal with semi-arbitrary keys being cast from strings (UUID, int, etc)
                # devine type on first try.
                model_objects = loaded_objects.get(result.model, {})
                if result.pk not in model_objects:
                    if result_klass is None:
                        result_klass = type(next(iter(model_objects)))

                    try:
                        result.pk = result_klass(result.pk)
```

The problem is that you can have multiple models.  I need to map the indexed model type to the class and do a lookup.  Thinking about the best way to go about this.

**Comment by RabidCicada** [comment]
I am incredibly surprised that the rest of django-haystack worked and regular search did not when I was using UUID's.

**Comment by RabidCicada** [comment]
@acdha I'd appreciate any guidance or insight about how you might think to solve this.  I'll be hacking away over the coming spare time snippets I get to fix this.

**Comment by RabidCicada** [comment]
At second look...That looks like it will solve it properly.  Though looking at the surrounding code I'm suspicious of performance, my fix only adds a O(constant) performance overhead with a couple lines.  I just need to add some tests to prevent UUID's breaking again.

This brings up a design decision discussion.  What primary keys should django-haystack allow?  Django allows a pretty wide range of primary id's.  I don't know about the full swath of our supported db's.  I'm happy enough with UUID+str+int.  And I probably wont invest a lot of work beyond getting the UUID's working...but perhaps it's something to think about.

Now that I've looked through and breadcrumb debugged so much of the code I feel like there's performance improvements to be made.  There is a lot of mapping and stuff going on that I feel could be avoided.

**Comment by RabidCicada** [comment]
It'll also need to be fixed for the NON load_all path.  I haven't even looked at that yet.

**Comment by RabidCicada** [comment]
Already begun work [here](/RabidCicada/django-haystack/tree/uuid-pk-fix)

**Comment by acdha** [comment]
@RabidCicada I think the int/uuid covers the vast majority of users but there might be an argument for thinking about how hard it would be for someone else to add a new type and seeing if there's a reasonable way for us to make that easier. My general preference would be to worry less about covering every use-case in favor of making it easier to override things if you find yourself with an unusual need.

Thanks for digging into this!

**Comment by RabidCicada** [comment]
Ok...Looked further into it.  Looks like the fix I already did is all we need.

The non load-all path goes through SearchResult:_get_object(self) which calls:
`self._object = self.searchindex.read_queryset().get(pk=self.pk)`

That constructor alone achieves the same polymorphism for construction via 'pk=' that I do for our mapping stuff in the other spot.

I'll see about adding a search test using the UUIDModel contributed previously.  After that we should be good to go.

**Comment by RabidCicada** [comment]
Trying to get tests fully passing.  Ran into one weird problem locally where solr tests would fail on 
```
FAIL: test_related_load_all_queryset (test_haystack.solr_tests.test_solr_backend.LiveSolrSearchQuerySetTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dev/django-haystack/test_haystack/solr_tests/test_solr_backend.py", line 1061, in test_related_load_all_queryset
    self.assertEqual([obj.object.id for obj in sqs], list(range(11, 24)))
AssertionError: Lists differ: [] != [11, 12, 13, 14, 15, 16, 17, 1...

Second list contains 13 additional elements.
First extra element 0:
11

- []
+ [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
```

I don't think changes should really have changed those results.  Still testing etc.

**Comment by RabidCicada** [comment]
On the comment of making it easier.  As of right now it should be fully polymorphic for the type.  As long as the text string can be used as a valid constructor from result.pk.

This implies that any type must be coercable TO a string representation and coercable FROM a string representation (as a string argument to constructor).  If it satisfies those...we are good.

The last limiter is the haystack identifier ala HAYSTACK_IDENTIFIER_METHOD

**Comment by RabidCicada** [comment]
@acdha Would you take a look at what I've added and tell  me what I borked?  I don't know why I'm changing the solr related_load_all_querset test yet...but it looks like I really have interfered.

After this I think it's ready to pull in.

**Comment by RabidCicada** [comment]
https://travis-ci.org/RabidCicada/django-haystack/jobs/269609786

**Comment by RabidCicada** [comment]
The following sequence in test_related_load_all_queryset() in test_solr_backend.py is what breaks.  It breaks on the final line:
```
sqs = sqs.load_all_queryset(MockModel, MockModel.objects.filter(id__gt=10))
self.assertTrue(isinstance(sqs, SearchQuerySet))
self.assertEqual(len(sqs._load_all_querysets), 1)
self.assertEqual([obj.object.id for obj in sqs], list(range(11, 24)))
```

It looks like some retrieval method is breaking...still investigating

**Comment by RabidCicada** [comment]
Figured out the issue:
My `type(next(iter(model_objects)))` for divining the pk type was blowing up on the edge case where `sqs = sqs.load_all_queryset(MockModel, MockModel.objects.filter(id__gt=10))` made the post_process_results function get an empty list from self._load_model_objects().  It only happens when the EXACT size of ITERATOR_LOAD_PER_QUERY is perfectly equal to the amount "ignored" by the id__gt part:).

Fixing it now.

**Comment by RabidCicada** [comment]
Hopefully I'll finish this up this weekend.

**Comment by acdha** [comment]
Thanks — I owe you some code review later

**Comment by RabidCicada** [comment]
So I have the final fix in.

I'd really like a better method of getting the pk field type but currently rely on the `type(next(iter(model_objects)))` construct.  I'd rather carry a note about the type around with us to prevent that cost on each and every result of the result set.

But this is what we've got for now.

**Comment by RabidCicada** [comment]
@acdha Heyo.  Would love to see this pulled in soon.  I've got tests and everything!
