### ISSUE TITLE
ajax with django-haystack?

### ISSUE THREAD

**Issue by loopq** [django-haystack/django-haystack#1548]
## Configuration

* Operating system version:
* Search engine version:
* Python version:3.5.2
* Django version:1.11.3
* Haystack version:2.6.1

i have find long time,but nothing is useful.how ajax use with django-haystack?

**Comment by lilboat72** [comment]
3 years later...Do you remember if you found a solution

**Comment by acdha** [comment]
It works like any other use of AJAX with Django: you create a view for the front-end code to call, which takes whatever parameters make sense for your application, uses Haystack to perform the query, and returns the response. There's an example for what this looks like in the autocomplete section of the documentation:

https://django-haystack.readthedocs.io/en/master/autocomplete.html
