### ISSUE TITLE
DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')

### ISSUE THREAD

**Issue by palewire** [django-haystack/django-haystack#1571]
I'm getting the following `setuptools_scm` error when trying to install via the latest version of pip in a virtual environment. As you can see in the code below, setuptools_scm does appear to be installed. I'm trying to figure out why it's not linking up with your library. If you have any ideas, please let me know.

```bash
(himmel.latimes.com)datadesk@himmel:/apps/himmel.latimes.com$ pip freeze | grep setuptools-scm
setuptools-scm==1.15.6
(himmel.latimes.com)datadesk@himmel:/apps/himmel.latimes.com$ python
Python 2.7.3 (default, Aug  1 2012, 05:14:39) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_scm
>>> exit()
(himmel.latimes.com)datadesk@himmel:/apps/himmel.latimes.com$ pip install django-haystack
Collecting django-haystack
  Using cached django-haystack-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    No local packages or download links found for setuptools-scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-do137B/django-haystack/setup.py", line 68, in <module>
        setup_requires=['setuptools_scm'],
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/apps/himmel.latimes.com/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/apps/himmel.latimes.com/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/apps/himmel.latimes.com/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 576, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/apps/himmel.latimes.com/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 821, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/apps/himmel.latimes.com/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 833, in obtain
        return installer(requirement)
      File "/apps/himmel.latimes.com/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 294, in fetch_build_egg
        return cmd.easy_install(req)
      File "/apps/himmel.latimes.com/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 583, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-do137B/django-haystack/
```

**Comment by daxaxelrod** [comment]
pip isnt picking up on it but you can install the package manually

bash`pip install setuptools-scm`

**Comment by acdha** [comment]
What version of pip are people seeing this with? It seems to be not uncommon but there were suggestions that it was due to what is by now a quite old version of pip (https://github.com/pypa/pypi-legacy/issues/322#issuecomment-229131838) so I'm wondering whether updating that would also fix the problem.

**Comment by daxaxelrod** [comment]
hey @acdha, thanks for the response! Im on pip.1 using python 3.7 within a venv

**Comment by ecederstrand** [comment]
This happens if you use a non-standard PyPI repo. pip will use it, but `setup_requires` is handled by `setuptools` which does not respect pip settings. Instead, you are redirected to pypi.org which is not accessible in our environment. I'm fighting with this now. The suggestion to create a `distutils.cfg` file does not work for me.

Is `setuptools-scm` even needed here? I can't see anything in setup.cfg requiring it. #1603 seems to think it isn't.

**Comment by acdha** [comment]
`setuptools-scm` is what provides this option: https://github.com/django-haystack/django-haystack/blob/802b0f6f4b3b99314453261876a32bac2bbec94f/setup.py#L30

**Comment by pawamoy** [comment]
An interesting comment to mention: https://github.com/pypa/setuptools/issues/2385#issuecomment-696147999

> Part of the problem here is that easy_install is deprecated, but in some cases, setup_requires dependencies still rely on it.
However, in late versions of Setuptools (42 and later), setup_requires dependencies are loaded using pip (if available) and pass through any custom indexes.
So the question is - why is pip not being used to install the setup_requires dependencies? What version of Setuptools do you have installed?

So I guess a solution to this is to upgrade setuptools.
