### ISSUE TITLE
facet.date API is gone in Solr 6.6, replaced with facet.range

### ISSUE THREAD

**Issue by yourcelf** [django-haystack/django-haystack#1572]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour

Docs describe date faceting [here](https://django-haystack.readthedocs.io/en/master/searchqueryset_api.html#date-facet).  A query like this:
```
SearchQuerySet().date_facet('date_exact', datetime.datetime(1990, 1, 1), 'NOW', 'year').facet_counts()
```
should return facet counts that include date-based faceting by year.

## Actual behaviour

No date-based facets are returned under Solr 6.6.  The `facet.date` API has been replaced by a more general [`facet.range` API](https://lucene.apache.org/solr/guide/6_6/working-with-dates.html) which supports the same general parameter format, but uses `facet.range` query keys and returns results as `facet_ranges` rather than `facet_dates`.

Currently, the above call to `date_facet` produces these query parameters:

```
facet.date=date_exact
&f.date_exact.facet.date.start=1990-01-01T00:00:00Z
&f.date_exact.facet.date.end=NOW
&f.date_exact.facet.date.gap=%2B1YEAR/YEAR
```
Solr 6.6 requires this instead:
```
facet.range=date_exact
&f.date_exact.facet.range.start=1990-01-01T00:00:00Z
&f.date_exact.facet.range.end=NOW
&f.date_exact.facet.range.gap=%2B1YEAR/YEAR
```

In addition, results are returned under the `facet_ranges` key rather than `facet_dates`, so the [`_process_results`](https://github.com/django-haystack/django-haystack/blob/471706a46d1c0d81ad4be5b8d7fd86d055dbe0f1/haystack/backends/solr_backend.py#L388-L401) method will need to include `facet_ranges` as well.
```
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{},
    "facet_ranges":{
      "date_exact":{
        "counts":[
          "1990-01-01T00:00:00Z",282,
          "1991-01-01T00:00:00Z",428,
          ...
        ],
        "gap":"+1YEAR/YEAR",
        "start":"1990-01-01T00:00:00Z",
        "end":"2018-01-01T00:00:00Z"}},
      }
    }
```
Here is [a commit](https://github.com/yourcelf/django-haystack/commit/aa501c1db462ff8cf51bb25bf8efce91a1095aac) which modifies the solr backend to use `facet.range` instead of `facet.date` for date faceting.  Two issues with that: (1) I don't know if this same approach is compatible to earlier versions of solr, and (2) the results from `facet_ranges` are organized a bit differently from the results from `facet_dates` before, so it isn't backwards compatible to people's code relying on date faceting.  It would be pretty reasonable to re-organize the results to match the object shape for what they looked like in `facet_dates` -- but it might be preferable to just treat this as the range query that it is, perhaps revisiting https://github.com/django-haystack/django-haystack/pull/978.

## Steps to reproduce the behaviour

1. Construct a schema that facets on date fields.
2. Attempt to retrieve facet counts using date-based faceting.

## Configuration

* Operating system version: Ubuntu 16.04
* Search engine version: Solr
* Python version: 3.5
* Django version: 1.11
* Haystack version: 2.7.dev0

**Comment by joshuajonah** [comment]
+1 So are we just stopping Solr compatibility at 5?

**Comment by acdha** [comment]
@joshuajonah Haystack is a volunteer project. If you'd like to see support for this particular feature with newer versions of Solr it looks like a pull request for @yourcelf's commit and/or reviewing #978 would be a good contribution.

**Comment by laborautonomo** [comment]
consider PR #1690

**Comment by frafra** [comment]
PR #1690 has been merged. Is this issue still valid?
