### ISSUE TITLE
Official release compatible with current Django LTS (1.11)

### ISSUE THREAD

**Issue by ipmb** [django-haystack/django-haystack#1574]
## Expected behaviour

I can install the current version of `django-haystack` with the current Django LTS version.

## Actual behaviour

```
$ pipenv install django-haystack Django==1.11.8
Installing django-haystack…
Requirement already satisfied: django-haystack in /Users/pete/.virtualenvs/tmp-n8UXe2BB/lib/python3.6/site-packages
Requirement already satisfied: Django>=1.8 in /Users/pete/.virtualenvs/tmp-n8UXe2BB/lib/python3.6/site-packages (from django-haystack)
Requirement already satisfied: pytz in /Users/pete/.virtualenvs/tmp-n8UXe2BB/lib/python3.6/site-packages (from Django>=1.8->django-haystack)

Adding django-haystack to Pipfile's [packages]…
Installing Django==1.11.8…
Requirement already satisfied: Django==1.11.8 in /Users/pete/.virtualenvs/tmp-n8UXe2BB/lib/python3.6/site-packages
Requirement already satisfied: pytz in /Users/pete/.virtualenvs/tmp-n8UXe2BB/lib/python3.6/site-packages (from Django==1.11.8)

Adding Django==1.11.8 to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches django<1.11,==1.11.8,>=1.8
...
```

## Steps to reproduce the behaviour

```
pipenv install django-haystack Django==1.11.8
```

`pip` will happily install mismatch dependencies, but `pipenv` complains a little louder. It's not clear to me if the only change is updating the `install_requires` in `setup.py` or if there are additional changes required to support Django 1.11 that are not in the current 2.6.1 release.

**Comment by acdha** [comment]
Have you had time to test the current 2.7.dev0 release? I can ship a release quickly but haven't had much time to work on Haystack recently.

**Comment by ipmb** [comment]
I just tested it on the project I'm working on which is using haystack by way of [aldryn-search](https://github.com/aldryn/aldryn-search). It only uses very basic features, but I was able to `rebuild_index`, perform searches and get the expected results. So that's an n=1 worksforme.

**Comment by jedie** [comment]
Confirm: worksforme ;)

**Comment by bhrutledge** [comment]
We're in the process of upgrading to 1.11, and using [pip-tools](https://github.com/jazzband/pip-tools) to manage our requirements. Similar to pipenv, it complains because django-haystack 2.6.1 requires Django<1.11. How can we help get an official 2.7 release?

**Comment by bhrutledge** [comment]
Ah, ignore this: "django-haystack 2.6.1 requires Django<1.11". I misunderstood the output I was seeing.

**Comment by barseghyanartur** [comment]
Several people haved mentioned that it works for them. It makes sense to update tox and schedule a release.

**Comment by acdha** [comment]
I just uploaded 2.7.dev1 to PyPI with the accumulated changes since 2.7.dev0. If I don't hear complaints from anyone in the next couple of days I'll publish that as 2.7.0.

**Comment by dani0805** [comment]
Any plans for supporting Django 2?

**Comment by acdha** [comment]
@dani0805 Pull requests welcome! I don't currently have a project which uses Haystack and Django 2.0 so my time to work on it is limited.

**Comment by dani0805** [comment]
I found https://github.com/django-haystack/django-haystack/pull/1582 and we are now working with it now. So far seems to be working fine.

**Comment by acdha** [comment]
@dani0805 thanks – any bit of help is appreciated

**Comment by jedie** [comment]
> If I don't hear complaints from anyone in the next couple of days I'll publish that as 2.7.0.

2.7.dev1 works fine with django 1.11

**Comment by acdha** [comment]
2.7.0 is on PyPI now.
