### ISSUE TITLE
Faceting on queryset defined by kwarg url parameter

### ISSUE THREAD

**Issue by wilkinj33** [django-haystack/django-haystack#1583]
I'm filtering my queryset based on a category passed via the url, called 'slug2'. The view works correctly and returns results if I use 'SearchView' but returns the following error when using FacetedSearchView:

" for field in self.facet_fields:
TypeError: 'NoneType' object is not iterable"

 Any thoughts?

views.py

    from haystack.generic_views import SearchView, FacetedSearchView
    class categorySearchView(FacetedSearchView):
        form_class = FacetedProductSearchForm
        template_name = 'result.html'
        context_object_name = 'object_list'
        paginate_by = 5

    def get_queryset(self):
        queryset = super(categorySearchView, self).get_queryset()
        m = self.kwargs['slug2'] # slug is passed through within **kwargs
        if m:
            return queryset.filter(category='%s' % m)
        return queryset 
urls.py
    
    url(r'^category/(?P<slug>[-\w]+)/(?P<slug2>[-\w]+)/$', categorySearchView.as_view(), name='category_view')

**Comment by acdha** [comment]
Are you using the legacy class-based views or the newer ones in `haystack.generic_views` based on the Django class-based views? Only the latter set facet_fields – on the legacy views the facet information is set as a `facets` extra context variable.

See https://github.com/django-haystack/django-haystack/blob/ed20e00323a8fa78d8257af0a2bd637c0e9ee1d6/haystack/generic_views.py#L108

**Comment by wilkinj33** [comment]
Yes, I'm using the views within generic_views.py

**Comment by acdha** [comment]
Does your edit mean this issue can be closed?

**Comment by wilkinj33** [comment]
Yes, thanks Chris.
