### ISSUE TITLE
Haystack, Whoosh, or the Whoosh backend has become ridiculously slow?

### ISSUE THREAD

**Issue by kylemacfarlane** [django-haystack/django-haystack#159]
To be honest, the only reason I use Whoosh is because it's easy to setup on both dev and production so maybe I should just upgrade.

Whoosh has always been slow, but queries that would take ~2s when I first started using Haystack and Whoosh (the fork) now take ~10s with the current versions of both. Yet our index has only increased from about 5000 to 6000 products (but it's still only about 9MB). A 500% slow down with only an 80% size increase of the index. Or maybe I've messed something up?

If Haystack + Whoosh was this slow before deployment I never would have put Whoosh on production and it's first on my list to replace. But the question is why has it become so slow?

**Comment by egrubbs** [comment]
Haystack + Whoosh went from 8sec to 0.2sec when I turned off the INCLUDE_SPELLING setting.

**Comment by oscarychen** [comment]
@egrubbs How do you add Whoosh specific configurations from Django Haystack? Is it from the Django settings.py somehow? Could you provide an example?

**Comment by asedeno** [comment]
> @egrubbs How do you add Whoosh specific configurations from Django Haystack? Is it from the Django settings.py somehow? Could you provide an example?

https://django-haystack.readthedocs.io/en/master/settings.html
