### ISSUE TITLE
Error during indexing FacetFields with Haystack 2.8.0 and Django 2.0

### ISSUE THREAD

**Issue by brian-maher** [django-haystack/django-haystack#1595]
* [X ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour

Indexing should complete successfully when running either rebuild_index or update_index.

## Actual behaviour

When running rebuild_index or update_index using Haystack 2.8.0 and Django 2.0, we get the following error:

pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: Exception writing document id periodicals.article.301 to the index; possible analysis error: cannot change DocValues type from SORTED_SET to SORTED for field "publication_abbreviation"]

Which is defined as:

publication_abbreviation = indexes.FacetCharField(model_attr='issue__publication__abbreviation', null=True)

Downgrading to 2.7.0 whilst keeping Django 2.0 resolves the issue, so this appears to have been introduced in 2.8.0.

## Steps to reproduce the behaviour

1. Create a FacetCharField in SearchIndex
2. run rebuild_index

## Configuration

* Operating system version: Ubuntu 16.04
* Search engine version: Sold 6.6.1
* Python version: 3.5.2
* Django version: 2.0.3
* Haystack version: 2.8.0

**Comment by brian-maher** [comment]
Just to add some more notes from my testing.

Indexing with 2.8.0 will work OK if I index with 2.7.0 and then upgrade to 2.8.0.

**Comment by SalahAdDin** [comment]
@acdha It's a strange behaviour.

**Comment by acdha** [comment]
Can you compare the generated schema between the two versions? It sounds like we should confirm and perhaps document a type change if that makes sense.

**Comment by MtzwOsk** [comment]
2.7.0 force installing Django lower than 2.0
