### ISSUE TITLE
[setup.py] Please, add dependency on setuptools in install_requires field

### ISSUE THREAD

**Issue by P-EB** [django-haystack/django-haystack#1604]
Dear developers,

In `haystack/__init__.py`, you do import `pkg_resources`, which is not an install dependency of django-haystack, as `setuptools` is not mentionned as an `install_requires`

This leads to some issues in minimal debian installations, and in testing : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896263 , https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896296

Could you add `setuptools` as an `install_requires` entry in your `setup.py`?

Thanks!

**Comment by coredumperror** [comment]
This has become significantly more important with the removal of setuptools from the Python standard library in 3.12. `django-haystack` cannot be installed on Python 3.12 unless `setuptools` is also installed.

Please either remove the use of `pkg_resources` from the code, or add setuptools as an explicit dependency.

**Comment by cclauss** [comment]
Please retry with the [beta release](https://github.com/django-haystack/django-haystack/releases).

This was dealt with in #1935 but the problem is that we cannot make a new release until our [three pinned issues](https://github.com/django-haystack/django-haystack/issues) are fixed.
* #1935
