### ISSUE TITLE
Update index breaks when using batching

### ISSUE THREAD

**Issue by hornn** [django-haystack/django-haystack#1615]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour
upgrade_index and rebuild_index should index all objects in the database, regardless of batch size.

## Actual behaviour
When batching is used, i.e. when there are more objects than the the batch size
(e.g. 2000 objects and batch size 1000), some objects are not indexed.
This issue was introduced in 2.7.0, after [this](https://github.com/django-haystack/django-haystack/commit/689911bfd47d51936bc3a1227fe4892ebff47741) commit.

## Steps to reproduce the behaviour
This is a little tricky, because it doesn't always reproduce. It happened in our system after we made changes in the database (updates and deletes), so that the default order was no longer based on the pk. Alternatively, it can happen if the model has a default ordering that is different than the primary key.
1. Create a model with default ordering
```
class AModel(models.Model):
  id = AutoField(primary_key=True)
  name = models.TextField()
  class Meta:
    ordering = ['name']
```
2. Create index on the model
```
class AIndex(indexes.SearchIndex, indexes.Indexable):
 name = indexes.CharField(model_attr='name')

  def get_model(self):
    return AModel
```
3. Create X objects
4. Build index with batching less than X
`python manage.py rebuild_index -b X/2`
5. Some objects are not indexed because the ordering in the batching code is not by the PK.

## RCA
This issue was proved by adding logs to update_index.py, in [line 84](https://github.com/django-haystack/django-haystack/blob/master/haystack/management/commands/update_index.py#L84)
```
print("  max pk: %d" % max_pk)
real_max = max([obj.pk for obj in current_qs])
print("  real max pk: %d" % real_max)
```
and running rebuild index with verbosity = 3.
It proved that the `max_pk` is not actually the maximal PK in each batch, and that's why objects can be omitted.
```
 python manage.py rebuild_index -v 3 --noinput

Indexing 2052 X
  max pk: 912
  real max pk: 2052
  indexed 1 - 1000 of 2052 (worker PID: 20042).
  max pk: 1987
  real max pk: 2052
  indexed 1001 - 2000 of 2052 (worker PID: 20042).
  max pk: 2034
  real max pk: 2052
  indexed 2001 - 2052 of 2052 (worker PID: 20042).
```

## Fix
The issue was resolved after adding `.order_by('pk')` to the queryset in [line 69](https://github.com/django-haystack/django-haystack/blob/master/haystack/management/commands/update_index.py#L69)
```
- small_cache_qs = qs.all()
+ small_cache_qs = qs.all().order_by('pk')
```

## Configuration

* Operating system version: OSX, linux
* Search engine version: SOLR 6.2.1, pysolr 3.7.0
* Python version: 2.7.13
* Django version: 1.11.9
* Haystack version: 2.8.1
* Database: Postgres

**Comment by acdha** [comment]
Thanks!
