### ISSUE TITLE
v2.8.1 doesn't create a working schema for solr 4.X

### ISSUE THREAD

**Issue by erez-o** [django-haystack/django-haystack#1617]
when running `build_solr_schema` in the latest haystack (v.2.8.1), the created schema.xml file doesn't work with solr 4.X. The old schema file created in v2.6.1 works fine.

Looking at the generated schema, it has version 1.6 which fits solr 5+ unless I'm mistaken. 

If you wish to support Solr 4.X, I suggest saving the old solr schema template file [v2.6.1](https://github.com/django-haystack/django-haystack/blob/v2.6.1/haystack/templates/search_configuration/solr.xml) in the master branch.

Note - I'm downgrading solr from 6.X to 4.X because the search occasionally returns empty results for no reason, but the behavior isn't consistent enough for me to file a bug report.

**Comment by acdha** [comment]
We should probably just strengthen the documentation to officially deprecate 4.x in https://django-haystack.readthedocs.io/en/latest/installing_search_engines.html.

If you're having problems with search it would be good to confirm that this is actually a bug, as opposed to unexpected but correct results, and fix that. There shouldn't be any reason to favor 4.x at this point.

**Comment by erez-o** [comment]
Successfully upgraded to 6.6.3. Can't reproduce the bug I reported, so I'm closing this.

Regarding solr 6.X docs, I do suggest you take a look at #1608

**Comment by erez-o** [comment]
If it helps anyone, I found the "bug" where the search results returned empty.

It is unrelated to haystack but to supervisord - starting solr 6 instead off solr 4 in the supervisord conf file causes supervisor to constantly restart every second, so solr sometimes returns correct results (when it's up) and sometimes zero results (when it's down). 

At least up until this moment, I see others reporting that supervisor doesn't play nice with solr 6, and no easy fix.
