### ISSUE TITLE
rebuild_index command does not preserve Haystack index's directory permissions

### ISSUE THREAD

**Issue by alunbestor** [django-haystack/django-haystack#162]
The rebuild_index command appears to function by deleting Whoosh's index directory (HAYSTACK_WHOOSH_PATH) and then recreating it, before populating the empty directory with index data. In doing so it does not persist the directory's former file permissions, which can mean that the user running the site process (in an Apache hosted environment, for instance) no longer has write access to the directory or its contents, causing searches to fail with an error.

**Comment by sampeka** [comment]
It's been a long time and a ton of changes since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
