### ISSUE TITLE
Docs inconsistent about supported Elasticsearch versions 

### ISSUE THREAD

**Issue by clairempr** [django-haystack/django-haystack#1626]
The latest documentation gives inconsistent information about supported Elasticsearch versions. 

In the section **Installing Search Engines**, it says

> Haystack currently supports Elasticsearch 1.x, 2.x, and 5.x.

But in the section **Backend Support**, it says 

> Requires: elasticsearch-py 1.x or 2.x. ElasticSearch 5.X is currently unsupported: see #1383.

Which one is correct? I’d really like to upgrade to a newer version of Elasticsearch but I want to be sure of the supported versions first.

**Comment by acdha** [comment]
The first one

**Comment by oliveratutexas** [comment]
I think this issue should be re-opened as the docs on the website still state as much
