### ISSUE TITLE
Docs give a highlight example for Solr but not for Elasticsearch

### ISSUE THREAD

**Issue by higs4281** [django-haystack/django-haystack#1627]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour
Provide working examples for both Solr and Elasticsearch

## Actual behaviour
Only addresses Solr.

## Steps to reproduce the behaviour
visit https://django-haystack.readthedocs.io/en/latest/searchqueryset_api.html#highlight

I couldn't find an issue or PR addressing this, and I thought I could save someone else from digging through ES docs. Addressed in [PR 1628](https://github.com/django-haystack/django-haystack/pull/1628).

**Comment by acdha** [comment]
Thanks!
