### ISSUE TITLE
App server won't start if GDAL library is not setup

### ISSUE THREAD

**Issue by anshul-chhangani** [django-haystack/django-haystack#1631]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour
Setting up GDAL library should be optional, if someone doesn't want to use LocationField

## Actual behaviour

django.contrib.gis.geos.Point import is global in fields.py which depends on GDAL library and it throws an exception: ImproperlyConfigured: Could not find the GDAL library

In the version Haystack 2.8.1 this is a local import in the convert function of the LocationField, which solves the issue.

## Steps to reproduce the behaviour

1. Make sure that GDAL library is not setup for your app, runserver will fail with the above mentioned exception.

## Configuration

* Operating system version:  macOS 10.13.4
* Search engine version: Elasticsearch 5.5.3
* Python version: 2.7.13
* Django version: 1.11.13
* Haystack version: Latest Master from Commit - bbcd038a96a4572bafa7f47bdf9eb0d345a2445b

**Comment by liederer** [comment]
Same problem here. Current master branch, macOS 10.13.6, Elasticsearch 5.6, Python 3.6, Django 2.0.7.

**Comment by fnsne** [comment]
Still unresolved now.
