### ISSUE TITLE
cannot import name connections

### ISSUE THREAD

**Issue by MalikRumi** [django-haystack/django-haystack#1654]
haystack version 2.8.1
Django 2.1.4
Python 3.7.1

## Expected behaviour
That it would import whatever it needs

## Actual behaviour
ImportError: cannot import name 'connections' from 'haystack' (unknown location)

## Steps to reproduce the behaviour

1. Start my app

## Configuration

* Operating system version: Ubuntu 18.04
* Search engine version: simple

I have seen this on SO: https://chat.stackoverflow.com/rooms/106913/discussion-between-sander-van-leeuwen-and-swathi-pantala and https://stackoverflow.com/questions/36123487/importerror-cannot-import-name-connections

Here is my relevant terminal output on that issue:

(staging) malikarumi@Tetuoan2~/Projects/staging/stage2$ pip uninstall haystack
Skipping haystack as it is not installed.
(staging) malikarumi@Tetuoan2:~/Projects/staging/stage2$ pip install django-haystack
Requirement already satisfied django-haystack in /home/malikarumi/Projects/staging/lib/python3.7/site-packages (2.8.1)

I have looked at the source code. Where, for example, I see from haystack.utils import whatever, there is in fact a utils folder there. But I see nothing called 'connections', so the error makes sense to me. Yes, I do have HAYSTACK_CONNECTIONS in my settings file, but then it would be from settings.HAYSTACK_CONNECTIONS, wouldn't it?  Where is this 'connections' and how do I make this import error go away? I got haystack because it was a dependency of django-machina. Your feedback and assistance appreciated.

**Comment by MalikRumi** [comment]
p.s. 
I now see this on line 44 of __init__: 
connections = loading.ConnectionHandler(settings.HAYSTACK_CONNECTIONS)
There are also imports of settings and loading at the top of __init__
But that still doesn't solve my problem.

**Comment by pinksharpii** [comment]
Was there ever a solution to this? I'm having the same problem.

**Comment by MalikRumi** [comment]
Are you on Heroku? If not, sorry, no, I can't help you. As you can see, no one from this project ever jumped on the thread.

**Comment by acdha** [comment]
There’s not really anything I can do with so little information. This is some sort of configuration error — perhaps the dependencies for your search backend are missing? — so I’d suggest working through the install documentation as part of writing down how to reproduce the problem since that’s likely to uncover the missing step.

**Comment by Computersciencened** [comment]
Is there a fix to this issue?

ImportError: cannot import name 'connections' from 'haystack'

Have recently uninstalled haystack via pip.

**Comment by acdha** [comment]
@Computersciencened Nobody has been able to provide a reproducible test case. I suspect this is an issue with another dependency or possibly the way the environment is setup but don’t have anything else to go on.

**Comment by zhengyuchuan** [comment]
You can try to restart your IDE.I ran into the same problem.I restart Pycharm and solved this problem  :)

**Comment by sajib1066** [comment]
> You can try to restart your IDE.I ran into the same problem.I restart Pycharm and solved this problem :)

how funny
