### ISSUE TITLE
Need way to provide boost functions in Solr

### ISSUE THREAD

**Issue by iamareebjamal** [django-haystack/django-haystack#1672]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour

I need to provide my search results an edismax boost function `feed_count follower_count^8.0`, which should result in the following URL:

```
http://localhost:8983/solr/ng_core/select?bf=feed_count%20follower_count%5E8.0&defType=edismax&q=shad
```

## Actual behaviour

Closest I came by searching the docs and stackoverflow was to filter using `AltParser` like this:

```
sqs.filter(text=AltParser('edismax', query, bf='feed count follower_count^8.0')
```

which produces the following query:

```
{!edismax bf='feed count follower_count^8.0' }shad
```

which returns no result at all. I played around in Solr Dashboard and even if I get it to return results, the way Solr parses it is very very different than it does the expected query. 

I tried reading upon how to add custom query params to the generated query, but the `Custom Input` method does not fit my need since it can only change the query text and not add parameters.

The current workaround I had to do was to do it this way:

```
sqs.query.get_results(defType='edismax', bf='feed_count')
```

So that the extra kwargs get passed on to the final query function, however, I really don't want to jump out of the nice SearchQuerySet chaining, and more importantly, I can't get the paging to work with this nicely:

```
sqs.query.get_results(defType='edismax', bf='feed_count')[offset:offset + page_size]
```

This won't work since the results have already been fetched, and 

```
sqs[offset:offset + page_size].query.get_results(defType='edismax', bf='feed_count')
```

This won't work since now sqs slice returns a list. To correctly run it, I have to write it like this:

```
query = sqs.query
query.set_limits(offset, offset + page_size)
query.get_results(defType='edismax', bf='feed_count')
```

Which feels slightly more hacky. So is there a way I can add query params without breaking the SearchQuerySet chain?

## Steps to reproduce the behaviour
Written Above

## Configuration

* Operating system version: Linux Mint 19.1 (Ubuntu 18.04)
* Search engine version: Solr 7, 8
* Python version: 3.6
* Django version: 1.11
* Haystack version: 2.8.1

**Comment by acdha** [comment]
This hits one of the big challenges for Haystack: search engines have less in common than SQL databases so you're basically left with trying to find a way to cleanly pass non-portable values.

I've been using this for years on a project:

```python
            alt_q = AltParser('edismax', self.query,
                              qf='title^4 text institution^0.5',
                              bq='django_ct:core.itemtranslation^6.0',
                              # Fewer than three terms must all match, with more than three 75% must match:
                              mm='2<-25%')

            sqs = sqs.filter(content=alt_q)
```

That subsequently uses the queryset API (and avoids extra calls) but it does use a custom backend (https://gist.github.com/acdha/0a66ca23984bc8d607936fecd9c29941) because I'm also heavily dependent on Collapse/Expand for performance on that project.

**Comment by iamareebjamal** [comment]
OK, so there is no way except to create a custom backend for this functionality?

**Comment by acdha** [comment]
Customizing the query parameters beyond what AltParser allows will likely require subclassing the backend.

**Comment by iamareebjamal** [comment]
OK, thanks.
