### ISSUE TITLE
New release of django-haystack?

### ISSUE THREAD

**Issue by maxking** [django-haystack/django-haystack#1673]
I was wondering if you could release a new version of django-haystack, primarily to get the support for `elasticsearch5_backend`?

The previous release was about an year ago.

**Comment by acdha** [comment]
Good idea but I haven't had much time to work on it. If you wanted to help with testing & reviewing the change log you could help accelerate the process:

https://github.com/django-haystack/django-haystack/compare/v2.8.1...master

**Comment by maxking** [comment]
I can help out, sure. What is your usual testing process for releases? OR what would be something that I can do?

I am currently running a source install  locally to work with ElasticSearch 5.x backend.

**Comment by s-i-l-k-e** [comment]
@maxking I second this. @acdha what help do you need to get things off the ground?

**Comment by acdha** [comment]
I don’t have much time to spare these days so testing & drafting the release notes would be helpful.

**Comment by debdolph** [comment]
Any ETA for the 3.0-release? We need a release with django3 support :/…

**Comment by acdha** [comment]
Can you help with testing?

**Comment by debdolph** [comment]
> Can you help with testing?

We currently are using the latest beta release and cannot see anything that does not work

**Comment by acdha** [comment]
“latest beta release” meaning 3.0b1 on PyPI? I'm inclined to just release that since it's been a couple months with no feedback.

**Comment by debdolph** [comment]
> “latest beta release” meaning 3.0b1 on PyPI? I'm inclined to just release that since it's been a couple months with no feedback.

jup. We are using 3.0b1 without problems

**Comment by jbagot** [comment]
The version 3.0 is already released, you could close this issue. Thanks btw
