### ISSUE TITLE
Issue with some installs of Haystack and elasticsearch and http://127.0.0.1:9200/haystack/_mapping.

### ISSUE THREAD

**Issue by msapiro** [django-haystack/django-haystack#1675]
I have Haystack installed on four different servers. I have recently switched from using Whoosh as the backend to using elasticsearch. The four servers and their configurations are:

dev:
- Ubuntu 16.04
- Python 3.5.2
- openjdk-11-jre 11.0.1
- Django-2.0.8
- elasticsearch  5.5.3 installed from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.3.deb
- elasticsearch Python bindings 5.5.3 installed via pip install 'elasticsearch>=5.0.0,<6.0.0'
- Haystack installed from GitHub via pip install -e git+https://github.com/django-haystack/django-haystack.git@master#egg=django-haystack
go:
- Ubuntu 16.04
- Python 3.5.2
- openjdk-11-jre 11.0.1
- Django-2.0.6
- elasticsearch  5.5.3 installed from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.3.deb
- elasticsearch Python bindings 5.5.3 installed via pip install 'elasticsearch>=5.0.0,<6.0.0'
- Haystack installed from GitHub via pip install -e git+https://github.com/django-haystack/django-haystack.git@master#egg=django-haystack
mpo:
- Ubuntu 14.04
- Python 3.6.5
- openjdk-11-jre 11.0.1
- Django-2.0.9
- elasticsearch  5.5.3 installed from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.3.deb
- elasticsearch Python bindings 5.5.3 installed via pip install 'elasticsearch>=5.0.0,<6.0.0'
- Haystack installed from GitHub via pip install -e git+https://github.com/django-haystack/django-haystack.git@master#egg=django-haystack
lm3o:
- Ubuntu 14.04
- Python 3.6.2
- openjdk-11-jre 11.0.1
- Django-2.0.5
- elasticsearch  5.6.16 installed from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.16.deb
- elasticsearch Python bindings 5.5.3 installed via pip install 'elasticsearch>=5.0.0,<6.0.0'
- Haystack installed from GitHub via pip install -e git+https://github.com/django-haystack/django-haystack.git@master#egg=django-haystack

The issue is on `dev` and `go` but not on `mpo` or `lm3o`, when the Django admin update_index job is run, it says:
```
PUT http://127.0.0.1:9200/haystack/_mapping/modelresult [status:400 request:0.011s]
```
and when the Django admin rebuild_index job is run, it says:
```
GET http://127.0.0.1:9200/haystack/_mapping [status:404 request:0.003s]
PUT http://127.0.0.1:9200/haystack/_mapping/modelresult [status:400 request:0.008s]
```
The times in these messages vary, but the rest is constant. The jobs actually seem to work on the servers that issue these messages, but the messages are annoying (they come via emal from an hourly cron as well as when jobs are run manually.)

The only common factor I see in the configs is the servers that issue the messages are Ubuntu 16.04 and Python 3.5 and those that don't are Ubuntu 14.04 and Python 3.6, but that doesn't seem a likely cause.

Any ideas on this?

**Comment by msapiro** [comment]
I have done some more experimenting. To see if this had anything to do with the Python version, I updated the installations on `dev` to Python 3.7.1 and Django 2.1.8 and on `go` to Python 3.7.3 and Django 2.1.8. The behavior didn't change.

The one thing I'm focusing on now is `dev` and `go` use systemd and `mpo` and `lm3o` use init. The start options for elasticsearch are different. The init.d script has -d to daemonize the process and the systemd script has only --quiet. I tried adding -d to the systemd script which required removing --quiet, but this didn't help.

I'm still lost for a solution.

**Comment by joshuajonah** [comment]
The 400 and 404 errors are the issue here. elastic search is either not running or not accessible. Try those links in a web browser and get elastic functioning properly first. This isn't really a Haystack thing.

**Comment by msapiro** [comment]
elasticsearch is running correctly and there is no problem. The `GET http://127.0.0.1:9200/haystack/_mapping` 404 error only occurs once when initializing a new search index, i.e. once after running clear_index or when running rebuild_index. This comes from https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L156 and is anticipated and caught and passed. This is not a problem. The only question is why, when these commands are run on 4 different installations, the message is printed only on two of them.

The `PUT http://127.0.0.1:9200/haystack/_mapping/modelresult` 400 occurs every time update_index is run. This comes from https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L175. I don't know why this fails, but other than printing the error, it doesn't seem to cause a problem. 

Here's an example. I have instrumented `haystack/backends/elasticsearch_backend.py` like this:
```
--- elasticsearch_backend.py.orig	2019-05-24 08:35:14.896895896 -0700
+++ elasticsearch_backend.py	2019-05-24 08:39:46.647372092 -0700
@@ -153,8 +153,10 @@
         # during the ``update`` & if it doesn't match, we'll put the new
         # mapping.
         try:
+            print('Trying get_mapping')
             self.existing_mapping = self.conn.indices.get_mapping(index=self.index_name)
         except NotFoundError:
+            print('get_mapping 404')
             pass
         except Exception:
             if not self.silently_fail:
@@ -172,9 +174,11 @@
                 self.conn.indices.create(
                     index=self.index_name, body=self.DEFAULT_SETTINGS, ignore=400
                 )
+                print('trying put_mapping')
                 self.conn.indices.put_mapping(
                     index=self.index_name, doc_type="modelresult", body=current_mapping
                 )
+                print('put_mapping succeeded')
                 self.existing_mapping = current_mapping
             except Exception:
                 if not self.silently_fail:
```
And here's an annotated transcript:

First clear the index.
```
mark@msapiro:/opt/mailman/mm$ bin/django-admin clear_index
WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
All documents removed.
```
Then run update
```
mark@msapiro:/opt/mailman/mm$ bin/django-admin update_index
Indexing 24 emails
Trying get_mapping
GET http://127.0.0.1:9200/haystack/_mapping [status:404 request:0.014s]
get_mapping 404
```
get_mapping 404s but this is expected.
```
trying put_mapping
PUT http://127.0.0.1:9200/haystack/_mapping/modelresult [status:400 request:0.013s]
```
put_mapping 400s. Why? The `/haystack/_mapping/modelresult` exists now and is getable.
```
mark@msapiro:/opt/mailman/mm$ wget -O - http://127.0.0.1:9200/haystack/_mapping/modelresult
--2019-05-24 08:55:36--  http://127.0.0.1:9200/haystack/_mapping/modelresult
Connecting to 127.0.0.1:9200... connected.
HTTP request sent, awaiting response... 200 OK
Length: 707 [application/json]
Saving to: ‘STDOUT’

-                     0%[                    ]       0  --.-KB/s               {"haystack":{"mappings":{"modelresult":{"properties":{"archived_date":{"type":"date"},"date":{"type":"date"},"django_ct":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"django_id":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"id":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"mailinglist":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"sender":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"subject":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"text":{"type":"text-                   100%[===================>]     707  --.-KB/s    in 0s      

2019-05-24 08:55:36 (72.7 MB/s) - written to stdout [707/707]
```
yet another update_index run can't PUT it.
```
mark@msapiro:/opt/mailman/mm$ bin/django-admin update_index
Indexing 24 emails
Trying get_mapping
```
This time get_mapping succeeds
```
trying put_mapping
PUT http://127.0.0.1:9200/haystack/_mapping/modelresult [status:400 request:0.010s]
mark@msapiro:/opt/mailman/mm$ 
```
but put_mapping still fails. In spite of the failure, the indexing succeeds as the items can be successfully searched in the application. The 400 failure on the PUT is a puzzle, but it is not what concerns me. My issue is my application has a Django job (currently run hourly) which runs update_index with --since to index the emails that arrived since the last update. On two servers, this runs silently and on the other two it outputs the `PUT http://127.0.0.1:9200/haystack/_mapping/modelresult [status:400 request:0.010s]` message resulting in annoying hourly emails to the admin.

While it would be good to understand why we get the 400 and maybe fix it, the real issue for me is how can I make the two noisy servers like the other ones. I don't think the 400 is an elasticsearch issue per se because the two quiet servers don't issue the `GET http://127.0.0.1:9200/haystack/_mapping [status:404 request:0.014s]` message for the 404 on an initial get_mapping even though we know the 404 occurs in that case.

I've done some more digging. I find that the `put_mapping` we are calling is defined in `elasticsearch.client.indices.py` and it calls `self.transport.perform_request()` with a body argument
```
{'modelresult': {'properties': {'django_ct': {'type': 'string', 'index': 'not_analyzed', 'include_in_all': False}, 'django_id': {'type': 'string', 'index': 'not_analyzed', 'include_in_all': False}, 'text': {'type': 'string', 'analyzer': 'snowball'}, 'mailinglist': {'type': 'string', 'analyzer': 'snowball'}, 'subject': {'type': 'string', 'analyzer': 'snowball', 'boost': 1.25}, 'date': {'type': 'date'}, 'sender': {'type': 'string', 'analyzer': 'snowball', 'boost': 1.125}, 'tags': {'type': 'string', 'analyzer': 'snowball', 'boost': 1.25}, 'archived_date': {'type': 'date'}}}}
```
and this throws `elasticsearch.exceptions.RequestError` with the message
```
{'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'The [string] type is removed in 5.0 and automatic upgrade failed because parameters [boost] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [subject]'}], 'type': 'illegal_argument_exception', 'reason': 'The [string] type is removed in 5.0 and automatic upgrade failed because parameters [boost] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [subject]'}, 'status': 400}
``` 
Thus, the 400 is a result of our using the `boost` parameter in our SearchIndex subclass and this is incompatible with elasticsearch 5.

However, this doesn't explain why `self.transport.perform_request()` prints the  `PUT http://127.0.0.1:9200/haystack/_mapping/modelresult [status:400 request:0.010s]` message on two servers and not on the other two, but I agree that this is not a Haystack issue so I'm closing this.

**Comment by msapiro** [comment]
The answer to the remaining question is the error is ultimately logged via `logging.getLogger('elasticsearch').warning() and the two servers that printed the message had a console logger defined in Django's settings and the other two didn't.

Sorry for all the noise on this, but I did learn something in the process.
