### ISSUE TITLE
Prepare_FOO() does not work properly

### ISSUE THREAD

**Issue by Tonyaha** [django-haystack/django-haystack#1683]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
I want to use prepare_FOO() to overwrite the original field data of ProductXXXSearchIndex for search results filtering

## Actual behaviour
When I traverse the search results, print (result. FOO) gets all the same data.
## Steps to reproduce the behaviour

1.Table structure:
![WX20190906-175947](https://user-images.githubusercontent.com/23009370/64419739-27bd4080-d0d0-11e9-94da-28d9014fa4be.png)
2.
![WX20190906-174359](https://user-images.githubusercontent.com/23009370/64418640-fd6a8380-d0cd-11e9-911e-9f65ba460e6e.png)
3. traversing search results, all printed is True. why?
![WX20190906-175529](https://user-images.githubusercontent.com/23009370/64419489-98b02880-d0cf-11e9-8981-fe9836ea8b6e.png)

## Configuration

* Operating system version: Ubuntu 18.04
* Search engine version: ElasticSearch 2.4.1
* Python version: python 3.6.8
* Django version: django 1.11
* Haystack version: django-haystack 2.8.1

**Comment by acdha** [comment]
You declared that field as a Boolean but are returning strings. I’m assuming this is because bool(“false”) will be true.

**Comment by Tonyaha** [comment]
> You declared that field as a Boolean but are returning strings. I’m assuming this is because bool(“false”) will be true.

Thank you for your answer. I changed it according to your prompt. The program is running normally.

**Comment by Tonyaha** [comment]
> You declared that field as a Boolean but are returning strings. I’m assuming this is because bool(“false”) will be true.

Thank you for your answer. I changed it according to your prompt. The program is running normally.
