### ISSUE TITLE
FieldError when running update_index on an index with a ManyToManyKey to Site

### ISSUE THREAD

**Issue by bkonkle** [django-haystack/django-haystack#169]
Good afternoon!  I've run into an issue and I've spent a few hours trying to debug it on my side and getting nowhere.  I've got a model with a ManyToManyKey to Site.  In my SearchIndex subclass, I've defined a 'sites' field as an indexes.MultiValueField(), and I have a prepare_sites(self, obj) method that returns [site.id for site in obj.sites.all()].  The name of the model is ContentPartner, and when I run 'manage.py update_index', I get the following error:

    django.core.exceptions.FieldError: Cannot resolve keyword 'contentpartner' into field. Choices are: alert_lists, anonymity_infos, blog_collections, blogs, combined_polls, comment, domain, emmittcomment, errorflag, flatpage, id, mail_forms, name, polls, redirect, shows, word_lists

I've tried debugging with pdb, and the part it's having a problem with is `obj.sites.all()`.  When pdb tries to evaluate that within the context of the 'prepare_sites' method, it throws the FieldError.  The confusing part is that I can open a separate 'manage.py shell' session, pull the same exact object, and evaluate obj.sites.all() without a problem.  It appears that the reverse accessors for Site are not fully loaded at the time the 'prepare_sites' method is being called.

Let me know what additional information I can provide to help debug.  Thanks for your work on such a fantastic project!

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
