### ISSUE TITLE
Django Haystack does not update Indexes thus creates dead/blank objects (releated to Xapian Haystack?)

### ISSUE THREAD

**Issue by HoshiYamazaki** [django-haystack/django-haystack#1694]
* [Yes] Tested with the latest Haystack release
* [No] Tested with the current Haystack master branch

## Expected behaviour
After deleting instance from my model called Fundraise Django should index every Fundraise again or don't pass empty objects in index.

## Actual behaviour
After deletion/addition of Fundraises Haystack creates empty/blank index objects which breaks my search engine (in template I use fields that are not populated because Haystack does not remove Index after deletion of Fundraise from admin, thus Index can't get data from model instance which does not exist, so it's blank).

# SignalProcessor I tried to fix that:
https://github.com/django-haystack/django-haystack/issues/877

## Configuration

* Operating system version: Linux Mint 19.1 w/ updates
* Search engine version: Xapian-Haystack + fix from https://github.com/notanumber/xapian-haystack/pull/187
* Python version: 3.6.8
* Django version: 2.2.5
* Haystack version:  2.8.1

**Comment by HoshiYamazaki** [comment]
My SearchIndex:
```
class FundraiseIndex(indexes.SearchIndex, indexes.Indexable):
    """Search for Fundraise."""

    text = NgramField(
        document=True,
        use_template=True,
    )

    def get_model(self):
        """Return model for page."""
        return Fundraise

    def index_queryset(self, using=None):
        """Return index for page."""
        return self.get_model().objects.select_related(
            'sportsman',
            'sportsman__user__country',
            'album',
            'album__head',
        ).filter(
            Q(status=Fundraise.ACCEPTED) | Q(status=Fundraise.VERIFIED),
            date_to__gte=timezone.now(),
        ).order_by(
            'date_to',
        )
```
txt template:
```
{{ object.title }}
{{ object.goal }}
{{ object.reason.name }}
{{ object.sportsman.user.first_name }}
{{ object.sportsman.user.last_name }}
```

**Comment by acdha** [comment]
This sounds like you need to run the [`update_index` command](https://django-haystack.readthedocs.io/en/master/management_commands.html#update-index) or use one of the signal handlers to update the index after changing the database.
