### ISSUE TITLE
In project type model make email and hosting different objects instead of one

### ISSUE THREAD

**Issue by panditavaneesh** [django-haystack/django-haystack#1699]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Steps to reproduce the behaviour

1.

## Configuration

* Operating system version:
* Search engine version:
* Python version:
* Django version:
* Haystack version:

**Comment by acdha** [comment]
This seems like it’s specific to your project, not Haystack
