### ISSUE TITLE
django haystack with modern elasticsearch ?

### ISSUE THREAD

**Issue by stuaxo** [django-haystack/django-haystack#1703]
Hi,
   The version of elastic search supported by haystack is very old now.
What is needed to update elasticsearch to version 7.x ?

Cheers
Stuart.

**Comment by acdha** [comment]
We have not had much interest from the community in supporting it. If you want to work on a backend following the older versions, feel free to send a PR.

**Comment by stuaxo** [comment]
Cheers - it's for work.. but not my bit of the project, if it was then I probably would.   Never know I may end up back here with one :)

I'm guessing people might be using something like https://pypi.org/project/django-elasticsearch-dsl/ instead.   Weird to me, as last time I had to do anything with search was a while ago and haystack was where it's at.

**Comment by acdha** [comment]
Haystack has a hard problem in that it tries to present an abstraction over search engines which change frequently and have fairly different interfaces. If you only ever intend to support one search engine, it's definitely easier just to support that engine directly and let their developers support the client library.

**Comment by stuaxo** [comment]
Definitely understand this, last time I worked with an amazon API they completely changed the location of lots of APIs on a point release :(
