### ISSUE TITLE
Django.utils.six removed from Django

### ISSUE THREAD

**Issue by crimsonpython24** [django-haystack/django-haystack#1706]
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
Expected the server to run smoothly without any problems.
## Actual behaviour
```python
ImportError: cannot import name 'six' from 'django.utils'
```
## Steps to reproduce the behaviour

1. Create a new Django project
2. Insert 
```python
from haystack import *
```
where the asterisk can be substituted into any package in haystack

## Configuration

* Operating system version: Mac OS Catalina, version 15.10.2
* Search engine version: 81.0.4000.3 (Official Build) dev (64-bit)
* Python version: 3.7.4
* Django version: 3.0.1
* Haystack version: 2.8.1 (`django-haystack`)

**Comment by acdha** [comment]
Duplicate. Please search for ongoing work before opening new issues.
