### ISSUE TITLE
When django-haystack uses Solr as a search engine, can it only search accurately? How can I fuzzy search?

### ISSUE THREAD

**Issue by reBiocoder** [django-haystack/django-haystack#1707]
When django-haystack uses Solr as a search engine, can it only search accurately? How can I fuzzy search?

![6FF@8GGZ3B }K4`4WN(7B77](https://user-images.githubusercontent.com/39401819/71912483-8abf0100-31b0-11ea-84ab-63433b9a0db4.png)

![LO%$%3O)DD1D1MC@6VN0`(V](https://user-images.githubusercontent.com/39401819/71912518-9e6a6780-31b0-11ea-81b8-872d610ff6d7.png)
As shown above, the wildcard * does not work

**Comment by acdha** [comment]
This was added in #937. You can also pass any custom syntax to the backend like this: http://django-haystack.readthedocs.io/en/v2.6.0/inputtypes.html

**Comment by reBiocoder** [comment]
> 这是在[＃937](https://github.com/django-haystack/django-haystack/pull/937)中添加的。您也可以像这样将任何自定义语法传递给后端：[http](http://django-haystack.readthedocs.io/en/v2.6.0/inputtypes.html) : [//django-haystack.readthedocs.io/en/v2.6.0/inputtypes.html](http://django-haystack.readthedocs.io/en/v2.6.0/inputtypes.html)

thank you very much!
