### ISSUE TITLE
Django 3.0 – ImportError: cannot import name 'six' from 'django.utils'

### ISSUE THREAD

**Issue by JonLevischi** [django-haystack/django-haystack#1708]
<img width="1263" alt="Screen Shot 2020-01-07 at 15 41 30" src="https://user-images.githubusercontent.com/700091/71922796-6809f980-316a-11ea-8bb0-b5219242f682.png">

* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour
Run server and load package.

## Actual behaviour
Error trying to import deprecated module.

## Steps to reproduce the behaviour

1. Just install latest Django.

## Configuration
Same that was working before Django 3.0

* Operating system version: Ubuntu 18 / macOS 10.15.2
* Search engine version: Whoosh 2.7.4
* Python version: 3.8.1
* Django version: 3.0.2
* Haystack version: 2.8.1

**Comment by acdha** [comment]
Follow the pull request for this

**Comment by jmtb28** [comment]
@acdha Can you add a link to the pull request of this issue that you're talking about? Thanks.

**Comment by timkofu** [comment]
I have the same problem.
