### ISSUE TITLE
TypeError: handle() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by KrikorHerlopian1** [django-haystack/django-haystack#1719]
update_index.Command().handle(
    app_label,
    using=None, 
    remove=indexJob.remove
    )

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fdc/PycharmProjects/FDC/FDC_2_7/artifacts/DBIndexManager.py", line 56, in _update_index
    remove=indexJob.remove
TypeError: handle() takes 1 positional argument but 2 were given

Python version:
python 3.6
Django version:
2.2
Haystack version:
2.8.1

**Comment by KrikorHerlopian1** [comment]
Haystack version s 2.8.1

**Comment by KrikorHerlopian1** [comment]
Am migrating from django 1.8 to django 2.2 and haystack was version 2.4 i think to 2.8.1

**Comment by yeago** [comment]
what is DBIndexManager?

that trace doesn't really seem to tell much
