### ISSUE TITLE
ImportError: cannot import name 'six' from 'django.utils'

### ISSUE THREAD

**Issue by ryanhunt** [django-haystack/django-haystack#1732]
* [ x ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
It works
## Actual behaviour
```
File "/Users/ryan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/haystack/__init__.py", line 11, in <module>
    from haystack.utils import loading
  File "/Users/ryan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/haystack/utils/__init__.py", line 9, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/Users/ryan/.pyenv/versions/3.8.2/lib/python3.8/site-packages/django/utils/__init__.py)
```

## Steps to reproduce the behaviour

It appears haystack is still relying upon six from django.utils, which was dropped in Django 3.0. See [here](https://stackoverflow.com/questions/59191180/getting-error-cannot-import-name-six-from-django-utils-when-using-django-3-0) and [here](https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils)

## Configuration

* Operating system version:??
* Search engine version: ??
* Python version: 3.8.2
* Django version: 3.0.6
* Haystack version: 2.8.1

**Comment by acdha** [comment]
Haystack 2.8.1 does not support Django 3. The 3.0 beta is available if you want to help test it: https://pypi.org/project/django-haystack/3.0b2/
