### ISSUE TITLE
Cannot resolve keyword 'your_distance_gte' into field. Choices are: Shop_category,  address, your_distance, id, name, shop_location, user, user_id

### ISSUE THREAD

**Issue by Sarthak77tiwari** [django-haystack/django-haystack#1735]
I have two model shop and customer
**shop**

`Shop(models.Model):
     address = models.CharField(max_length=70, null=True)
    Shop_category = models.CharField(max_length=200, null=True, ) 
    Name=models.CharField(max_length=70)
     distance = models.PositiveIntegerField(null=True)
     shop_location = models.PointField(null=True, default=Point(28.49, 77.33))`
**customer**
`class Customer(models.Model):
        user = models.OneToOneField(User, null=True, 
           on_delete=models.CASCADE)
    customer_location = models.PointField(null=True, default=Point(28.49, 77.33))`
I want to set the filter on the shop. The shop will show to the customer if the distance between shop and customer under the distance given by the shop.distance and my views.py

     `from django.contrib.gis.db.models.functions import Distance
  `Shop_list = Shop.objects.filter(
    your_distance_gte=Distance('shop_location',    
    request.user.customer.customer_location)
   )`
I am getting the error Cannot resolve keyword 'your_distance_gte' into field. Choice are: Shop_category, address, your_distance, id, name, shop_location, user, user_id

**Comment by acdha** [comment]
This uses the same syntax as the Django ORM: you need a double underscore for a field or operator boundary.
