### ISSUE TITLE
Documentation for Haystack 3 migration?

### ISSUE THREAD

**Issue by Cabalist** [django-haystack/django-haystack#1744]
* [X] Tested with the latest Haystack release
* [X] Tested with the current Haystack master branch

Is a changelog or migration guide available for moving to Haystack3?  

We are working on a Django 3 migration and have found that `FacetMultiValueField`, `FacetBooleanField` are not available any longer.   We are looking for next steps to complete the migration.  

Thanks! 

## Configuration

* Operating system version: latest ubuntu
* Search engine version: pysolr-3.9.0
* Python version:3.8.5
* Django version: 3.1.2
* Haystack version:3.0

**Comment by acdha** [comment]
They're still in the source code. Are you getting an error while trying to use them?

**Comment by Cabalist** [comment]
Yep.  I get:

`AttributeError: module 'haystack.indexes' has no attribute 'FacetMultiValueField'`

Upon closer inspection it looks like they were moved/removed from `haystack.indexes`.   My guess is that they shouldn't have been imported from there in the first place in this project.  

This can probably be closed.  :)

**Comment by acdha** [comment]
Ah, yes, one of the things which happened a while back was tidying the * imports so linters could be more reliable.
