### ISSUE TITLE
update_index  removed all records 

### ISSUE THREAD

**Issue by nikolaysm** [django-haystack/django-haystack#1747]
I'm using django 1.11 and haystack 2.8.1

If i run update_index  with `--remove` and `--age=24` and with multiple indexes than all records are removed.

After some debugging of the update_index I came across that line 300 in the update_index command returns an empty list.

https://github.com/django-haystack/django-haystack/blob/1f010774c8b52e71a6c629f4469934d093a3bdf1/haystack/management/commands/update_index.py#L300

I think there's a bug.

We have to provide `using` otherwise we cannot use multiple indexes on the same model.
`qs = index.index_queryset(using=using).values_list('pk', flat=True)`

Or have I taken something wrong?

**Comment by acdha** [comment]
That does sound like a bug — I think you're using it in a relatively uncommon configuration which we clearly could use some coverage for. If you want to work on a pull request it might be good to start with a test confirming the problem so we can look for any side effects to the fix.

**Comment by nikolaysm** [comment]
I have a similar index_queryset as in documentation [Multi-lingual Content](https://django-haystack.readthedocs.io/en/master/multiple_index.html#multi-lingual-content)

```
def index_queryset(self, using=None):
    return Post.objects.filter(language=using)
```

So if `using` not provided it returns empty queryset.

**Comment by claudep** [comment]
I guess that the merged PR is solving this issue.
