### ISSUE TITLE
Broken Link to Whoosh

### ISSUE THREAD

**Issue by mslinn** [django-haystack/django-haystack#1757]
The file [backend_support.rst](https://django-haystack.readthedocs.io/en/master/backend_support.html) contains a broken link to Whoosh: https://bitbucket.org/mchaput/whoosh/, which is invalid.

I do not know what the correct URL is, or I would have offered a pull request.

**Comment by thatsed** [comment]
The readme has the same problem.

That same link is also broken in Whoosh docs https://whoosh.readthedocs.io/en/latest/intro.html#getting-help-with-whoosh
I couldn't find the repo on BitBucket either, but i find its documentation a better suited target for the broken link.

**Comment by mslinn** [comment]
I found the project on GitHub: https://github.com/mchaput/whoosh/
