### ISSUE TITLE
pip installation fails for django-haystack 2.7.0 due to setuptools_scm dependency broken for python 2.7 

### ISSUE THREAD

**Issue by jpatel3** [django-haystack/django-haystack#1765]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
django-haystack==2.7.0 installation work fine

## Actual behaviour
django-haystack==2.7.0 installation as dependency for the project fails due to underlying dependency refers to latest version of setuptools_scm 6.0.1, which expects python 3

## Steps to reproduce the behaviour

1. try to install django-haystack===2.7.0 with python 2 environment, which was working fine till setuptools__scm released new version today March 17 2021, which expects python 3.
2. here is the comment from setuptools_scm confirming -
https://github.com/pypa/setuptools_scm/issues/541#issuecomment-801198230

is there any work around?

## Configuration

* Operating system version: 
* Search engine version: solr-6.5.1
* Python version: 2.7.10
* Django version: 1.11.23
* Haystack version: 2.7.0

**Comment by acdha** [comment]
Python 2 hit end of life in January 2020 and Haystack followed in February 2020. If you can't upgrade, you'll need to pin a version of `setuptools_scm` which still supports Python 2.
