### ISSUE TITLE
ModuleNotFoundError: No module named 'whoosh'

### ISSUE THREAD

**Issue by jonesnc** [django-haystack/django-haystack#1791]
## Problem
I want to be able to use django-haystack + elasticsearch backend without needing to install the `whoosh` package, since I'm not using the Whoosh backend. I currently get an `ModuleNotFoundError: No module named 'whoosh'` error when attempting to use haystack. Once the `whoosh` package is installed, the error goes away, but I don't want to have to do that since I'm not using the Whoosh backend.

* [ ] Tested with the latest Haystack release (no, this only happens on the current master branch)
* [X] Tested with the current Haystack master branch

## Expected behaviour
The ability to use `django-haystack` with a non-Whoosh backend without needing to install the `Whoosh` package

## Actual behaviour
Using haystack throws `ModuleNotFoundError: No module named 'whoosh'` when I don't have the `whoosh` package installed

## Steps to reproduce the behaviour

1. Put `git+https://github.com/django-haystack/django-haystack.git@8ab14a273d8f438fe3542d988954e41bddc13fc8#egg=django-haystack` in your requirements.txt file, then run `pip install -r requirements.txt`
2. Start a Django shell with `python3 manage.py shell`
3. Try to use `haystack`:
```python
[1]: from haystack.query import SearchQuerySet

[2]: SearchQuerySet().all().count()
```
4. See the error:
```
/usr/local/lib/python3.6/dist-packages/haystack/fields.py in <module>                                                                                                                
      4 from django.template import loader                                                
      5 from django.utils import datetime_safe                                                                                                                                       
----> 6 from whoosh import analysis                                                       
      7                                                                                   
      8 from haystack.exceptions import SearchFieldError                                  
                                                                                          
ModuleNotFoundError: No module named 'whoosh'
```

## Configuration

* Operating system version: Ubuntu 18.04.5 LTS (in a container)
* Search engine version: Elasticsearch 5.6
* Python version: 3.6
* Django version: 2.2
* Haystack version: django-haystack-3.1.dev68+g8ab14a2

**Comment by acdha** [comment]
Ouch, sorry about that – it looks like an oversight in #1789. We need to make that conditional.

**Comment by jonesnc** [comment]
@acdha If you could describe what a fix would look like, I could work on a PR that addresses this issue.

**Comment by hzwlth** [comment]
pip install whoosh

**Comment by cclauss** [comment]
A bit more context on Whoosh...
* https://github.com/django-haystack/django-haystack/issues/1924#issuecomment-1860716826
