### ISSUE TITLE
relevants suggestions

### ISSUE THREAD

**Issue by crowd42** [django-haystack/django-haystack#1801]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

I'm using Django-haystack + Elasticsearch. I have INCLUDE_SPELLING set to True and {{ suggestion }} tag in my template. When for example I search for émile zola I get émile zozo (which doesn't exist in the index or db) as suggestion instead of emile zola. Anyway to fix this? Thanks

**Comment by acdha** [comment]
That's probably a better question for the ElasticSearch documentation — Haystack just requests that from the backend and passes back whatever the search engine returns. It's possible that there are some defaults for your language which need tuning.

**Comment by crowd42** [comment]
Thank you, I will check on their side
