### ISSUE TITLE
Haystack is responsible for bad coverage score

### ISSUE THREAD

**Issue by batiste** [django-haystack/django-haystack#182]
When I activate haystack in my project, the coverage report becomes bad.

Haystack is loading modules in my project too soon because of that the coverage doesn't count the import and function definition in my models.py. Apparently because I import those in my search_indexes.py.

I use django test extensions:

http://github.com/garethr/django-test-extensions/issues#issue/5

Could be nice to find a way to not load read search_indexes.py files that early, maybe by using an registry instead?

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this issue with haystack now please raise a new issue.
