### ISSUE TITLE
Django 4.0 Incompatability

### ISSUE THREAD

**Issue by jensenbox** [django-haystack/django-haystack#1826]
This could be the first of many - meaning I have not tested to see if there are any further issues other than:

```
dev                |   File "/usr/local/lib/python3.9/site-packages/haystack/admin.py", line 7, in <module>
dev                |     from django.utils.translation import ungettext
dev                | ImportError: cannot import name 'ungettext' from 'django.utils.translation' (/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py)
```

This is a direct result of: https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0

**Comment by saemideluxe** [comment]
This seems to be fixed on master. Maybe somebody could publish a new release?

**Comment by StephenMayeux** [comment]
> This seems to be fixed on master. Maybe somebody could publish a new release?

I would also like to see this published on a new release. The latest version (3.1.1) was release last year in August.

**Comment by claudep** [comment]
Looks like #1828 is waiting for maintainer approval. @acdha, would you mind giving me write access to the repo? I can't promise so much time to dedicate to the project, but I can lend a hand. I'm already maintaining [xapian-haystack](https://github.com/notanumber/xapian-haystack/).

**Comment by acdha** [comment]
@claudep I just sent you an invite. Thank you!

**Comment by MatthiasPortzel** [comment]
+1 waiting for a release of this change.
