### ISSUE TITLE
When will haystack release for django 4.0+ version?

### ISSUE THREAD

**Issue by R1ckyH** [django-haystack/django-haystack#1842]
## Expected behavior
update for Django 4.0+ version
## Actual behavior
support for django 3.2 right now
as a user with Django, I see that it hasn't been updated since Aug 2021, so will it be possible to update to Django 4.0?

**Comment by claudep** [comment]
I would like to make the project a bit more active, but it looks like we would need at least a second person with enough time to review/approve patches, as @acdha seems to be a bit short of time for the project.

**Comment by MNabeelHassan** [comment]
Currently I am using this hack to get django-haystack working with django 4.0:
```
pip install git+https://github.com/django-haystack/django-haystack.git@4a5d82fa03c93d5446cb2d040f32092b3abedb1b#egg=django-haystack
```
Ps: It would still be nice if the newer version got released.

**Comment by R1ckyH** [comment]
> The PR for the issue I was facing was already done, approved and merged: #1814 So I don't think a new PR is needed, just v3.1.2 needs to be released.

may I ask that have you test it with Django 4.0?

**Comment by MNabeelHassan** [comment]
Yes, no problems so far

**Comment by R1ckyH** [comment]
I see, as @MNabeelHassan test for Django 4.0, I think that v3.1.2 might be time to release right now @claudep

**Comment by R1ckyH** [comment]
hello @acdham, would you like to release a new version and publish it to pip which is compatible with Django 4.0

**Comment by acdha** [comment]
> hello @acdha , would you like to release a new version and publish it to pip which is compatible with Django 4.0?

I'm a bit reluctant to release something which I don't have time to test more than casually as a point release. I just tagged a pre-release so it's a bit easier for you to test but this could use some community review:

https://pypi.org/project/django-haystack/3.2.dev0/

**Comment by R1ckyH** [comment]
I see. You are right, I will try it later, thx a lot for it.

**Comment by NagisaCo** [comment]
Last month I used haystack3.1.1 with Django 4.0 and modified some source codes for its compatibility. I'll try the 3.2.dev0 for Django 4.0 now. Thanks for your effort. Looking forward to the next release.

**Comment by acdha** [comment]
Thank you for testing. I can roll the release any time but would like at least a couple of positive confirmations first.

**Comment by dvzrv** [comment]
I have patched django-haystack and hyperkitty to gain support for django 4.0 as on Arch Linux we follow a rolling release scheme.

> I can roll the release any time but would like at least a couple of positive confirmations first.

I understand that you would like to be cautious about a release, but isn't testing this project what your CI is for?

However, please consider, that it is not feasible to use django-haystack, if for every release there is a waiting time for over two months to wait for people on the internet to give a :+1: (FWIW: anyone could do that and it does not provide any proof that anything works or doesn't work, however tests do that quite unambiguously) and downstreams start cherry-picking patches left and right.
