### ISSUE TITLE
crash after updating to 3.2 (date_facet_fields is returning: TypeError: 'NoneType' object is not iterable)

### ISSUE THREAD

**Issue by azneto** [django-haystack/django-haystack#1850]
* [ X ] Tested with the latest Haystack release
* [ X ] Tested with the current Haystack master branch

## Expected behaviour
The system was working fine using django-haystack==3.1.1, but crashes after updating to django-haystack==3.2.dev0 or django-haystack==3.2.0

## Actual behaviour

```
[Tue May 03 13:33:51.455164 2022] [wsgi:error]  File "/var/www/YOURPROJECT/lib/python3.8/site-packages/haystack/generic_views.py", line 112, in get_queryset
[Tue May 03 13:33:51.455200 2022] [wsgi:error]  TypeError: 'NoneType' object is not iterable
```

## Steps to reproduce the behaviour

Based on this pull request #1690, it seems like this code from generic_views.py was supposed to run only if the search engine is solr:

```
112        for field in self.date_facet_fields:
113            qs = qs.date_facet(**field)
```

If I comment those lines, everything works fine.

## Configuration

* Operating system version: Ubuntu 20.04.4 LTS
* Search engine version: elasticsearch 7.17.2
* Python version: 3.8.10
* Django version: 3.2.13
* Haystack version: 3.2.0

**Comment by acdha** [comment]
Try v3.2.1 which is just out in 14e824c862ab6c9db7bc3c3acf343cd0ab08953c

**Comment by azneto** [comment]
It works! Thx
