### ISSUE TITLE
Django 5 deprecated datetime_safe --> Drop support for whoosh?

### ISSUE THREAD

**Issue by itmve** [django-haystack/django-haystack#1924]
Using django 5 and django-haystack from git with the whoosh backend the following error occurs:

```
  File "/home/<project>/env/lib/python3.11/site-packages/haystack/backends/whoosh_backend.py", line 10, in <module>
    from django.utils.datetime_safe import date, datetime
ModuleNotFoundError: No module named 'django.utils.datetime_safe'
```
datetime_safe was deprectated in django 5.

**Comment by cclauss** [comment]
https://pypi.org/project/Whoosh/ has not been updated since 2016 and points to a nonexistent repo on GitLab.

While https://github.com/mchaput/whoosh exists, it needs modernization.

There are lots of open issues in https://github.com/django-haystack/django-haystack/labels/backend%20%3A%20whoosh

**Comment by cclauss** [comment]
Fixed by
* #1937
