### ISSUE TITLE
How to create a document index asynchronously when use whoosh?

### ISSUE THREAD

**Issue by liuzm7188** [django-haystack/django-haystack#2002]
class Data(models.Model):
    content = models.TextField()
    is_updated = models.BooleanField(default=False)

I want to  create a document index asynchronously.
Such as: [it is wrong.]
    from haystack.signals import BaseSignalProcessor
    signal_processor = BaseSignalProcessor()
    
    queryset = Data.objects.filter(is_updated=True)
    for instance in queryset:
        signal_processor.handle_save(instance)
  
How to fix the above code?

**Comment by liuzm7188** [comment]
for instance in queryset:
    signal_processor.handle_save(Data, instance)

**Comment by cclauss** [comment]
(Added GitHub markdown [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) for readability.)
