### ISSUE TITLE
Support for related models

### ISSUE THREAD

**Issue by patrys** [django-haystack/django-haystack#22]
Actually more like support for related SearchIndexes. An exmaple case is searching for all blog posts that mention a certain word either in their body or in one of the comments. Searching both indexes is certainly possible but requires manually following foreign keys and merging the results not to get duplicate entries.

It would be nice to be able to use related SearchIndexes just like you use any other SearchIndex fields.

**Comment by sampeka** [comment]
Closing these old issues now to start moving this project back toward a healthy state, but please feel free to reopen this and we can start a new dialogue about it.
