### ISSUE TITLE
Problem with spelling_suggestion() and models()

### ISSUE THREAD

**Issue by terrasque** [django-haystack/django-haystack#231]
(Seen with whoosh backend)

If I restrict my search to one model, one word will always pop up in spelling_suggestions()

Example:
    In [12]: SearchQuerySet().models(Model).auto_query("a").spelling_suggestion()
    Out[12]: u'skrangler'

    In [13]: SearchQuerySet().models(Model).auto_query("moo").spelling_suggestion()
    Out[13]: u'skrangler'

    In [14]: SearchQuerySet().models(Model).auto_query("asdf").spelling_suggestion()
    Out[14]: u'asd skrangler'

    In [15]: SearchQuerySet().models(Model).auto_query("test").spelling_suggestion()
    Out[15]: u'tester skrangler'

    In [16]: SearchQuerySet().auto_query("test").spelling_suggestion()
    Out[16]: u'tester'

    In [17]: SearchQuerySet().auto_query("asdf").spelling_suggestion()
    Out[17]: u'asd'

    In [18]: SearchQuerySet().auto_query("moo").spelling_suggestion()
    Out[18]: ''

    In [19]: SearchQuerySet().auto_query("a").spelling_suggestion()

    In [20]: 

Each time model is specified, it will add "skrangler" to the list of spelling suggestions. 

Versions
    Whoosh==0.3.18
    django-haystack==1.0.1-final
    Django==1.2.1
    Python 2.5.2

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
