### ISSUE TITLE
Solr backend does not correctly handle indexing an ImageField

### ISSUE THREAD

**Issue by gregplaysguitar** [django-haystack/django-haystack#233]
Not sure whether this is really an issue with haystack or pysolr, but since ImageField is a django-specific field I'll report it here for now.

Basically when you try to index an imagefield, whoosh and xapian just save the path to the image as a string, but pysolr sees the __iter__ method and thinks it's a list or tuple, so tries to index everything it can iterate over.

I'll see if I can patch the solr backend to fix this, or possibly I just need to explicitly return a string (and not an image field) in my prepare_image method.

Here's the relevant pysolr code:

    def add(self, docs, commit=True):
            """Adds or updates documents. For now, docs is a list of dictionaies
            where each key is the field name and each value is the value to index.
            """
            message = ET.Element('add')
            for doc in docs:
                d = ET.Element('doc')
                for key, value in doc.items():
                    # handle lists, tuples, and other iterabes
                    if hasattr(value, '__iter__'):
                        for v in value:
                            f = ET.Element('field', name=key)
                            f.text = self._from_python(v)
                            d.append(f)
                    # handle strings and unicode
                    else:
                        f = ET.Element('field', name=key)
                        f.text = self._from_python(value)
                        d.append(f)
                message.append(d)
            m = ET.tostring(message)
            response = self._update(m)
            # TODO: Supposedly, we can put a <commit /> element in the same post body
            # as the add element. That isn't working for some reason, and it would save us
            # an extra trip to the server. This works for now.
            if commit:
                self.commit()

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
