### ISSUE TITLE
SearchQuerySet incorrect results

### ISSUE THREAD

**Issue by marcinn** [django-haystack/django-haystack#235]
django-haystack version 1.1.0alpha, Xapian backend 1.1.4 alpha.

I found a problem with SearchQuerySet cache. When slicing queryset further results are incorrect:

    > rs = SearchQuerySet().auto_query('bosch')
    > rs.count()
    192
    > rs[0]    # __getitem__ magic call
    <SearchResult: catalog.product (pk=1104)>
    > rs.count()
    371

Cloning query in SearchQuerySet._fill_cache() workarounds this issue. But incorrect results are still cached. Result count changes after query.set_limits()  (maybe this is a backend-specific issue?)

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
