### ISSUE TITLE
SearchQuerySet exclude not working correctly

### ISSUE THREAD

**Issue by brocaar** [django-haystack/django-haystack#240]
Haystack version: 1.0.1-final
Whoosh version: 0.3.18

For every SearchIndex class I have a CharField named 'kind'. prepare_kind returns a string like 'news', 'products', 'pages' so I can filter/exclude by kind. This doesn't return the expected results :(

Example:

===

from haystack.query import SearchQuerySet
sq = SearchQuerySet()
sq.filter(language_code='en', site_id=2)
[<SearchResult: cms.title (pk=u'35')>, <SearchResult: cms.title (pk=u'34')>, <SearchResult: cms.title (pk=u'33')>, <SearchResult: cms.title (pk=u'32')>, <SearchResult: news.item (pk=u'4')>, <SearchResult: news.item (pk=u'2')>]

sq.filter(language_code='en', site_id=2)[0].kind
u'cms'

sq.filter(language_code='en', site_id=2)[5].kind
u'news'

By excluding kind='news', it still returns news items:
sq.filter(language_code='en', site_id=2).exclude(kind='news')
[<SearchResult: cms.title (pk=u'35')>, <SearchResult: cms.title (pk=u'34')>, <SearchResult: cms.title (pk=u'33')>, <SearchResult: cms.title (pk=u'32')>, <SearchResult: news.item (pk=u'4')>, <SearchResult: news.item (pk=u'2')>]

Raw query:
sq.filter(language_code='en', site_id=2).exclude(kind='news').query.build_query()
u'(site_id:2 AND language_code:en AND NOT (kind:news))'

I also have a SearchIndex with kind='products'. By excluding on kind='products', my news items disappear:
sq.filter(language_code='en', site_id=2).exclude(kind='products')
[<SearchResult: cms.title (pk=u'35')>, <SearchResult: cms.title (pk=u'34')>, <SearchResult: cms.title (pk=u'33')>, <SearchResult: cms.title (pk=u'32')>]

Raw query:
sq.filter(language_code='en', site_id=2).exclude(kind='products').query.build_query()
u'(site_id:2 AND language_code:en AND NOT (kind:products))'

===

Am I doing something wrong or is this a Haystack or Whoosh bug?

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
