### ISSUE TITLE
whoosh backend with multivaluefield gives error when the data is an empty list

### ISSUE THREAD

**Issue by hvdklauw** [django-haystack/django-haystack#256]
The whoosh backend gives me an error if I have a multivaluefield which happens to be empty.

It tries to do a split(',') on a NoneType.

Maybe add a check before it, that if it's None then don't split ;-)

I fixed it for now by putting a bullshit value in the value

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
