### ISSUE TITLE
haystack depends on get_models() when it may not be 'correct'

### ISSUE THREAD

**Issue by kezabelle** [django-haystack/django-haystack#257]
On a project I'm working on, we've got a bunch of different settings files, some included via svn:externals, as such we end up monkeypatching settings.INSTALLED_APPS to get the definitive list of applications needed for 'the project' - syncdb understands this well enough, as do things like south, the admin, et al.

A problem arises in that when running `manage.py update_index` (and presumably rebuild_index too) it looks into `django.db.models.get_models` which, apparently, is a singleton which may include apps no longer part of INSTALLED_APPS.

I list this specifically as a haystack bug because its the only time I've encountered it (so much so, someone on #django IRC had to tell me get_models was a singleton cache). I'm not au fait enough with how django settings are loaded to understand why patching INSTALLED_APPS seems to work fine but may become out of sync with the appcache.

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
