### ISSUE TITLE
Defaulting CharField value to __unicode__

### ISSUE THREAD

**Issue by ingmar** [django-haystack/django-haystack#259]
CharField.prepare should default to unicode(obj) instead of None when there is no other value defined. E.g. in this situation:

    class RegionIndex(SearchIndex):
        title = CharField()
    site.register(Region, RegionIndex)

Haystack 1.1 indexes "None". It'd be much better default behaviour to simply index the result of `unicode(obj)`, or at least try to do so and put None only if that fails.

**Comment by sampeka** [comment]
Not sure this is better default behaviour, particularly if you had lots of different CharFields - you would end up with lots of documents with multiple fields with the same value. Also this is easily overridable with the `prepare_{field_name}` method. Given the age of this issue, I'll close it for now but please feel free to raise a new one to start a new discussion about it.
