### ISSUE TITLE
Quoting issues

### ISSUE THREAD

**Issue by aiko1895** [django-haystack/django-haystack#267]
from haystack.query import SearchQuerySet
sqs = SearchQuerySet()

search_input = '22" '
len(SearchQuerySet().filter(content=sqs.query.clean(search_input)))

Everything is OK, but when I use

search_input = '22" BX'
len(SearchQuerySet().filter(content=sqs.query.clean(search_input)))

I get ERROR:

/data/www/staging/env/lib/python2.5/site-packages/whoosh/support/pyparsing.pyc in parseString(self, instring, parseAll)
   1074         except ParseBaseException, exc:
   1075             # catch and re-raise exception from here, clears out pyparsing internal stack trace
-> 1076             raise exc
   1077         else:
   1078             return tokens

ParseException: Expected end of text (at char 13), (line:1, col:14)

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
