### ISSUE TITLE
Haystack within the Django admin for global search across all models

### ISSUE THREAD

**Issue by simonw** [django-haystack/django-haystack#27]
One of the talks at EuroDjangoCon mentioned that a global search field in the admin that searched all editable content items would be useful. This seems like just the kind of thing that Haystack could be used for. Might be tricky figuring out exactly how to integrate it in to the admin - personally I'd expect it to involve a brand new /admin/search/ view which is styled to look like the admin but has haystack do all of the work

**Comment by sampeka** [comment]
Closing these old issues now to start moving this project back toward a healthy state, but please feel free to open a new issue
