### ISSUE TITLE
Whoosh backend - SearchQuerySet.highlight does not highlight words

### ISSUE THREAD

**Issue by bburan** [django-haystack/django-haystack#273]
Just set up Haystack (Git master - 1.1.0-alpha) with Whoosh (1.1.1).  Very nice work!  However, I am having trouble getting highlighting to work.

    >>> print SearchQuerySet().filter(text='test')[0].text
    'This is a test article for the Whoosh/Haystack integration'

    >>> print SearchQuerySet().filter(text='test').highlight()[0].highlighted
    {'text': ['']}

After some digging, it appears that part of the problem can be found at lines 443:446 of whoosh_backend.py (under SearchBackend._process_results).  Terms being passed to the highlight function is [u'text:test'].  If I change the terms variable to [u'test'], highlighting works as advertised.

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.

**Comment by karolyi** [comment]
+1
