### ISSUE TITLE
selected_facets, URL construction

### ISSUE THREAD

**Issue by imageinary** [django-haystack/django-haystack#294]
When using faceting (as per the example search.html here: http://docs.haystacksearch.org/dev/faceting.html, author has been changed to categories) it appears that when entering a new search term the selected_facets are not cleared.

For example: if you search for foo and then select category test the url looks like this:
    ?q=foo&selected_facets=&selected_facets=categories:test
if you then search for foo2 I would expect the url to look like this:
    ?q=foo2&selected_facets=&selected_facets=
but it looks like this:
    ?q=foo2&selected_facets=&selected_facets=categories:test

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
