### ISSUE TITLE
non-ascii spelling suggestions broken (solr)

### ISSUE THREAD

**Issue by sk1p** [django-haystack/django-haystack#295]
Hi,
using haystack 51013af46cce42459309834a9b1bfd4472456ec1 + apache solr 1.4.1 + pysolr-v2.0.13-0-gdf50f7d 
i get some bad spelling suggestions when searching for non-ascii words. for example searching for "böhme" results in the suggestion "bÃ¶böhme". 

might be related to this issue:

https://issues.apache.org/jira/browse/SOLR-1204

thanks

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
