### ISSUE TITLE
Whoosh Backend: incorrect datestring formatting

### ISSUE THREAD

**Issue by JoeGermuska** [django-haystack/django-haystack#307]
getting this error:

/Users/germuska/.virtualenvs/flps/lib/python2.6/site-packages/whoosh/fields.pyc in _parse_datestring(self, qstring)
    418             day = int(qstring[6:8])
    419         if len(qstring) >= 10:
--> 420             hour = int(qstring[8:10])
    421         if len(qstring) >= 12:
    422             minute = int(qstring[10:12])

ValueError: invalid literal for int() with base 10: 'T0'

In [33]: filtered.query.build_query()
Out[33]: u'pub_date:[TO 18900101T000000]'

In [34]: qstring = '18900101T000000'

In [35]: qstring[8:10]
Out[35]: 'T0'

Reviewing the doc for whoosh.fields, it seems that the T is not expected by Whoosh:

    def _parse_datestring(self, qstring):
        # This method does parses a very simple datetime representation of
        # the form YYYY[MM[DD[hh[mm[ss[uuuuuu]]]]]]

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
