### ISSUE TITLE
SearchQuerySet().filter(...).highlight() doesn't work with whoosh backend

### ISSUE THREAD

**Issue by amakhnach** [django-haystack/django-haystack#310]
What do I have?

Whoosh 1.4.1
Django 1.2.4
Haystack 1.1.0

search_sites.py
    import haystack
    haystack.autodiscover()

search_index.py
    class PublicationIndex(SearchIndex):
       document = CharField(document=True, use_template=True)
    site.register(Publication, PublicationIndex)

publication_document.txt
    {{ object.title_en }}
    {{ object.text_en }}

What am I doing?

python manage.py shell
    >> from haystack.query import SearchQuerySet
    >> from apps.digest.models Publication

    >> sqs = SearchQuerySet().filter(document='how').highlight()
    [<SearchResult: digest.publication (pk=u'26')>]

    >> result = sqs[0]
    >> result.object.text_en
    u"Here's a slightly more complex example using Paginator in a view to
    paginate a queryset. We give both the view and the accompanying
    template to show how you can display the results. This example assumes
    you have a Contacts model that has already been imported."

    >> result.highlighted
    {'document': ['']}

why it doesn't work correctly?

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.

**Comment by karolyi** [comment]
+1
