### ISSUE TITLE
no work find in FK

### ISSUE THREAD

**Issue by CARocha** [django-haystack/django-haystack#321]
Ok i'm test in find for ForeignKey but NOT work a use backend SIMPLE i use example in documentation but does not fully function this is the example

models 1
class A(models.Model)
    nombre = models.CharField(...)

class B(models.Model)
    nombre = models.CharField(...)
    fk = models.ForeignKey(A)

only need find in model B 
in the note.txt a put
{{ object.fk.nombre }} but not find nothing

thank

**Comment by sampeka** [comment]
It's been a long time and a ton of changes have been integrated since this issue was raised, however if you can reproduce this bug with haystack now please raise a new issue.
