### ISSUE TITLE
VariableDoesNotExist Exception In highlight Template Tag

### ISSUE THREAD

**Issue by riggsd** [django-haystack/django-haystack#328]
When my search index gets out of sync with deleted objects, the default Haystack search results template is occasionally tossed some phantom objects. The 'highlight' tag blows up with:

     File "/usr/lib/python2.5/site-packages/django_haystack-1.1.0-py2.5.egg/haystack/templatetags/highlight.py", line 31, in render
       text_block = self.text_block.resolve(context)
    
     File "/usr/lib/python2.5/site-packages/Django-1.2.3-py2.5.egg/django/template/__init__.py", line 696, in resolve
       value = self._resolve_lookup(context)
    
     File "/usr/lib/python2.5/site-packages/Django-1.2.3-py2.5.egg/django/template/__init__.py", line 749, in _resolve_lookup
       raise VariableDoesNotExist("Failed lookup for key [%s] in %r", (bit, current)) # missing attribute
    
    VariableDoesNotExist: Failed lookup for key [text] in u'None'

The Django docs advise catching this exception when using the `resolve()` method in a template tag. http://docs.djangoproject.com/en/1.2/howto/custom-template-tags/#passing-template-variables-to-the-tag

Here's a pseudo-patch to 'haystack.templatetags.highlight.py' for my local fix:

    def render(self, context):
        try:
            text_block = self.text_block.resolve(context)
        except template.VariableDoesNotExist:
            return u'None!'
        ...

**Comment by straningera** [comment]
Rebuilding the index worked for me (Whoosh backend). Probably due to content changes (different ids) in the underlying database.

**Comment by SteveByerly** [comment]
fixed in #1402 when it's incorporated
