### ISSUE TITLE
Allow prepare() to skip indexing of an object

### ISSUE THREAD

**Issue by gtaylor** [django-haystack/django-haystack#380]
SearchIndex.index_queryset() may be used to define a queryset of object to index, but this leaves us without the ability to filter based on methods or properties. 

It looks like should_update() is not currently being called, so there's no way to selectively skip the indexing of an object by a property/method.

Perhaps returning an empty dict from within prepare() would signify that the object should be skipped?

**Comment by chronossc** [comment]
Some update on that issue after almost 4 years?

**Comment by acdha** [comment]
@chronossc Most people use `index_queryset` for efficiency. If you have a problem which cannot be solved there, feel free to submit a pull request. It would need to update every backend but that could be as simple as adding an exception and a single except/continue block to e.g. 

https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/solr_backend.py#L56

**Comment by chronossc** [comment]
@acdha Yeah, the `index_queryset` can't be used in that because is something more like per object checks, that while not as efficient, it is more flexible. I will prepare a PR for you.

**Comment by chronossc** [comment]
@acdha The commit is at https://github.com/chronossc/django-haystack/commit/5745c0c9a2c6b69b282f1c8765942ef00d1e43bc and can be merged to 2.3.x versions, however you do not have a 2.3.x branch and this change in my opnion isn't for a 2.4.x version (master). Do you mind create a 2.3.x branch from last 2.3.x tag so I can do a pull request :)?

Thx in advance!

**Comment by acdha** [comment]
Since it's a new feature I think it should go in 2.4.

**Comment by chronossc** [comment]
Created the PR #1191. In that same PR I expose my opnion about why we should apply that feature on 2.3.x version.
