### ISSUE TITLE
Sphinx RT Index Backend.

### ISSUE THREAD

**Issue by btimby** [django-haystack/django-haystack#485]
We use Sphinx for searching. Currently we are using SphinxSE to allow us to query Sphinx using the Django ORM.

However, we are planning a move away from SphinxSE, and our currently selected implementation will use Sphinx RT Indexes and Haystack for performing the search.

As such, I have started a Sphinx backend for Haystack that uses SphinxQL and Sphinx RT Indexes.

Sphinx RT Indexes differ from regular indexes because they are not built using the command line tool indexer. They are build by using SQL INSERT/REPLACE INTO/DELETE statements.

I think this is a better fit for Haystack than using indexer to build and the Sphinx Python API to issue search queries.

This is my first experience with Haystack, so I imagine I am doing quite a few things wrong and have cut a few corners at this point. The backend is located here:

https://github.com/btimby/sphinx-haystack/blob/master/sphinx_haystack.py

Currently it can perform simple searches against the index. I just wanted to send a heads-up so that I can get some feedback before moving too far down this path.

**Comment by jorgecarleitao** [comment]
I'm maintaining an app for using Sphinx in Django: https://github.com/jorgecarleitao/django-sphinxql . It still doesn't support real time indexes though.

**Comment by acdha** [comment]
https://django-haystack.readthedocs.io/en/latest/backend_support.html now has a note pointing people to @jorgecarleitao's django-sphinxql. If anyone else wants to work on this, I'd vote for starting with a separate backend plugin so you don't have to wait on me to get releases out.

**Comment by jorgecarleitao** [comment]
Thanks @acdha.
FYI, Sphinx is licensed under GPL. This alone justifies a separated backend plugin, as in Xapian backend.
