### ISSUE TITLE
Sorting on 'text' or CharFields with ElasticSearch 

### ISSUE THREAD

**Issue by nkeilar** [django-haystack/django-haystack#569]
I'm pretty much running over what is mentioned here with the ElasticSearch backend. 

http://groups.google.com/group/django-haystack/tree/browse_frm/month/2009-10/0bd0046ce9ec40a7?rnum=11&lnk=nl

Specifically running: 

SearchQuerySet().order_by('name')

with 

class PersonIndex(indexes.RealTimeSearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    name = indexes.CharField(model_attr='fullname')

and 

class CompanyIndex(indexes.RealTimeSearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    name = indexes.CharField(model_attr='name')

yeilds no results

Can anyone confirm this is an issue?

Context: I'd really like to be able to have a drop down with sort by name, dates(various), model fields (various). 

Thanks for the great work. Happy to dig deeper if someone else can confirm its a problem. 

Cheers, 

Nathan

**Comment by SalahAdDin** [comment]
Hi, anyone fix this bug ??? :+1:

**Comment by jeury301** [comment]
> To sort on a CharField, make it storable, but not indexable.
> `sorted_name = indexes.CharField(indexed=False, stored=True)`
> 
> If you need to have it sortable and indexable, use two different fields in the SearchIndex.

This literally saved my day!
