### ISSUE TITLE
Multiple indexes per model

### ISSUE THREAD

**Issue by matclayton** [django-haystack/django-haystack#595]
We have a potential use case where we would like to have multiple indexes per model, and haystack seems to prohibit this at the moment. These indexes would be very different and use different fields etc. 

Maybe the solution is to combine into a giant index, however it feels like it would be good to allow multiple indexes per models. Especially when thinking about internal and external tooling.

**Comment by grjones** [comment]
There are many uses cases for needing multiple indexes for a single model. We had to do this using hacks in our project.  +1 to make this a real thing.

**Comment by acdha** [comment]
@grjones a fair amount has changed in the last 5 years since this ticket was created. If you have an idea for how this could be implemented, I think it'd be best to open an issue or pull request with a concrete use-case and proposed implementation strategy.
