### ISSUE TITLE
Whoosh only orders by one criteria instead of many - one after another 

### ISSUE THREAD

**Issue by TTGmarkad** [django-haystack/django-haystack#604]
With Whoosh as Search Engine, the search results are sorted according to one instead of all given criteria.
##### Example:

_SearchIndex_:

``` python
class PersonIndex(SearchIndex):
    last_name = CharField(model_attr="last_name")
    first_name = CharField(model_attr="first_name")
```

This

``` python
SearchQuerySet().filter(last_name='foo').order_by('last_name', 'first_name')
```

whould return a SearchQuerySet, that is ordered by 'last_name' and not by 'last_name' and 'first_name'.
##### possible solution:

I think, that the problem is the line 307 in the file "haystack/backends/whoosh_backend.py": 

``` python
sort_by = sort_by_list[0]
```

This line should probably be replaced with:

``` python
sort_by = sort_by_list
```

This works for me.

**Comment by rjhelms** [comment]
I'm experiencing this same issue in version 2.6., and same fix as suggested by @TTGmarkad still seems to work. I've submitted this as pull request #1570.
