### ISSUE TITLE
Ghost Duplicate SearchIndex

### ISSUE THREAD

**Issue by saulshanabrook** [django-haystack/django-haystack#615]
When I try to run `./manage.py rebuild_index`, Haystack thinks that one of my models has more than one search index for it:

     django.core.exceptions.ImproperlyConfigured: Model '<class 'canada.apps.updates.models.Update'>' has more than one 'SearchIndex`` handling it. Please exclude either '<canada.apps.updates.search_indexes.UpdateIndex object at 0x1021cddb8>' or '<canada.apps.updates.search_indexes.UpdateIndex object at 0x1021cde20>' using the 'HAYSTACK_EXCLUDED_INDEXES' setting.

However If I exclude that app or delete the search index, the other apps work fine. My `search_indexes.py` for the app looks like:

    from haystack import indexes
    from .models import Update

    class UpdateIndex(indexes.SearchIndex, indexes.Indexable):
        text = indexes.CharField(document=True, use_template=True)

        def get_model(self):
            return Update

It seems that for some reason Haystack is importing it twice as different objects. My other apps' `search_indexes.py` look exactly the same, so I don't' know why this app is tripping it up.

**Comment by stints** [comment]
I'm guessing this has been pushed back to v2.5?  Deleting the pyc will work some of the times so I'm able to continue working without much hassle but it's a bit annoying.

**Comment by wanggaolin** [comment]
https://www.lssin.com/blog/read.html?id=118
