### ISSUE TITLE
how to set analyzer to haystack with elasticsearch

### ISSUE THREAD

**Issue by ppdouble** [django-haystack/django-haystack#639]
I am using haystack v2.0.0beta, elasticsearch 0.18.5 , I installed an analyzer plugin named 'ik-analyzer' to elasticsearch 0.18.5, which is for analysing Asia character. How to use this analyzer in haystack, I didnt find relational information in haystack documention. Any one has same experience?

**Comment by nikitinsm** [comment]
+1
