### ISSUE TITLE
RealTimeSearchIndex.update_object always gets using='default'

### ISSUE THREAD

**Issue by jwgcarlson** [django-haystack/django-haystack#649]
I'm trying to use Haystack (latest master) with ElasticSearch.  I have several Haystack connections defined, one for each ElasticSearch index that I would like to use, and I would like to update the indexes in real-time.

The problem is that the ```RealTimeSearchIndex.update_object``` method (which is connected to the ```post_save``` signal for the associated model) always gets called with the 'using' argument set to the current _database_ alias ([Django docs](https://docs.djangoproject.com/en/dev/ref/signals/#post-save)).  This completely bypasses Haystack's connection routing abstraction.

A simple fix would be to connect the signal to an intermediate method, that calls ```update_object``` with using=None, e.g.

```
class RealTimeSearchIndex(SearchIndex):
    def _post_save_handler(self, instance, using=None, **kwargs):
        self.update_object(instance, using=None, **kwargs)
    def _setup_save(self):
        signals.post_save.connect(self._post_save_handler, sender=self.get_model())
    ...
```

**Comment by acdha** [comment]
Can you confirm that this is still an issue now and re-open if it is?
