### ISSUE TITLE
AttributeError: 'FileIndex' object has no attribute 'backend'

### ISSUE THREAD

**Issue by justhamade** [django-haystack/django-haystack#663]
Following the example here https://github.com/toastdriven/django-haystack/blob/master/docs/rich_content_extraction.rst
I get the following error.
AttributeError: 'FileIndex' object has no attribute 'backend'

It looks like backend should be _get_backend() which seems to work.

**Comment by jpatel3** [comment]
+1

running into the same issue, maybe it has something to do with what underlying backend is used Solr, whoosh or ...

**Comment by acdha** [comment]
That looks like API drift. I just made https://github.com/acdha/django-haystack/commit/5c441bf6c688c384f53f2d20f540487dabf13a7a which replaces `_get_backend()` with a better name for a public method and updates the documentation.
