### ISSUE TITLE
Highlight - Return full text 

### ISSUE THREAD

**Issue by apavillet** [django-haystack/django-haystack#748]
When we use highlight with a backend like elasticsearch, everything works fine except for the fact that the text are centered around the "highlighted" terms.

I'd be nice to have an option to return the full text with each term highlighted in it.

**Comment by weeheavy** [comment]
Same with Solr 5.0.0. I'd even vote for the "return full text" to be the default. Also, I'd love to have this feature in general.

**Comment by petkostas** [comment]
I Vote for this one as well, most of the times we need the full text displayed (with the highlighted search term) rather a truncated part of it.

**Comment by SteveByerly** [comment]
This is currently being addressed in #1402 - after reading the comments, i think i might change the approach, but hope to get it merged in a coming release.
