### ISSUE TITLE
Error message for duplicate index classes is out of date

### ISSUE THREAD

**Issue by davesque** [django-haystack/django-haystack#796]
### Steps to re-create:

1. Create an app with two index classes handling the same model and add it to `settings.INSTALLED_APPS`.
2. Run `python manage.py build_solr_schema`.

### Actual behavior:

An exception is thrown with an error message like the following:

    django.core.exceptions.ImproperlyConfigured: Model '<class 'cms.models.pagemodel.Page_En'>' has more than one 'SearchIndex`` handling it. Please exclude either '<haystack.indexes.ENPageIndex object at 0x3747ce8>' or '<haystack.indexes.ENPageIndex object at 0x3747db8>' using the 'HAYSTACK_EXCLUDED_INDEXES' setting.

...which refers to the `HAYSTACK_EXCLUDED_INDEXES` setting which I believe is no longer in use.

### Expected behavior:

The error message will refer to the `EXCLUDED_INDEXES` setting which is defined in `settings.HAYSTACK_CONNECTIONS`.

A pull request can be found [here](https://github.com/toastdriven/django-haystack/pull/795).

**Comment by sbaechler** [comment]
I guess this issue can be closed then.
