### ISSUE TITLE
Support for 'missing' and 'exists' filters

### ISSUE THREAD

**Issue by nrsimha** [django-haystack/django-haystack#824]
Is it possible to use 'missing' or 'exists' filters in Haystack using Elasticsearch?

http://www.elasticsearch.org/guide/reference/query-dsl/missing-filter/
http://www.elasticsearch.org/guide/reference/query-dsl/exists-filter/

**Comment by anentropic** [comment]
It seems to work

Shame this could not have followed the Django convention with `fieldname__exists=True|False` instead of a different undocumented(?) usage
