### ISSUE TITLE
ElasticSearch update broke facets in haystack

### ISSUE THREAD

**Issue by fijter** [django-haystack/django-haystack#850]
Facets return lowercase, broken down to words facets with ElasticSearch 0.90.3 while 0.90.1 works as expected, it returns the full indexed value. 

So, with 0.90.3 it returns the following facets:
camera's (292)
digital (292)

And with 0.90.1 it returns the following:
Digital camera's (292)

I tested it with Haystack 9.10 and pyelasticsearch 0.6, it worked fine with ElasticSearch 0.90.1 but doesn't work as expected with 0.90.3, I downgraded to 0.90.1 and now it is working again but this doesn't look like a permanent solution.

**Comment by avorio** [comment]
I'm experiencing the exact same issue.

```python
serial = indexes.CharField(model_attr='serial__title', faceted=True, null=True)
```

A similarity between this and the original post is that we are both using `__` to interact with a ForeignKey field. Could that be the root of the problem, perhaps? Other facets are working fine.
