### ISSUE TITLE
unknown field 'django_id' (Solr 4.5)

### ISSUE THREAD

**Issue by ghost** [django-haystack/django-haystack#878]
Hello, When I'm tried rebuild_index get this:

Failed to add documents to Solr: [Reason: None]
<response><lst name="responseHeader"><int name="status">400</int><int name="QTime">4</int></lst><lst name="error"><str name="msg">ERROR: [doc=movies.film.1] unknown field 'django_id'</str><int name="code">400</int></lst></response>
Failed to add documents to Solr: [Reason: None]
<response><lst name="responseHeader"><int name="status">400</int><int name="QTime">1</int></lst><lst name="error"><str name="msg">ERROR: [doc=movies.film.1016] unknown field 'django_id'</str><int name="code">400</int></lst></response>
Indexing 9 series
Failed to add documents to Solr: [Reason: None]
<response><lst name="responseHeader"><int name="status">400</int><int name="QTime">2</int></lst><lst name="error"><str name="msg">ERROR: [doc=series.serie.1] unknown field 'django_id'</str><int name="code">400</int></lst></response>

I'm use Haystack 2.1 and Solr 4.5.

Thanks.

**Comment by uditagarwal** [comment]
The above changes suggested work for me. It wasn't working earlier, but it turns out I mainly just forgot to restart Solr, after I made changes to the schema.

**Comment by bgarcial** [comment]
The @furins suggestions works for me
