### ISSUE TITLE
ElasticSearch and distances

### ISSUE THREAD

**Issue by Mibou** [django-haystack/django-haystack#957]
Hello,

Elasticsearch 1.0 only accepts distances as a string with unit integrated (for example "12km") while Django-Haystack uses a simple float.

Example Django-Haystack output : 

{"sort": [{"_geo_distance": {"location": [48.39, -4.4856], "unit": "km", "order": "asc"}}], "query": {"filtered": {"filter": {"bool": {"must": [{"terms": {"django_ct": ["utilisateurs.magasin"]}}, {"geo_distance": {"distance": 30.0, "location": {"lat": -4.4856, "lon": 48.39}}}]}}, "query": {"query_string": {"query": "(partenaire:(\"3\"))", "default_operator": "AND", "default_field": "text", "auto_generate_phrase_queries": true, "analyze_wildcard": true}}}}, "from": 0, "size": 1}

Origin of the Django-Haystack geo_distance :

https://github.com/toastdriven/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L437

ElasticSearch reference for geo_distance :

http://www.elasticsearch.org/guide/en/elasticsearch/reference/master/query-dsl-geo-distance-filter.html#_options_3

**Comment by acdha** [comment]
Closing this ticket since #1003 was merged
